# Set the compiler/linker for the build:
ifeq ($(strip $(COMPILER)),clang)
CC=clang
else ifeq ($(strip $(COMPILER)),gcc)
CC=g++
else
CC=clang
endif
AR=ar rcs
LNKSO=$(CC) -shared

# Set a timer for make test/check
ifeq ($(subst 1,Y,$(subst YES,Y,$(strip $(TIME)))),Y)
TIMECMD=/usr/bin/time -f "%C running %e seconds"
else
TIMECMD=
endif

# Debug and release flags, RELEASE=Y highest optimization level else create debug symbols and buil with lowest optimization level
ifeq ($(subst 1,Y,$(subst YES,Y,$(strip $(RELEASE)))),Y)
DEBUGFLAGS:=-O3
else
ifeq ($(strip $(CC)),clang)
DEBUGFLAGS:=-ggdb -g3 -O0 -fstandalone-debug
else
DEBUGFLAGS:=-ggdb -g3 -O0
endif
endif

# Flag for using an allocator always throwing bad_alloc as upstream memory resource for the monotonic buffer resource 
# used for structures intended to be allocated on the stack. This must not be set in a release build and not in all cases of a debug build.
ifeq ($(subst 1,Y,$(subst YES,Y,$(strip $(TESTLOCALMEM)))),Y)
DEBUGFLAGS:=$(DEBUGFLAGS) -DMEWA_TEST_LOCAL_MEMORY_RESOURCE
endif

# Switch verbosity on for build and make test/check
ifeq ($(subst 1,Y,$(subst YES,Y,$(strip $(VERBOSE)))),Y)
CXXVBFLAGS 	:=-v
TSTVBFLAGS 	:=-V
endif

# Set default PREFIX and installation dir of manpage
ifeq ($(strip $(PREFIX)),/usr)
MANPAGES := `man --path | awk  '1' RS=":" | grep /usr/share | awk 'NR==1{print $1}'`
else ifeq ($(strip $(PREFIX)),/usr/local)
MANPAGES := `man --path | awk  '1' RS=":" | grep /usr/local | awk 'NR==1{print $1}'`
else ifeq ($(strip $(PREFIX)),)
MANPAGES := `man --path | awk  '1' RS=":" | grep /usr/local | awk 'NR==1{print $1}'`
PREFIX   := /usr/local
else
MANPAGES := $(PREFIX)/man
endif

# Include path variables for Lua in file generated by ./configure
ifeq ($(wildcard Lua.inc),)
$(error File Lua.inc not found. Please run ./configure first!)
endif

include Lua.inc

# Project settings:
BUILDDIR := build
DESTINATION := $(PREFIX)/bin
INCDEST  := $(PREFIX)/include
MAKEDEP  := Lua.inc configure
SRCDIR   := src
INCDIR   := include
TESTDIR  := tests
DOCDIR   := doc
STDFLAGS := -std=c++17
CXXFLAGS := -c $(STDFLAGS) $(CXXVBFLAGS) $(DEBUGFLAGS) -fPIC -Wall -Wshadow -pedantic -Wfatal-errors -fvisibility=hidden -pthread
INCFLAGS := -I$(SRCDIR) -I$(LUAINC) -I$(INCDIR)
LDFLAGS  := -g -pthread
LDLIBS   := -lm -lstdc++
LIBOBJS  := $(BUILDDIR)/lexer.o \
		$(BUILDDIR)/automaton.o $(BUILDDIR)/automaton_tostring.o $(BUILDDIR)/automaton_parser.o \
		$(BUILDDIR)/typedb.o \
                $(BUILDDIR)/fileio.o $(BUILDDIR)/strings.o $(BUILDDIR)/error.o
MODOBJS  := $(BUILDDIR)/lualib_mewa.o \
		$(BUILDDIR)/lua_load_automaton.o $(BUILDDIR)/lua_run_compiler.o \
		$(BUILDDIR)/lua_serialize.o $(BUILDDIR)/lua_parameter.o
LIBRARY  := $(BUILDDIR)/libmewa.a
MODULE   := $(BUILDDIR)/mewa.so
TESTPRG  := $(BUILDDIR)/testError $(BUILDDIR)/testLexer $(BUILDDIR)/testScope $(BUILDDIR)/testRandomScope \
		$(BUILDDIR)/testRandomIdentMap $(BUILDDIR)/testAutomaton \
		$(BUILDDIR)/testTypeDb $(BUILDDIR)/testRandomTypeDb
PROGRAM  := $(BUILDDIR)/mewa

# Build targets:
all : build $(LIBRARY) $(PROGRAM) $(MODULE) $(TESTPRG) $(MAKEDEP)

clean: build
	rm $(BUILDDIR)/* .depend
build:
	mkdir -p $(BUILDDIR)

# Generate include dependencies:
SOURCES := $(wildcard $(SRCDIR)/*.cpp)
TESTSRC := $(wildcard $(TESTDIR)/*.cpp)
depend: .depend
.depend: $(SOURCES) $(TESTSRC)
	$(CC) $(STDFLAGS) $(INCFLAGS) -MM $^ | sed -E 's@^([^: ]*[:])@\$(BUILDDIR)/\1@' > .depend
include .depend

# Build rules:
$(BUILDDIR)/%.o: $(SRCDIR)/%.cpp $(MAKEDEP)
	$(CC) $(CXXFLAGS) $(INCFLAGS) -c $< -o $@

$(BUILDDIR)/%.o: $(TESTDIR)/%.cpp $(MAKEDEP)
	$(CC) $(CXXFLAGS) $(INCFLAGS) -c $< -o $@

$(LIBRARY): $(LIBOBJS)
	$(AR) $(LIBRARY) $(LIBOBJS)

$(PROGRAM) $(TESTPRG): $(LIBRARY)

$(BUILDDIR)/%: $(BUILDDIR)/%.o
	$(CC) $(LDFLAGS) $(LDLIBS) -o $@ $< $(LIBRARY)

$(MODULE): $(LIBRARY) $(MODOBJS)
	$(LNKSO) $(LUALIBS) $(LDLIBS) -o $@ $(MODOBJS) $(LIBRARY)

test : all
	$(TIMECMD) $(BUILDDIR)/testError $(TSTVBFLAGS)
	$(TIMECMD) $(BUILDDIR)/testLexer $(TSTVBFLAGS)
	$(TIMECMD) $(BUILDDIR)/testScope $(TSTVBFLAGS)
	$(TIMECMD) $(BUILDDIR)/testRandomScope $(TSTVBFLAGS)
	$(TIMECMD) $(BUILDDIR)/testRandomIdentMap $(TSTVBFLAGS)
	$(TIMECMD) $(BUILDDIR)/testAutomaton $(TSTVBFLAGS)
	$(TIMECMD) $(BUILDDIR)/testTypeDb $(TSTVBFLAGS)
	$(TIMECMD) $(BUILDDIR)/testRandomTypeDb $(TSTVBFLAGS)
	tests/luatest.sh "$(LUABIN)"
check: test

install: all
	cp $(PROGRAM) $(DESTINATION)
	mkdir -p $(INCDEST)/mewa
	cp include/mewa/*.hpp $(INCDEST)/mewa/
	mkdir -p $(MANPAGES)/man1
	cp MANPAGE $(MANPAGES)/man1/mewa.1
	gzip -f $(MANPAGES)/man1/mewa.1
	cp $(MODULE) $(CMODPATH)

uninstall:
	rm $(CMODPATH)/mewa.so
	rm $(MANPAGES)/man1/mewa.1.gz
	rm $(INCDEST)/mewa/*.hpp
	rm $(DESTINATION)/mewa

# ONLY FOR DEVELOPERS (All generated files of make doc are checked in, so you only have to run this if you edit the docs or sources):
DOCSRC := $(wildcard $(DOCDIR)/*.md.in)
doc: all $(DOCSRC)
	@echo "Create documentation of program mewa from its man page ..."
	groff -mandoc -T pdf MANPAGE > $(DOCDIR)/program_mewa.pdf
	@echo "Substitute some .in files in $(DOCDIR) with verified examples. Needs perl installed ..."
	perl doc/gen/map_md_in.pl $(TSTVBFLAGS)

