Shift token "extern" at line 3 in state XXX, goto XXX
Shift token DQSTRING = "C" at line 3 in state XXX, goto XXX
Shift token "procedure" at line 3 in state XXX, goto XXX
Shift token IDENT = "printf" at line 3 in state XXX, goto XXX
Shift token '(' at line 3 in state XXX, goto XXX
Shift token "const" at line 3 in state XXX, goto XXX
Shift token IDENT = "byte" at line 3 in state XXX, goto XXX
Reduce #1 to typename by token '^' at line 3 in state XXX, goto XXX
Reduce #2 to typehdr by token '^' at line 3 in state XXX, call typehdr {const=true}, goto XXX
Reduce #1 to typegen by token '^' at line 3 in state XXX, goto XXX
Shift token '^' at line 3 in state XXX, goto XXX
Reduce #2 to typegen by token IDENT = "fmt" at line 3 in state XXX, call typegen_pointer {const=false}, goto XXX
Reduce #1 to typespec by token IDENT = "fmt" at line 3 in state XXX, call typespec, goto XXX
Shift token IDENT = "fmt" at line 3 in state XXX, goto XXX
Reduce #2 to extern_parameters by token "..." at line 3 in state XXX, call extern_paramdeftail, goto XXX
Reduce #1 to extern_paramlist by token "..." at line 3 in state XXX, call extern_paramdeflist, goto XXX
Shift token "..." at line 3 in state XXX, goto XXX
Shift token ')' at line 3 in state XXX, goto XXX
Shift token ';' at line 3 in state XXX, goto XXX
Reduce #9 to extern_definition by token "interface" at line 5 in state XXX, call extern_procdef_vararg, goto XXX
Reduce #0 to extern_definitionlist by token "interface" at line 5 in state XXX, goto XXX
Reduce #2 to extern_definitionlist by token "interface" at line 5 in state XXX, goto XXX
Shift token "interface" at line 5 in state XXX, goto XXX
Shift token IDENT = "Object" at line 5 in state XXX, goto XXX
Shift token '{' at line 6 in state XXX, goto XXX
Shift token "function" at line 7 in state XXX, goto XXX
Shift token IDENT = "x" at line 7 in state XXX, goto XXX
Shift token IDENT = "int" at line 7 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 7 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 7 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 7 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 7 in state XXX, call typespec, goto XXX
Shift token '(' at line 7 in state XXX, goto XXX
Reduce #0 to extern_paramlist by token ')' at line 7 in state XXX, call extern_paramdeflist, goto XXX
Shift token ')' at line 7 in state XXX, goto XXX
Shift token "const" at line 7 in state XXX, goto XXX
Shift token "nothrow" at line 7 in state XXX, goto XXX
Reduce #0 to funcattribute by token ';' at line 7 in state XXX, call funcattribute {const=false,throws=true}, goto XXX
Reduce #2 to funcattribute by token ';' at line 7 in state XXX, call funcattribute {throws=false}, goto XXX
Reduce #2 to funcattribute by token ';' at line 7 in state XXX, call funcattribute {const=true}, goto XXX
Shift token ';' at line 7 in state XXX, goto XXX
Reduce #8 to ininterf_definition by token "function" at line 8 in state XXX, call interface_funcdef, goto XXX
Shift token "function" at line 8 in state XXX, goto XXX
Shift token IDENT = "y" at line 8 in state XXX, goto XXX
Shift token IDENT = "int" at line 8 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 8 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 8 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 8 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 8 in state XXX, call typespec, goto XXX
Shift token '(' at line 8 in state XXX, goto XXX
Reduce #0 to extern_paramlist by token ')' at line 8 in state XXX, call extern_paramdeflist, goto XXX
Shift token ')' at line 8 in state XXX, goto XXX
Shift token "const" at line 8 in state XXX, goto XXX
Shift token "nothrow" at line 8 in state XXX, goto XXX
Reduce #0 to funcattribute by token ';' at line 8 in state XXX, call funcattribute {const=false,throws=true}, goto XXX
Reduce #2 to funcattribute by token ';' at line 8 in state XXX, call funcattribute {throws=false}, goto XXX
Reduce #2 to funcattribute by token ';' at line 8 in state XXX, call funcattribute {const=true}, goto XXX
Shift token ';' at line 8 in state XXX, goto XXX
Reduce #8 to ininterf_definition by token "function" at line 9 in state XXX, call interface_funcdef, goto XXX
Shift token "function" at line 9 in state XXX, goto XXX
Shift token IDENT = "ofs_x" at line 9 in state XXX, goto XXX
Shift token IDENT = "int" at line 9 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 9 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 9 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 9 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 9 in state XXX, call typespec, goto XXX
Shift token '(' at line 9 in state XXX, goto XXX
Shift token IDENT = "int" at line 9 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "addx" at line 9 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "addx" at line 9 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "addx" at line 9 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "addx" at line 9 in state XXX, call typespec, goto XXX
Shift token IDENT = "addx" at line 9 in state XXX, goto XXX
Reduce #2 to extern_parameters by token ')' at line 9 in state XXX, call extern_paramdeftail, goto XXX
Reduce #1 to extern_paramlist by token ')' at line 9 in state XXX, call extern_paramdeflist, goto XXX
Shift token ')' at line 9 in state XXX, goto XXX
Shift token "const" at line 9 in state XXX, goto XXX
Shift token "nothrow" at line 9 in state XXX, goto XXX
Reduce #0 to funcattribute by token ';' at line 9 in state XXX, call funcattribute {const=false,throws=true}, goto XXX
Reduce #2 to funcattribute by token ';' at line 9 in state XXX, call funcattribute {throws=false}, goto XXX
Reduce #2 to funcattribute by token ';' at line 9 in state XXX, call funcattribute {const=true}, goto XXX
Shift token ';' at line 9 in state XXX, goto XXX
Reduce #8 to ininterf_definition by token "function" at line 10 in state XXX, call interface_funcdef, goto XXX
Shift token "function" at line 10 in state XXX, goto XXX
Shift token IDENT = "ofs_y" at line 10 in state XXX, goto XXX
Shift token IDENT = "int" at line 10 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 10 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 10 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 10 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 10 in state XXX, call typespec, goto XXX
Shift token '(' at line 10 in state XXX, goto XXX
Shift token IDENT = "int" at line 10 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "addy" at line 10 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "addy" at line 10 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "addy" at line 10 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "addy" at line 10 in state XXX, call typespec, goto XXX
Shift token IDENT = "addy" at line 10 in state XXX, goto XXX
Reduce #2 to extern_parameters by token ')' at line 10 in state XXX, call extern_paramdeftail, goto XXX
Reduce #1 to extern_paramlist by token ')' at line 10 in state XXX, call extern_paramdeflist, goto XXX
Shift token ')' at line 10 in state XXX, goto XXX
Shift token "const" at line 10 in state XXX, goto XXX
Shift token "nothrow" at line 10 in state XXX, goto XXX
Reduce #0 to funcattribute by token ';' at line 10 in state XXX, call funcattribute {const=false,throws=true}, goto XXX
Reduce #2 to funcattribute by token ';' at line 10 in state XXX, call funcattribute {throws=false}, goto XXX
Reduce #2 to funcattribute by token ';' at line 10 in state XXX, call funcattribute {const=true}, goto XXX
Shift token ';' at line 10 in state XXX, goto XXX
Reduce #8 to ininterf_definition by token '}' at line 11 in state XXX, call interface_funcdef, goto XXX
Reduce #0 to ininterf_definitionlist by token '}' at line 11 in state XXX, goto XXX
Reduce #2 to ininterf_definitionlist by token '}' at line 11 in state XXX, goto XXX
Reduce #2 to ininterf_definitionlist by token '}' at line 11 in state XXX, goto XXX
Reduce #2 to ininterf_definitionlist by token '}' at line 11 in state XXX, goto XXX
Reduce #2 to ininterf_definitionlist by token '}' at line 11 in state XXX, goto XXX
Shift token '}' at line 11 in state XXX, goto XXX
Reduce #5 to interfacedefinition by token "interface" at line 13 in state XXX, call interfacedef, goto XXX
Reduce #1 to free_definition by token "interface" at line 13 in state XXX, call definition 1, goto XXX
Shift token "interface" at line 13 in state XXX, goto XXX
Shift token IDENT = "ObjectUpdater" at line 13 in state XXX, goto XXX
Shift token '{' at line 14 in state XXX, goto XXX
Shift token "operator" at line 15 in state XXX, goto XXX
Shift token '=' at line 15 in state XXX, goto XXX
Reduce #1 to operatordecl by token '(' at line 15 in state XXX, call operatordecl {name="=",symbol="assign"}, goto XXX
Shift token '(' at line 15 in state XXX, goto XXX
Shift token IDENT = "int" at line 15 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "x_" at line 15 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "x_" at line 15 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "x_" at line 15 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "x_" at line 15 in state XXX, call typespec, goto XXX
Shift token IDENT = "x_" at line 15 in state XXX, goto XXX
Shift token ',' at line 15 in state XXX, goto XXX
Shift token IDENT = "int" at line 15 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "y_" at line 15 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "y_" at line 15 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "y_" at line 15 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "y_" at line 15 in state XXX, call typespec, goto XXX
Shift token IDENT = "y_" at line 15 in state XXX, goto XXX
Reduce #2 to extern_parameters by token ')' at line 15 in state XXX, call extern_paramdeftail, goto XXX
Reduce #4 to extern_parameters by token ')' at line 15 in state XXX, call extern_paramdef, goto XXX
Reduce #1 to extern_paramlist by token ')' at line 15 in state XXX, call extern_paramdeflist, goto XXX
Shift token ')' at line 15 in state XXX, goto XXX
Shift token "nothrow" at line 15 in state XXX, goto XXX
Reduce #0 to funcattribute by token ';' at line 15 in state XXX, call funcattribute {const=false,throws=true}, goto XXX
Reduce #2 to funcattribute by token ';' at line 15 in state XXX, call funcattribute {throws=false}, goto XXX
Shift token ';' at line 15 in state XXX, goto XXX
Reduce #7 to ininterf_definition by token '}' at line 16 in state XXX, call interface_operator_procdef, goto XXX
Reduce #0 to ininterf_definitionlist by token '}' at line 16 in state XXX, goto XXX
Reduce #2 to ininterf_definitionlist by token '}' at line 16 in state XXX, goto XXX
Shift token '}' at line 16 in state XXX, goto XXX
Reduce #5 to interfacedefinition by token "class" at line 18 in state XXX, call interfacedef, goto XXX
Reduce #1 to free_definition by token "class" at line 18 in state XXX, call definition 1, goto XXX
Shift token "class" at line 18 in state XXX, goto XXX
Shift token IDENT = "Point" at line 18 in state XXX, goto XXX
Shift token ':' at line 18 in state XXX, goto XXX
Shift token IDENT = "Object" at line 18 in state XXX, goto XXX
Reduce #1 to typename by token ',' at line 18 in state XXX, goto XXX
Reduce #1 to typehdr by token ',' at line 18 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token ',' at line 18 in state XXX, goto XXX
Shift token ',' at line 18 in state XXX, goto XXX
Shift token IDENT = "ObjectUpdater" at line 18 in state XXX, goto XXX
Reduce #1 to typename by token '{' at line 19 in state XXX, goto XXX
Reduce #1 to typehdr by token '{' at line 19 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '{' at line 19 in state XXX, goto XXX
Reduce #1 to inheritlist by token '{' at line 19 in state XXX, call inheritdef 1, goto XXX
Reduce #3 to inheritlist by token '{' at line 19 in state XXX, call inheritdef 1, goto XXX
Shift token '{' at line 19 in state XXX, goto XXX
Shift token "public" at line 20 in state XXX, goto XXX
Reduce #1 to linkage by token "constructor" at line 20 in state XXX, call linkage {private=false,linkage="external",explicit=true}, goto XXX
Shift token "constructor" at line 20 in state XXX, goto XXX
Shift token '(' at line 20 in state XXX, goto XXX
Shift token IDENT = "int" at line 20 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "x_" at line 20 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "x_" at line 20 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "x_" at line 20 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "x_" at line 20 in state XXX, call typespec, goto XXX
Shift token IDENT = "x_" at line 20 in state XXX, goto XXX
Reduce #2 to paramdecl by token ',' at line 20 in state XXX, call paramdef, goto XXX
Shift token ',' at line 20 in state XXX, goto XXX
Shift token IDENT = "int" at line 20 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "y_" at line 20 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "y_" at line 20 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "y_" at line 20 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "y_" at line 20 in state XXX, call typespec, goto XXX
Shift token IDENT = "y_" at line 20 in state XXX, goto XXX
Reduce #2 to paramdecl by token ')' at line 20 in state XXX, call paramdef, goto XXX
Reduce #1 to parameters by token ')' at line 20 in state XXX, goto XXX
Reduce #3 to parameters by token ')' at line 20 in state XXX, goto XXX
Reduce #1 to parameterlist by token ')' at line 20 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 20 in state XXX, goto XXX
Shift token "nothrow" at line 20 in state XXX, goto XXX
Shift token '{' at line 21 in state XXX, goto XXX
Shift token IDENT = "m_x" at line 22 in state XXX, goto XXX
Reduce #1 to expression by token '=' at line 22 in state XXX, call variable, goto XXX
Shift token '=' at line 22 in state XXX, goto XXX
Shift token IDENT = "x_" at line 22 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 22 in state XXX, call variable, goto XXX
Reduce #3 to expression by token ';' at line 22 in state XXX, call binop "=", goto XXX
Shift token ';' at line 22 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "self" at line 23 in state XXX, call free_expression, goto XXX
Shift token IDENT = "self" at line 23 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 23 in state XXX, call variable, goto XXX
Shift token '.' at line 23 in state XXX, goto XXX
Shift token IDENT = "m_y" at line 23 in state XXX, goto XXX
Reduce #3 to expression by token '=' at line 23 in state XXX, call member, goto XXX
Shift token '=' at line 23 in state XXX, goto XXX
Shift token IDENT = "y_" at line 23 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 23 in state XXX, call variable, goto XXX
Reduce #3 to expression by token ';' at line 23 in state XXX, call binop "=", goto XXX
Shift token ';' at line 23 in state XXX, goto XXX
Reduce #2 to statement by token '}' at line 24 in state XXX, call free_expression, goto XXX
Reduce #0 to statementlist by token '}' at line 24 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 24 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 24 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 24 in state XXX, call codeblock, goto XXX
Shift token '}' at line 24 in state XXX, goto XXX
Reduce #7 to callablebody by token "public" at line 26 in state XXX, call callablebody {throws=false,const=false}, goto XXX
Reduce #3 to constructordefinition by token "public" at line 26 in state XXX, call constructordef, goto XXX
Reduce #1 to inclass_definition by token "public" at line 26 in state XXX, call definition_decl_impl_pass 4, goto XXX
Shift token "public" at line 26 in state XXX, goto XXX
Reduce #1 to linkage by token "operator" at line 26 in state XXX, call linkage {private=false,linkage="external",explicit=true}, goto XXX
Shift token "operator" at line 26 in state XXX, goto XXX
Shift token '=' at line 26 in state XXX, goto XXX
Reduce #1 to operatordecl by token '(' at line 26 in state XXX, call operatordecl {name="=",symbol="assign"}, goto XXX
Shift token '(' at line 26 in state XXX, goto XXX
Shift token IDENT = "int" at line 26 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "x_" at line 26 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "x_" at line 26 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "x_" at line 26 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "x_" at line 26 in state XXX, call typespec, goto XXX
Shift token IDENT = "x_" at line 26 in state XXX, goto XXX
Reduce #2 to paramdecl by token ',' at line 26 in state XXX, call paramdef, goto XXX
Shift token ',' at line 26 in state XXX, goto XXX
Shift token IDENT = "int" at line 26 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "y_" at line 26 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "y_" at line 26 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "y_" at line 26 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "y_" at line 26 in state XXX, call typespec, goto XXX
Shift token IDENT = "y_" at line 26 in state XXX, goto XXX
Reduce #2 to paramdecl by token ')' at line 26 in state XXX, call paramdef, goto XXX
Reduce #1 to parameters by token ')' at line 26 in state XXX, goto XXX
Reduce #3 to parameters by token ')' at line 26 in state XXX, goto XXX
Reduce #1 to parameterlist by token ')' at line 26 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 26 in state XXX, goto XXX
Shift token "nothrow" at line 26 in state XXX, goto XXX
Shift token '{' at line 27 in state XXX, goto XXX
Shift token IDENT = "self" at line 28 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 28 in state XXX, call variable, goto XXX
Shift token '.' at line 28 in state XXX, goto XXX
Shift token IDENT = "m_x" at line 28 in state XXX, goto XXX
Reduce #3 to expression by token '=' at line 28 in state XXX, call member, goto XXX
Shift token '=' at line 28 in state XXX, goto XXX
Shift token IDENT = "x_" at line 28 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 28 in state XXX, call variable, goto XXX
Reduce #3 to expression by token ';' at line 28 in state XXX, call binop "=", goto XXX
Shift token ';' at line 28 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "m_y" at line 29 in state XXX, call free_expression, goto XXX
Shift token IDENT = "m_y" at line 29 in state XXX, goto XXX
Reduce #1 to expression by token '=' at line 29 in state XXX, call variable, goto XXX
Shift token '=' at line 29 in state XXX, goto XXX
Shift token IDENT = "y_" at line 29 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 29 in state XXX, call variable, goto XXX
Reduce #3 to expression by token ';' at line 29 in state XXX, call binop "=", goto XXX
Shift token ';' at line 29 in state XXX, goto XXX
Reduce #2 to statement by token '}' at line 30 in state XXX, call free_expression, goto XXX
Reduce #0 to statementlist by token '}' at line 30 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 30 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 30 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 30 in state XXX, call codeblock, goto XXX
Shift token '}' at line 30 in state XXX, goto XXX
Reduce #7 to callablebody by token "public" at line 32 in state XXX, call callablebody {throws=false,const=false}, goto XXX
Reduce #4 to operatordefinition by token "public" at line 32 in state XXX, call operator_procdef, goto XXX
Reduce #1 to inclass_definition by token "public" at line 32 in state XXX, call definition_decl_impl_pass 4, goto XXX
Shift token "public" at line 32 in state XXX, goto XXX
Reduce #1 to linkage by token "function" at line 32 in state XXX, call linkage {private=false,linkage="external",explicit=true}, goto XXX
Shift token "function" at line 32 in state XXX, goto XXX
Shift token IDENT = "x" at line 32 in state XXX, goto XXX
Shift token IDENT = "int" at line 32 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 32 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 32 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 32 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 32 in state XXX, call typespec, goto XXX
Shift token '(' at line 32 in state XXX, goto XXX
Reduce #0 to parameterlist by token ')' at line 32 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 32 in state XXX, goto XXX
Shift token "const" at line 32 in state XXX, goto XXX
Shift token "nothrow" at line 32 in state XXX, goto XXX
Shift token '{' at line 33 in state XXX, goto XXX
Shift token "return" at line 34 in state XXX, goto XXX
Shift token IDENT = "m_x" at line 34 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 34 in state XXX, call variable, goto XXX
Shift token ';' at line 34 in state XXX, goto XXX
Reduce #3 to statement by token '}' at line 35 in state XXX, call return_value, goto XXX
Reduce #0 to statementlist by token '}' at line 35 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 35 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 35 in state XXX, call codeblock, goto XXX
Shift token '}' at line 35 in state XXX, goto XXX
Reduce #8 to callablebody by token "public" at line 37 in state XXX, call callablebody {throws=false,const=true}, goto XXX
Reduce #5 to functiondefinition by token "public" at line 37 in state XXX, call funcdef, goto XXX
Reduce #1 to inclass_definition by token "public" at line 37 in state XXX, call definition_decl_impl_pass 4, goto XXX
Shift token "public" at line 37 in state XXX, goto XXX
Reduce #1 to linkage by token "function" at line 37 in state XXX, call linkage {private=false,linkage="external",explicit=true}, goto XXX
Shift token "function" at line 37 in state XXX, goto XXX
Shift token IDENT = "y" at line 37 in state XXX, goto XXX
Shift token IDENT = "int" at line 37 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 37 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 37 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 37 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 37 in state XXX, call typespec, goto XXX
Shift token '(' at line 37 in state XXX, goto XXX
Reduce #0 to parameterlist by token ')' at line 37 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 37 in state XXX, goto XXX
Shift token "const" at line 37 in state XXX, goto XXX
Shift token "nothrow" at line 37 in state XXX, goto XXX
Shift token '{' at line 38 in state XXX, goto XXX
Shift token "return" at line 39 in state XXX, goto XXX
Shift token IDENT = "self" at line 39 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 39 in state XXX, call variable, goto XXX
Shift token '.' at line 39 in state XXX, goto XXX
Shift token IDENT = "m_y" at line 39 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 39 in state XXX, call member, goto XXX
Shift token ';' at line 39 in state XXX, goto XXX
Reduce #3 to statement by token '}' at line 40 in state XXX, call return_value, goto XXX
Reduce #0 to statementlist by token '}' at line 40 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 40 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 40 in state XXX, call codeblock, goto XXX
Shift token '}' at line 40 in state XXX, goto XXX
Reduce #8 to callablebody by token "function" at line 42 in state XXX, call callablebody {throws=false,const=true}, goto XXX
Reduce #5 to functiondefinition by token "function" at line 42 in state XXX, call funcdef, goto XXX
Reduce #1 to inclass_definition by token "function" at line 42 in state XXX, call definition_decl_impl_pass 4, goto XXX
Reduce #0 to linkage by token "function" at line 42 in state XXX, call linkage {private=false,linkage="external",explicit=false}, goto XXX
Shift token "function" at line 42 in state XXX, goto XXX
Shift token IDENT = "ofs_x" at line 42 in state XXX, goto XXX
Shift token IDENT = "int" at line 42 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 42 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 42 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 42 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 42 in state XXX, call typespec, goto XXX
Shift token '(' at line 42 in state XXX, goto XXX
Shift token IDENT = "int" at line 42 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "addx" at line 42 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "addx" at line 42 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "addx" at line 42 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "addx" at line 42 in state XXX, call typespec, goto XXX
Shift token IDENT = "addx" at line 42 in state XXX, goto XXX
Reduce #2 to paramdecl by token ')' at line 42 in state XXX, call paramdef, goto XXX
Reduce #1 to parameters by token ')' at line 42 in state XXX, goto XXX
Reduce #1 to parameterlist by token ')' at line 42 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 42 in state XXX, goto XXX
Shift token "const" at line 42 in state XXX, goto XXX
Shift token "nothrow" at line 42 in state XXX, goto XXX
Shift token '{' at line 43 in state XXX, goto XXX
Shift token "return" at line 44 in state XXX, goto XXX
Shift token IDENT = "m_x" at line 44 in state XXX, goto XXX
Reduce #1 to expression by token '+' at line 44 in state XXX, call variable, goto XXX
Shift token '+' at line 44 in state XXX, goto XXX
Shift token IDENT = "addx" at line 44 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 44 in state XXX, call variable, goto XXX
Reduce #3 to expression by token ';' at line 44 in state XXX, call binop "+", goto XXX
Shift token ';' at line 44 in state XXX, goto XXX
Reduce #3 to statement by token '}' at line 45 in state XXX, call return_value, goto XXX
Reduce #0 to statementlist by token '}' at line 45 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 45 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 45 in state XXX, call codeblock, goto XXX
Shift token '}' at line 45 in state XXX, goto XXX
Reduce #8 to callablebody by token "function" at line 47 in state XXX, call callablebody {throws=false,const=true}, goto XXX
Reduce #5 to functiondefinition by token "function" at line 47 in state XXX, call funcdef, goto XXX
Reduce #1 to inclass_definition by token "function" at line 47 in state XXX, call definition_decl_impl_pass 4, goto XXX
Reduce #0 to linkage by token "function" at line 47 in state XXX, call linkage {private=false,linkage="external",explicit=false}, goto XXX
Shift token "function" at line 47 in state XXX, goto XXX
Shift token IDENT = "ofs_y" at line 47 in state XXX, goto XXX
Shift token IDENT = "int" at line 47 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 47 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 47 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 47 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 47 in state XXX, call typespec, goto XXX
Shift token '(' at line 47 in state XXX, goto XXX
Shift token IDENT = "int" at line 47 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "addy" at line 47 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "addy" at line 47 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "addy" at line 47 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "addy" at line 47 in state XXX, call typespec, goto XXX
Shift token IDENT = "addy" at line 47 in state XXX, goto XXX
Reduce #2 to paramdecl by token ')' at line 47 in state XXX, call paramdef, goto XXX
Reduce #1 to parameters by token ')' at line 47 in state XXX, goto XXX
Reduce #1 to parameterlist by token ')' at line 47 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 47 in state XXX, goto XXX
Shift token "const" at line 47 in state XXX, goto XXX
Shift token "nothrow" at line 47 in state XXX, goto XXX
Shift token '{' at line 48 in state XXX, goto XXX
Shift token "return" at line 49 in state XXX, goto XXX
Shift token IDENT = "m_y" at line 49 in state XXX, goto XXX
Reduce #1 to expression by token '+' at line 49 in state XXX, call variable, goto XXX
Shift token '+' at line 49 in state XXX, goto XXX
Shift token IDENT = "addy" at line 49 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 49 in state XXX, call variable, goto XXX
Reduce #3 to expression by token ';' at line 49 in state XXX, call binop "+", goto XXX
Shift token ';' at line 49 in state XXX, goto XXX
Reduce #3 to statement by token '}' at line 50 in state XXX, call return_value, goto XXX
Reduce #0 to statementlist by token '}' at line 50 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 50 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 50 in state XXX, call codeblock, goto XXX
Shift token '}' at line 50 in state XXX, goto XXX
Reduce #8 to callablebody by token "public" at line 52 in state XXX, call callablebody {throws=false,const=true}, goto XXX
Reduce #5 to functiondefinition by token "public" at line 52 in state XXX, call funcdef, goto XXX
Reduce #1 to inclass_definition by token "public" at line 52 in state XXX, call definition_decl_impl_pass 4, goto XXX
Shift token "public" at line 52 in state XXX, goto XXX
Reduce #1 to linkage by token "function" at line 52 in state XXX, call linkage {private=false,linkage="external",explicit=true}, goto XXX
Shift token "function" at line 52 in state XXX, goto XXX
Shift token IDENT = "object" at line 52 in state XXX, goto XXX
Shift token IDENT = "Object" at line 52 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 52 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 52 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 52 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 52 in state XXX, call typespec, goto XXX
Shift token '(' at line 52 in state XXX, goto XXX
Reduce #0 to parameterlist by token ')' at line 52 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 52 in state XXX, goto XXX
Shift token "const" at line 52 in state XXX, goto XXX
Shift token "nothrow" at line 52 in state XXX, goto XXX
Shift token '{' at line 53 in state XXX, goto XXX
Shift token "return" at line 54 in state XXX, goto XXX
Shift token IDENT = "self" at line 54 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 54 in state XXX, call variable, goto XXX
Shift token '.' at line 54 in state XXX, goto XXX
Shift token IDENT = "Object" at line 54 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 54 in state XXX, call member, goto XXX
Shift token ';' at line 54 in state XXX, goto XXX
Reduce #3 to statement by token '}' at line 55 in state XXX, call return_value, goto XXX
Reduce #0 to statementlist by token '}' at line 55 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 55 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 55 in state XXX, call codeblock, goto XXX
Shift token '}' at line 55 in state XXX, goto XXX
Reduce #8 to callablebody by token "public" at line 56 in state XXX, call callablebody {throws=false,const=true}, goto XXX
Reduce #5 to functiondefinition by token "public" at line 56 in state XXX, call funcdef, goto XXX
Reduce #1 to inclass_definition by token "public" at line 56 in state XXX, call definition_decl_impl_pass 4, goto XXX
Shift token "public" at line 56 in state XXX, goto XXX
Reduce #1 to linkage by token "function" at line 56 in state XXX, call linkage {private=false,linkage="external",explicit=true}, goto XXX
Shift token "function" at line 56 in state XXX, goto XXX
Shift token IDENT = "updater" at line 56 in state XXX, goto XXX
Shift token IDENT = "ObjectUpdater" at line 56 in state XXX, goto XXX
Reduce #1 to typename by token '(' at line 56 in state XXX, goto XXX
Reduce #1 to typehdr by token '(' at line 56 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '(' at line 56 in state XXX, goto XXX
Reduce #1 to typespec by token '(' at line 56 in state XXX, call typespec, goto XXX
Shift token '(' at line 56 in state XXX, goto XXX
Reduce #0 to parameterlist by token ')' at line 56 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 56 in state XXX, goto XXX
Shift token "nothrow" at line 56 in state XXX, goto XXX
Shift token '{' at line 57 in state XXX, goto XXX
Shift token "return" at line 58 in state XXX, goto XXX
Shift token IDENT = "self" at line 58 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 58 in state XXX, call variable, goto XXX
Shift token '.' at line 58 in state XXX, goto XXX
Shift token IDENT = "ObjectUpdater" at line 58 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 58 in state XXX, call member, goto XXX
Shift token ';' at line 58 in state XXX, goto XXX
Reduce #3 to statement by token '}' at line 59 in state XXX, call return_value, goto XXX
Reduce #0 to statementlist by token '}' at line 59 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 59 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 59 in state XXX, call codeblock, goto XXX
Shift token '}' at line 59 in state XXX, goto XXX
Reduce #7 to callablebody by token IDENT = "int" at line 61 in state XXX, call callablebody {throws=false,const=false}, goto XXX
Reduce #5 to functiondefinition by token IDENT = "int" at line 61 in state XXX, call funcdef, goto XXX
Reduce #1 to inclass_definition by token IDENT = "int" at line 61 in state XXX, call definition_decl_impl_pass 4, goto XXX
Shift token IDENT = "int" at line 61 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "m_x" at line 61 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "m_x" at line 61 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "m_x" at line 61 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "m_x" at line 61 in state XXX, call typespec, goto XXX
Shift token IDENT = "m_x" at line 61 in state XXX, goto XXX
Reduce #2 to variabledefinition by token ';' at line 61 in state XXX, call vardef, goto XXX
Shift token ';' at line 61 in state XXX, goto XXX
Reduce #2 to inclass_definition by token IDENT = "int" at line 62 in state XXX, call definition 2, goto XXX
Shift token IDENT = "int" at line 62 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "m_y" at line 62 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "m_y" at line 62 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "m_y" at line 62 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "m_y" at line 62 in state XXX, call typespec, goto XXX
Shift token IDENT = "m_y" at line 62 in state XXX, goto XXX
Reduce #2 to variabledefinition by token ';' at line 62 in state XXX, call vardef, goto XXX
Shift token ';' at line 62 in state XXX, goto XXX
Reduce #2 to inclass_definition by token '}' at line 63 in state XXX, call definition 2, goto XXX
Reduce #0 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 63 in state XXX, goto XXX
Shift token '}' at line 63 in state XXX, goto XXX
Reduce #7 to classdefinition by token "class" at line 65 in state XXX, call classdef, goto XXX
Reduce #1 to free_definition by token "class" at line 65 in state XXX, call definition 1, goto XXX
Shift token "class" at line 65 in state XXX, goto XXX
Shift token IDENT = "Line" at line 65 in state XXX, goto XXX
Shift token ':' at line 65 in state XXX, goto XXX
Shift token IDENT = "Point" at line 65 in state XXX, goto XXX
Reduce #1 to typename by token '{' at line 66 in state XXX, goto XXX
Reduce #1 to typehdr by token '{' at line 66 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token '{' at line 66 in state XXX, goto XXX
Reduce #1 to inheritlist by token '{' at line 66 in state XXX, call inheritdef 1, goto XXX
Shift token '{' at line 66 in state XXX, goto XXX
Shift token "public" at line 67 in state XXX, goto XXX
Reduce #1 to linkage by token "constructor" at line 67 in state XXX, call linkage {private=false,linkage="external",explicit=true}, goto XXX
Shift token "constructor" at line 67 in state XXX, goto XXX
Shift token '(' at line 67 in state XXX, goto XXX
Shift token IDENT = "int" at line 67 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "x_" at line 67 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "x_" at line 67 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "x_" at line 67 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "x_" at line 67 in state XXX, call typespec, goto XXX
Shift token IDENT = "x_" at line 67 in state XXX, goto XXX
Reduce #2 to paramdecl by token ',' at line 67 in state XXX, call paramdef, goto XXX
Shift token ',' at line 67 in state XXX, goto XXX
Shift token IDENT = "int" at line 67 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "y_" at line 67 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "y_" at line 67 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "y_" at line 67 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "y_" at line 67 in state XXX, call typespec, goto XXX
Shift token IDENT = "y_" at line 67 in state XXX, goto XXX
Reduce #2 to paramdecl by token ')' at line 67 in state XXX, call paramdef, goto XXX
Reduce #1 to parameters by token ')' at line 67 in state XXX, goto XXX
Reduce #3 to parameters by token ')' at line 67 in state XXX, goto XXX
Reduce #1 to parameterlist by token ')' at line 67 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 67 in state XXX, goto XXX
Shift token "nothrow" at line 67 in state XXX, goto XXX
Shift token '{' at line 68 in state XXX, goto XXX
Shift token IDENT = "self" at line 69 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 69 in state XXX, call variable, goto XXX
Shift token '.' at line 69 in state XXX, goto XXX
Shift token IDENT = "Point" at line 69 in state XXX, goto XXX
Reduce #3 to expression by token '=' at line 69 in state XXX, call member, goto XXX
Shift token '=' at line 69 in state XXX, goto XXX
Shift token '{' at line 69 in state XXX, goto XXX
Shift token IDENT = "x_" at line 69 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 69 in state XXX, call variable, goto XXX
Shift token ',' at line 69 in state XXX, goto XXX
Shift token IDENT = "y_" at line 69 in state XXX, goto XXX
Reduce #1 to expression by token '}' at line 69 in state XXX, call variable, goto XXX
Reduce #1 to expressionlist by token '}' at line 69 in state XXX, goto XXX
Reduce #3 to expressionlist by token '}' at line 69 in state XXX, goto XXX
Shift token '}' at line 69 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 69 in state XXX, call structure, goto XXX
Reduce #3 to expression by token ';' at line 69 in state XXX, call binop "=", goto XXX
Shift token ';' at line 69 in state XXX, goto XXX
Reduce #2 to statement by token '}' at line 70 in state XXX, call free_expression, goto XXX
Reduce #0 to statementlist by token '}' at line 70 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 70 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 70 in state XXX, call codeblock, goto XXX
Shift token '}' at line 70 in state XXX, goto XXX
Reduce #7 to callablebody by token "public" at line 72 in state XXX, call callablebody {throws=false,const=false}, goto XXX
Reduce #3 to constructordefinition by token "public" at line 72 in state XXX, call constructordef, goto XXX
Reduce #1 to inclass_definition by token "public" at line 72 in state XXX, call definition_decl_impl_pass 4, goto XXX
Shift token "public" at line 72 in state XXX, goto XXX
Reduce #1 to linkage by token "procedure" at line 72 in state XXX, call linkage {private=false,linkage="external",explicit=true}, goto XXX
Shift token "procedure" at line 72 in state XXX, goto XXX
Shift token IDENT = "move" at line 72 in state XXX, goto XXX
Shift token '(' at line 72 in state XXX, goto XXX
Shift token IDENT = "int" at line 72 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "x_" at line 72 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "x_" at line 72 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "x_" at line 72 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "x_" at line 72 in state XXX, call typespec, goto XXX
Shift token IDENT = "x_" at line 72 in state XXX, goto XXX
Reduce #2 to paramdecl by token ',' at line 72 in state XXX, call paramdef, goto XXX
Shift token ',' at line 72 in state XXX, goto XXX
Shift token IDENT = "int" at line 72 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "y_" at line 72 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "y_" at line 72 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "y_" at line 72 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "y_" at line 72 in state XXX, call typespec, goto XXX
Shift token IDENT = "y_" at line 72 in state XXX, goto XXX
Reduce #2 to paramdecl by token ')' at line 72 in state XXX, call paramdef, goto XXX
Reduce #1 to parameters by token ')' at line 72 in state XXX, goto XXX
Reduce #3 to parameters by token ')' at line 72 in state XXX, goto XXX
Reduce #1 to parameterlist by token ')' at line 72 in state XXX, call paramdeflist, goto XXX
Shift token ')' at line 72 in state XXX, goto XXX
Shift token "nothrow" at line 72 in state XXX, goto XXX
Shift token '{' at line 73 in state XXX, goto XXX
Shift token IDENT = "self" at line 74 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 74 in state XXX, call variable, goto XXX
Shift token '.' at line 74 in state XXX, goto XXX
Shift token IDENT = "Point" at line 74 in state XXX, goto XXX
Reduce #3 to expression by token '=' at line 74 in state XXX, call member, goto XXX
Shift token '=' at line 74 in state XXX, goto XXX
Shift token '{' at line 74 in state XXX, goto XXX
Shift token IDENT = "x_" at line 74 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 74 in state XXX, call variable, goto XXX
Shift token ',' at line 74 in state XXX, goto XXX
Shift token IDENT = "y_" at line 74 in state XXX, goto XXX
Reduce #1 to expression by token '}' at line 74 in state XXX, call variable, goto XXX
Reduce #1 to expressionlist by token '}' at line 74 in state XXX, goto XXX
Reduce #3 to expressionlist by token '}' at line 74 in state XXX, goto XXX
Shift token '}' at line 74 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 74 in state XXX, call structure, goto XXX
Reduce #3 to expression by token ';' at line 74 in state XXX, call binop "=", goto XXX
Shift token ';' at line 74 in state XXX, goto XXX
Reduce #2 to statement by token '}' at line 75 in state XXX, call free_expression, goto XXX
Reduce #0 to statementlist by token '}' at line 75 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 75 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 75 in state XXX, call codeblock, goto XXX
Shift token '}' at line 75 in state XXX, goto XXX
Reduce #7 to callablebody by token '}' at line 76 in state XXX, call callablebody {throws=false,const=false}, goto XXX
Reduce #4 to functiondefinition by token '}' at line 76 in state XXX, call procdef, goto XXX
Reduce #1 to inclass_definition by token '}' at line 76 in state XXX, call definition_decl_impl_pass 4, goto XXX
Reduce #0 to inclass_definitionlist by token '}' at line 76 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 76 in state XXX, goto XXX
Reduce #2 to inclass_definitionlist by token '}' at line 76 in state XXX, goto XXX
Shift token '}' at line 76 in state XXX, goto XXX
Reduce #7 to classdefinition by token "main" at line 78 in state XXX, call classdef, goto XXX
Reduce #1 to free_definition by token "main" at line 78 in state XXX, call definition 1, goto XXX
Reduce #0 to free_definitionlist by token "main" at line 78 in state XXX, goto XXX
Reduce #2 to free_definitionlist by token "main" at line 78 in state XXX, goto XXX
Reduce #2 to free_definitionlist by token "main" at line 78 in state XXX, goto XXX
Reduce #2 to free_definitionlist by token "main" at line 78 in state XXX, goto XXX
Reduce #2 to free_definitionlist by token "main" at line 78 in state XXX, goto XXX
Shift token "main" at line 78 in state XXX, goto XXX
Shift token '{' at line 78 in state XXX, goto XXX
Shift token "var" at line 79 in state XXX, goto XXX
Shift token IDENT = "float" at line 79 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "x" at line 79 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "x" at line 79 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "x" at line 79 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "x" at line 79 in state XXX, call typespec, goto XXX
Shift token IDENT = "x" at line 79 in state XXX, goto XXX
Shift token '=' at line 79 in state XXX, goto XXX
Shift token FLOAT = "1.23" at line 79 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 79 in state XXX, call constant "constexpr float", goto XXX
Reduce #4 to variabledefinition by token ';' at line 79 in state XXX, call vardef_assign, goto XXX
Shift token ';' at line 79 in state XXX, goto XXX
Reduce #3 to statement by token "var" at line 80 in state XXX, call definition 1, goto XXX
Shift token "var" at line 80 in state XXX, goto XXX
Shift token IDENT = "Line" at line 80 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "ab" at line 80 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "ab" at line 80 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "ab" at line 80 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "ab" at line 80 in state XXX, call typespec, goto XXX
Shift token IDENT = "ab" at line 80 in state XXX, goto XXX
Shift token '=' at line 80 in state XXX, goto XXX
Shift token '{' at line 80 in state XXX, goto XXX
Shift token FLOAT = "7.23" at line 80 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 80 in state XXX, call constant "constexpr float", goto XXX
Shift token ',' at line 80 in state XXX, goto XXX
Shift token FLOAT = "4.23" at line 80 in state XXX, goto XXX
Reduce #1 to expression by token '}' at line 80 in state XXX, call constant "constexpr float", goto XXX
Reduce #1 to expressionlist by token '}' at line 80 in state XXX, goto XXX
Reduce #3 to expressionlist by token '}' at line 80 in state XXX, goto XXX
Shift token '}' at line 80 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 80 in state XXX, call structure, goto XXX
Reduce #4 to variabledefinition by token ';' at line 80 in state XXX, call vardef_assign, goto XXX
Shift token ';' at line 80 in state XXX, goto XXX
Reduce #3 to statement by token "var" at line 81 in state XXX, call definition 1, goto XXX
Shift token "var" at line 81 in state XXX, goto XXX
Shift token IDENT = "Object" at line 81 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "obj" at line 81 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "obj" at line 81 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "obj" at line 81 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "obj" at line 81 in state XXX, call typespec, goto XXX
Shift token IDENT = "obj" at line 81 in state XXX, goto XXX
Shift token '=' at line 81 in state XXX, goto XXX
Shift token IDENT = "ab" at line 81 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 81 in state XXX, call variable, goto XXX
Shift token '.' at line 81 in state XXX, goto XXX
Shift token IDENT = "object" at line 81 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 81 in state XXX, call member, goto XXX
Shift token '(' at line 81 in state XXX, goto XXX
Shift token ')' at line 81 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 81 in state XXX, call operator "()", goto XXX
Reduce #4 to variabledefinition by token ';' at line 81 in state XXX, call vardef_assign, goto XXX
Shift token ';' at line 81 in state XXX, goto XXX
Reduce #3 to statement by token IDENT = "printf" at line 82 in state XXX, call definition 1, goto XXX
Shift token IDENT = "printf" at line 82 in state XXX, goto XXX
Reduce #1 to expression by token '(' at line 82 in state XXX, call variable, goto XXX
Shift token '(' at line 82 in state XXX, goto XXX
Shift token DQSTRING = "RESULT[1] x = %d\n" at line 82 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 82 in state XXX, call string_constant, goto XXX
Shift token ',' at line 82 in state XXX, goto XXX
Shift token IDENT = "obj" at line 82 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 82 in state XXX, call variable, goto XXX
Shift token '.' at line 82 in state XXX, goto XXX
Shift token IDENT = "x" at line 82 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 82 in state XXX, call member, goto XXX
Shift token '(' at line 82 in state XXX, goto XXX
Shift token ')' at line 82 in state XXX, goto XXX
Reduce #3 to expression by token ')' at line 82 in state XXX, call operator "()", goto XXX
Reduce #1 to expressionlist by token ')' at line 82 in state XXX, goto XXX
Reduce #3 to expressionlist by token ')' at line 82 in state XXX, goto XXX
Shift token ')' at line 82 in state XXX, goto XXX
Reduce #4 to expression by token ';' at line 82 in state XXX, call operator "()", goto XXX
Shift token ';' at line 82 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "printf" at line 83 in state XXX, call free_expression, goto XXX
Shift token IDENT = "printf" at line 83 in state XXX, goto XXX
Reduce #1 to expression by token '(' at line 83 in state XXX, call variable, goto XXX
Shift token '(' at line 83 in state XXX, goto XXX
Shift token DQSTRING = "RESULT[1] y = %d\n" at line 83 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 83 in state XXX, call string_constant, goto XXX
Shift token ',' at line 83 in state XXX, goto XXX
Shift token IDENT = "obj" at line 83 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 83 in state XXX, call variable, goto XXX
Shift token '.' at line 83 in state XXX, goto XXX
Shift token IDENT = "y" at line 83 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 83 in state XXX, call member, goto XXX
Shift token '(' at line 83 in state XXX, goto XXX
Shift token ')' at line 83 in state XXX, goto XXX
Reduce #3 to expression by token ')' at line 83 in state XXX, call operator "()", goto XXX
Reduce #1 to expressionlist by token ')' at line 83 in state XXX, goto XXX
Reduce #3 to expressionlist by token ')' at line 83 in state XXX, goto XXX
Shift token ')' at line 83 in state XXX, goto XXX
Reduce #4 to expression by token ';' at line 83 in state XXX, call operator "()", goto XXX
Shift token ';' at line 83 in state XXX, goto XXX
Reduce #2 to statement by token "var" at line 84 in state XXX, call free_expression, goto XXX
Shift token "var" at line 84 in state XXX, goto XXX
Shift token IDENT = "ObjectUpdater" at line 84 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "updater" at line 84 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "updater" at line 84 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "updater" at line 84 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "updater" at line 84 in state XXX, call typespec, goto XXX
Shift token IDENT = "updater" at line 84 in state XXX, goto XXX
Shift token '=' at line 84 in state XXX, goto XXX
Shift token IDENT = "ab" at line 84 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 84 in state XXX, call variable, goto XXX
Shift token '.' at line 84 in state XXX, goto XXX
Shift token IDENT = "updater" at line 84 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 84 in state XXX, call member, goto XXX
Shift token '(' at line 84 in state XXX, goto XXX
Shift token ')' at line 84 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 84 in state XXX, call operator "()", goto XXX
Reduce #4 to variabledefinition by token ';' at line 84 in state XXX, call vardef_assign, goto XXX
Shift token ';' at line 84 in state XXX, goto XXX
Reduce #3 to statement by token IDENT = "updater" at line 85 in state XXX, call definition 1, goto XXX
Shift token IDENT = "updater" at line 85 in state XXX, goto XXX
Reduce #1 to expression by token '=' at line 85 in state XXX, call variable, goto XXX
Shift token '=' at line 85 in state XXX, goto XXX
Shift token '{' at line 85 in state XXX, goto XXX
Shift token UINTEGER = "31" at line 85 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 85 in state XXX, call constant "constexpr uint", goto XXX
Shift token ',' at line 85 in state XXX, goto XXX
Shift token UINTEGER = "411" at line 85 in state XXX, goto XXX
Reduce #1 to expression by token '}' at line 85 in state XXX, call constant "constexpr uint", goto XXX
Reduce #1 to expressionlist by token '}' at line 85 in state XXX, goto XXX
Reduce #3 to expressionlist by token '}' at line 85 in state XXX, goto XXX
Shift token '}' at line 85 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 85 in state XXX, call structure, goto XXX
Reduce #3 to expression by token ';' at line 85 in state XXX, call binop "=", goto XXX
Shift token ';' at line 85 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "printf" at line 86 in state XXX, call free_expression, goto XXX
Shift token IDENT = "printf" at line 86 in state XXX, goto XXX
Reduce #1 to expression by token '(' at line 86 in state XXX, call variable, goto XXX
Shift token '(' at line 86 in state XXX, goto XXX
Shift token DQSTRING = "RESULT[2] x = %d\n" at line 86 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 86 in state XXX, call string_constant, goto XXX
Shift token ',' at line 86 in state XXX, goto XXX
Shift token IDENT = "obj" at line 86 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 86 in state XXX, call variable, goto XXX
Shift token '.' at line 86 in state XXX, goto XXX
Shift token IDENT = "x" at line 86 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 86 in state XXX, call member, goto XXX
Shift token '(' at line 86 in state XXX, goto XXX
Shift token ')' at line 86 in state XXX, goto XXX
Reduce #3 to expression by token ')' at line 86 in state XXX, call operator "()", goto XXX
Reduce #1 to expressionlist by token ')' at line 86 in state XXX, goto XXX
Reduce #3 to expressionlist by token ')' at line 86 in state XXX, goto XXX
Shift token ')' at line 86 in state XXX, goto XXX
Reduce #4 to expression by token ';' at line 86 in state XXX, call operator "()", goto XXX
Shift token ';' at line 86 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "printf" at line 87 in state XXX, call free_expression, goto XXX
Shift token IDENT = "printf" at line 87 in state XXX, goto XXX
Reduce #1 to expression by token '(' at line 87 in state XXX, call variable, goto XXX
Shift token '(' at line 87 in state XXX, goto XXX
Shift token DQSTRING = "RESULT[2] y = %d\n" at line 87 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 87 in state XXX, call string_constant, goto XXX
Shift token ',' at line 87 in state XXX, goto XXX
Shift token IDENT = "obj" at line 87 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 87 in state XXX, call variable, goto XXX
Shift token '.' at line 87 in state XXX, goto XXX
Shift token IDENT = "y" at line 87 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 87 in state XXX, call member, goto XXX
Shift token '(' at line 87 in state XXX, goto XXX
Shift token ')' at line 87 in state XXX, goto XXX
Reduce #3 to expression by token ')' at line 87 in state XXX, call operator "()", goto XXX
Reduce #1 to expressionlist by token ')' at line 87 in state XXX, goto XXX
Reduce #3 to expressionlist by token ')' at line 87 in state XXX, goto XXX
Shift token ')' at line 87 in state XXX, goto XXX
Reduce #4 to expression by token ';' at line 87 in state XXX, call operator "()", goto XXX
Shift token ';' at line 87 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "updater" at line 88 in state XXX, call free_expression, goto XXX
Shift token IDENT = "updater" at line 88 in state XXX, goto XXX
Reduce #1 to expression by token '=' at line 88 in state XXX, call variable, goto XXX
Shift token '=' at line 88 in state XXX, goto XXX
Shift token '{' at line 88 in state XXX, goto XXX
Shift token UINTEGER = "71" at line 88 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 88 in state XXX, call constant "constexpr uint", goto XXX
Shift token ',' at line 88 in state XXX, goto XXX
Shift token UINTEGER = "511" at line 88 in state XXX, goto XXX
Reduce #1 to expression by token '}' at line 88 in state XXX, call constant "constexpr uint", goto XXX
Reduce #1 to expressionlist by token '}' at line 88 in state XXX, goto XXX
Reduce #3 to expressionlist by token '}' at line 88 in state XXX, goto XXX
Shift token '}' at line 88 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 88 in state XXX, call structure, goto XXX
Reduce #3 to expression by token ';' at line 88 in state XXX, call binop "=", goto XXX
Shift token ';' at line 88 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "printf" at line 89 in state XXX, call free_expression, goto XXX
Shift token IDENT = "printf" at line 89 in state XXX, goto XXX
Reduce #1 to expression by token '(' at line 89 in state XXX, call variable, goto XXX
Shift token '(' at line 89 in state XXX, goto XXX
Shift token DQSTRING = "RESULT[3] x = %d\n" at line 89 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 89 in state XXX, call string_constant, goto XXX
Shift token ',' at line 89 in state XXX, goto XXX
Shift token IDENT = "obj" at line 89 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 89 in state XXX, call variable, goto XXX
Shift token '.' at line 89 in state XXX, goto XXX
Shift token IDENT = "ofs_x" at line 89 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 89 in state XXX, call member, goto XXX
Shift token '(' at line 89 in state XXX, goto XXX
Shift token SINTEGER = "-13" at line 89 in state XXX, goto XXX
Reduce #1 to expression by token ')' at line 89 in state XXX, call constant "constexpr int", goto XXX
Reduce #1 to expressionlist by token ')' at line 89 in state XXX, goto XXX
Shift token ')' at line 89 in state XXX, goto XXX
Reduce #4 to expression by token ')' at line 89 in state XXX, call operator "()", goto XXX
Reduce #1 to expressionlist by token ')' at line 89 in state XXX, goto XXX
Reduce #3 to expressionlist by token ')' at line 89 in state XXX, goto XXX
Shift token ')' at line 89 in state XXX, goto XXX
Reduce #4 to expression by token ';' at line 89 in state XXX, call operator "()", goto XXX
Shift token ';' at line 89 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "printf" at line 90 in state XXX, call free_expression, goto XXX
Shift token IDENT = "printf" at line 90 in state XXX, goto XXX
Reduce #1 to expression by token '(' at line 90 in state XXX, call variable, goto XXX
Shift token '(' at line 90 in state XXX, goto XXX
Shift token DQSTRING = "RESULT[3] y = %d\n" at line 90 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 90 in state XXX, call string_constant, goto XXX
Shift token ',' at line 90 in state XXX, goto XXX
Shift token IDENT = "obj" at line 90 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 90 in state XXX, call variable, goto XXX
Shift token '.' at line 90 in state XXX, goto XXX
Shift token IDENT = "ofs_y" at line 90 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 90 in state XXX, call member, goto XXX
Shift token '(' at line 90 in state XXX, goto XXX
Shift token UINTEGER = "1" at line 90 in state XXX, goto XXX
Reduce #1 to expression by token ')' at line 90 in state XXX, call constant "constexpr uint", goto XXX
Reduce #1 to expressionlist by token ')' at line 90 in state XXX, goto XXX
Shift token ')' at line 90 in state XXX, goto XXX
Reduce #4 to expression by token ')' at line 90 in state XXX, call operator "()", goto XXX
Reduce #1 to expressionlist by token ')' at line 90 in state XXX, goto XXX
Reduce #3 to expressionlist by token ')' at line 90 in state XXX, goto XXX
Shift token ')' at line 90 in state XXX, goto XXX
Reduce #4 to expression by token ';' at line 90 in state XXX, call operator "()", goto XXX
Shift token ';' at line 90 in state XXX, goto XXX
Reduce #2 to statement by token "var" at line 91 in state XXX, call free_expression, goto XXX
Shift token "var" at line 91 in state XXX, goto XXX
Shift token IDENT = "ObjectUpdater" at line 91 in state XXX, goto XXX
Reduce #1 to typename by token IDENT = "updater2" at line 91 in state XXX, goto XXX
Reduce #1 to typehdr by token IDENT = "updater2" at line 91 in state XXX, call typehdr {const=false}, goto XXX
Reduce #1 to typegen by token IDENT = "updater2" at line 91 in state XXX, goto XXX
Reduce #1 to typespec by token IDENT = "updater2" at line 91 in state XXX, call typespec, goto XXX
Shift token IDENT = "updater2" at line 91 in state XXX, goto XXX
Shift token '=' at line 91 in state XXX, goto XXX
Shift token IDENT = "updater" at line 91 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 91 in state XXX, call variable, goto XXX
Reduce #4 to variabledefinition by token ';' at line 91 in state XXX, call vardef_assign, goto XXX
Shift token ';' at line 91 in state XXX, goto XXX
Reduce #3 to statement by token IDENT = "updater2" at line 92 in state XXX, call definition 1, goto XXX
Shift token IDENT = "updater2" at line 92 in state XXX, goto XXX
Reduce #1 to expression by token '=' at line 92 in state XXX, call variable, goto XXX
Shift token '=' at line 92 in state XXX, goto XXX
Shift token '{' at line 92 in state XXX, goto XXX
Shift token UINTEGER = "32" at line 92 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 92 in state XXX, call constant "constexpr uint", goto XXX
Shift token ',' at line 92 in state XXX, goto XXX
Shift token UINTEGER = "412" at line 92 in state XXX, goto XXX
Reduce #1 to expression by token '}' at line 92 in state XXX, call constant "constexpr uint", goto XXX
Reduce #1 to expressionlist by token '}' at line 92 in state XXX, goto XXX
Reduce #3 to expressionlist by token '}' at line 92 in state XXX, goto XXX
Shift token '}' at line 92 in state XXX, goto XXX
Reduce #3 to expression by token ';' at line 92 in state XXX, call structure, goto XXX
Reduce #3 to expression by token ';' at line 92 in state XXX, call binop "=", goto XXX
Shift token ';' at line 92 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "printf" at line 93 in state XXX, call free_expression, goto XXX
Shift token IDENT = "printf" at line 93 in state XXX, goto XXX
Reduce #1 to expression by token '(' at line 93 in state XXX, call variable, goto XXX
Shift token '(' at line 93 in state XXX, goto XXX
Shift token DQSTRING = "RESULT[4] x = %d\n" at line 93 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 93 in state XXX, call string_constant, goto XXX
Shift token ',' at line 93 in state XXX, goto XXX
Shift token IDENT = "obj" at line 93 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 93 in state XXX, call variable, goto XXX
Shift token '.' at line 93 in state XXX, goto XXX
Shift token IDENT = "ofs_x" at line 93 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 93 in state XXX, call member, goto XXX
Shift token '(' at line 93 in state XXX, goto XXX
Shift token SINTEGER = "-11" at line 93 in state XXX, goto XXX
Reduce #1 to expression by token ')' at line 93 in state XXX, call constant "constexpr int", goto XXX
Reduce #1 to expressionlist by token ')' at line 93 in state XXX, goto XXX
Shift token ')' at line 93 in state XXX, goto XXX
Reduce #4 to expression by token ')' at line 93 in state XXX, call operator "()", goto XXX
Reduce #1 to expressionlist by token ')' at line 93 in state XXX, goto XXX
Reduce #3 to expressionlist by token ')' at line 93 in state XXX, goto XXX
Shift token ')' at line 93 in state XXX, goto XXX
Reduce #4 to expression by token ';' at line 93 in state XXX, call operator "()", goto XXX
Shift token ';' at line 93 in state XXX, goto XXX
Reduce #2 to statement by token IDENT = "printf" at line 94 in state XXX, call free_expression, goto XXX
Shift token IDENT = "printf" at line 94 in state XXX, goto XXX
Reduce #1 to expression by token '(' at line 94 in state XXX, call variable, goto XXX
Shift token '(' at line 94 in state XXX, goto XXX
Shift token DQSTRING = "RESULT[4] y = %d\n" at line 94 in state XXX, goto XXX
Reduce #1 to expression by token ',' at line 94 in state XXX, call string_constant, goto XXX
Shift token ',' at line 94 in state XXX, goto XXX
Shift token IDENT = "obj" at line 94 in state XXX, goto XXX
Reduce #1 to expression by token '.' at line 94 in state XXX, call variable, goto XXX
Shift token '.' at line 94 in state XXX, goto XXX
Shift token IDENT = "y" at line 94 in state XXX, goto XXX
Reduce #3 to expression by token '(' at line 94 in state XXX, call member, goto XXX
Shift token '(' at line 94 in state XXX, goto XXX
Shift token ')' at line 94 in state XXX, goto XXX
Reduce #3 to expression by token ')' at line 94 in state XXX, call operator "()", goto XXX
Reduce #1 to expressionlist by token ')' at line 94 in state XXX, goto XXX
Reduce #3 to expressionlist by token ')' at line 94 in state XXX, goto XXX
Shift token ')' at line 94 in state XXX, goto XXX
Reduce #4 to expression by token ';' at line 94 in state XXX, call operator "()", goto XXX
Shift token ';' at line 94 in state XXX, goto XXX
Reduce #2 to statement by token "return" at line 95 in state XXX, call free_expression, goto XXX
Shift token "return" at line 95 in state XXX, goto XXX
Shift token UINTEGER = "0" at line 95 in state XXX, goto XXX
Reduce #1 to expression by token ';' at line 95 in state XXX, call constant "constexpr uint", goto XXX
Shift token ';' at line 95 in state XXX, goto XXX
Reduce #3 to statement by token '}' at line 96 in state XXX, call return_value, goto XXX
Reduce #0 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #2 to statementlist by token '}' at line 96 in state XXX, goto XXX
Reduce #1 to codeblock by token '}' at line 96 in state XXX, call codeblock, goto XXX
Shift token '}' at line 96 in state XXX, goto XXX
Accept
Calling Lua function: program
Lua call result [1]
{
  arg = {
    {
      arg = {
        {
          line = 3,
          name = "DQSTRING",
          value = "C"},
        {
          line = 3,
          name = "IDENT",
          value = "printf"},
        {
          arg = {
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 3,
                              name = "IDENT",
                              value = "byte"}},
                          call = {
                            name = "typehdr {const=true}",
                            obj = {
                              const = true},
                            proc = <function>},
                          line = 3,
                          step = 0}},
                      call = {
                        name = "typegen_pointer {const=false}",
                        obj = {
                          const = false},
                        proc = <function>},
                      line = 3,
                      step = 0}},
                  call = {
                    name = "typespec",
                    proc = <function>},
                  line = 3,
                  step = 0},
                {
                  line = 3,
                  name = "IDENT",
                  value = "fmt"}},
              call = {
                name = "extern_paramdeftail",
                proc = <function>},
              line = 3,
              step = 0}},
          call = {
            name = "extern_paramdeflist",
            proc = <function>},
          line = 3,
          step = 0}},
      call = {
        name = "extern_procdef_vararg",
        proc = <function>},
      line = 3,
      step = 0},
    {
      arg = {
        {
          arg = {
            {
              line = 5,
              name = "IDENT",
              value = "Object"},
            {
              arg = {
                {
                  line = 7,
                  name = "IDENT",
                  value = "x"},
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 7,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typehdr {const=false}",
                        obj = {
                          const = false},
                        proc = <function>},
                      line = 7,
                      step = 0}},
                  call = {
                    name = "typespec",
                    proc = <function>},
                  line = 7,
                  step = 0},
                {
                  arg = {},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 7,
                  step = 0},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "funcattribute {const=false,throws=true}",
                            obj = {
                              const = false,
                              throws = true},
                            proc = <function>},
                          line = 7,
                          step = 0}},
                      call = {
                        name = "funcattribute {throws=false}",
                        obj = {
                          throws = false},
                        proc = <function>},
                      line = 7,
                      step = 0}},
                  call = {
                    name = "funcattribute {const=true}",
                    obj = {
                      const = true},
                    proc = <function>},
                  line = 7,
                  step = 0}},
              call = {
                name = "interface_funcdef",
                proc = <function>},
              line = 7,
              step = 0},
            {
              arg = {
                {
                  line = 8,
                  name = "IDENT",
                  value = "y"},
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 8,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typehdr {const=false}",
                        obj = {
                          const = false},
                        proc = <function>},
                      line = 8,
                      step = 0}},
                  call = {
                    name = "typespec",
                    proc = <function>},
                  line = 8,
                  step = 0},
                {
                  arg = {},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 8,
                  step = 0},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "funcattribute {const=false,throws=true}",
                            obj = {
                              const = false,
                              throws = true},
                            proc = <function>},
                          line = 8,
                          step = 0}},
                      call = {
                        name = "funcattribute {throws=false}",
                        obj = {
                          throws = false},
                        proc = <function>},
                      line = 8,
                      step = 0}},
                  call = {
                    name = "funcattribute {const=true}",
                    obj = {
                      const = true},
                    proc = <function>},
                  line = 8,
                  step = 0}},
              call = {
                name = "interface_funcdef",
                proc = <function>},
              line = 8,
              step = 0},
            {
              arg = {
                {
                  line = 9,
                  name = "IDENT",
                  value = "ofs_x"},
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 9,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typehdr {const=false}",
                        obj = {
                          const = false},
                        proc = <function>},
                      line = 9,
                      step = 0}},
                  call = {
                    name = "typespec",
                    proc = <function>},
                  line = 9,
                  step = 0},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 9,
                                  name = "IDENT",
                                  value = "int"}},
                              call = {
                                name = "typehdr {const=false}",
                                obj = {
                                  const = false},
                                proc = <function>},
                              line = 9,
                              step = 0}},
                          call = {
                            name = "typespec",
                            proc = <function>},
                          line = 9,
                          step = 0},
                        {
                          line = 9,
                          name = "IDENT",
                          value = "addx"}},
                      call = {
                        name = "extern_paramdeftail",
                        proc = <function>},
                      line = 9,
                      step = 0}},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 9,
                  step = 0},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "funcattribute {const=false,throws=true}",
                            obj = {
                              const = false,
                              throws = true},
                            proc = <function>},
                          line = 9,
                          step = 0}},
                      call = {
                        name = "funcattribute {throws=false}",
                        obj = {
                          throws = false},
                        proc = <function>},
                      line = 9,
                      step = 0}},
                  call = {
                    name = "funcattribute {const=true}",
                    obj = {
                      const = true},
                    proc = <function>},
                  line = 9,
                  step = 0}},
              call = {
                name = "interface_funcdef",
                proc = <function>},
              line = 9,
              step = 0},
            {
              arg = {
                {
                  line = 10,
                  name = "IDENT",
                  value = "ofs_y"},
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 10,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typehdr {const=false}",
                        obj = {
                          const = false},
                        proc = <function>},
                      line = 10,
                      step = 0}},
                  call = {
                    name = "typespec",
                    proc = <function>},
                  line = 10,
                  step = 0},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 10,
                                  name = "IDENT",
                                  value = "int"}},
                              call = {
                                name = "typehdr {const=false}",
                                obj = {
                                  const = false},
                                proc = <function>},
                              line = 10,
                              step = 0}},
                          call = {
                            name = "typespec",
                            proc = <function>},
                          line = 10,
                          step = 0},
                        {
                          line = 10,
                          name = "IDENT",
                          value = "addy"}},
                      call = {
                        name = "extern_paramdeftail",
                        proc = <function>},
                      line = 10,
                      step = 0}},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 10,
                  step = 0},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "funcattribute {const=false,throws=true}",
                            obj = {
                              const = false,
                              throws = true},
                            proc = <function>},
                          line = 10,
                          step = 0}},
                      call = {
                        name = "funcattribute {throws=false}",
                        obj = {
                          throws = false},
                        proc = <function>},
                      line = 10,
                      step = 0}},
                  call = {
                    name = "funcattribute {const=true}",
                    obj = {
                      const = true},
                    proc = <function>},
                  line = 10,
                  step = 0}},
              call = {
                name = "interface_funcdef",
                proc = <function>},
              line = 10,
              step = 0}},
          call = {
            name = "interfacedef",
            proc = <function>},
          line = 10,
          step = 1}},
      call = {
        name = "definition 1",
        obj = 1,
        proc = <function>},
      line = 10,
      step = 1},
    {
      arg = {
        {
          arg = {
            {
              line = 13,
              name = "IDENT",
              value = "ObjectUpdater"},
            {
              arg = {
                {
                  arg = {},
                  call = {
                    name = "operatordecl {name="=",symbol="assign"}",
                    obj = {
                      name = "=",
                      symbol = "assign"},
                    proc = <function>},
                  line = 13,
                  step = 1},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 15,
                                  name = "IDENT",
                                  value = "int"}},
                              call = {
                                name = "typehdr {const=false}",
                                obj = {
                                  const = false},
                                proc = <function>},
                              line = 15,
                              step = 1}},
                          call = {
                            name = "typespec",
                            proc = <function>},
                          line = 15,
                          step = 1},
                        {
                          line = 15,
                          name = "IDENT",
                          value = "x_"},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 15,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typehdr {const=false}",
                                    obj = {
                                      const = false},
                                    proc = <function>},
                                  line = 15,
                                  step = 1}},
                              call = {
                                name = "typespec",
                                proc = <function>},
                              line = 15,
                              step = 1},
                            {
                              line = 15,
                              name = "IDENT",
                              value = "y_"}},
                          call = {
                            name = "extern_paramdeftail",
                            proc = <function>},
                          line = 15,
                          step = 1}},
                      call = {
                        name = "extern_paramdef",
                        proc = <function>},
                      line = 15,
                      step = 1}},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 15,
                  step = 1},
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "funcattribute {const=false,throws=true}",
                        obj = {
                          const = false,
                          throws = true},
                        proc = <function>},
                      line = 15,
                      step = 1}},
                  call = {
                    name = "funcattribute {throws=false}",
                    obj = {
                      throws = false},
                    proc = <function>},
                  line = 15,
                  step = 1}},
              call = {
                name = "interface_operator_procdef",
                proc = <function>},
              line = 15,
              step = 1}},
          call = {
            name = "interfacedef",
            proc = <function>},
          line = 15,
          step = 2}},
      call = {
        name = "definition 1",
        obj = 1,
        proc = <function>},
      line = 15,
      step = 2},
    {
      arg = {
        {
          arg = {
            {
              line = 18,
              name = "IDENT",
              value = "Point"},
            {
              arg = {
                {
                  arg = {
                    {
                      line = 18,
                      name = "IDENT",
                      value = "Object"}},
                  call = {
                    name = "typehdr {const=false}",
                    obj = {
                      const = false},
                    proc = <function>},
                  line = 18,
                  step = 2},
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 18,
                          name = "IDENT",
                          value = "ObjectUpdater"}},
                      call = {
                        name = "typehdr {const=false}",
                        obj = {
                          const = false},
                        proc = <function>},
                      line = 18,
                      step = 2}},
                  call = {
                    name = "inheritdef 1",
                    obj = 1,
                    proc = <function>},
                  line = 18,
                  step = 3}},
              call = {
                name = "inheritdef 1",
                obj = 1,
                proc = <function>},
              line = 18,
              step = 4},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=true}",
                        obj = {
                          explicit = true,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 18,
                      step = 4},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 20,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 20,
                                      step = 4}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 20,
                                  step = 4},
                                {
                                  line = 20,
                                  name = "IDENT",
                                  value = "x_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 20,
                              step = 4},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 20,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 20,
                                      step = 4}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 20,
                                  step = 4},
                                {
                                  line = 20,
                                  name = "IDENT",
                                  value = "y_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 20,
                              step = 4}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 20,
                          step = 4},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 22,
                                          name = "IDENT",
                                          value = "m_x"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 22,
                                      step = 4},
                                    {
                                      arg = {
                                        {
                                          line = 22,
                                          name = "IDENT",
                                          value = "x_"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 22,
                                      step = 4}},
                                  call = {
                                    name = "binop =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 22,
                                  step = 4}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 22,
                              step = 4},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 23,
                                              name = "IDENT",
                                              value = "self"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 23,
                                          step = 4},
                                        {
                                          line = 23,
                                          name = "IDENT",
                                          value = "m_y"}},
                                      call = {
                                        name = "member",
                                        proc = <function>},
                                      line = 23,
                                      step = 4},
                                    {
                                      arg = {
                                        {
                                          line = 23,
                                          name = "IDENT",
                                          value = "y_"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 23,
                                      step = 4}},
                                  call = {
                                    name = "binop =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 23,
                                  step = 4}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 23,
                              step = 4}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 23,
                          step = 4}},
                      call = {
                        name = "callablebody {throws=false,const=false}",
                        obj = {
                          const = false,
                          throws = false},
                        proc = <function>},
                      line = 23,
                      scope = {
                        4,
                        5}}},
                  call = {
                    name = "constructordef",
                    proc = <function>},
                  id = 1,
                  line = 23,
                  step = 5}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 23,
              step = 5},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=true}",
                        obj = {
                          explicit = true,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 23,
                      step = 5},
                    {
                      arg = {},
                      call = {
                        name = "operatordecl {name="=",symbol="assign"}",
                        obj = {
                          name = "=",
                          symbol = "assign"},
                        proc = <function>},
                      line = 23,
                      step = 5},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 26,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 26,
                                      step = 5}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 26,
                                  step = 5},
                                {
                                  line = 26,
                                  name = "IDENT",
                                  value = "x_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 26,
                              step = 5},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 26,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 26,
                                      step = 5}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 26,
                                  step = 5},
                                {
                                  line = 26,
                                  name = "IDENT",
                                  value = "y_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 26,
                              step = 5}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 26,
                          step = 5},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 28,
                                              name = "IDENT",
                                              value = "self"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 28,
                                          step = 5},
                                        {
                                          line = 28,
                                          name = "IDENT",
                                          value = "m_x"}},
                                      call = {
                                        name = "member",
                                        proc = <function>},
                                      line = 28,
                                      step = 5},
                                    {
                                      arg = {
                                        {
                                          line = 28,
                                          name = "IDENT",
                                          value = "x_"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 28,
                                      step = 5}},
                                  call = {
                                    name = "binop =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 28,
                                  step = 5}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 28,
                              step = 5},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 29,
                                          name = "IDENT",
                                          value = "m_y"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 29,
                                      step = 5},
                                    {
                                      arg = {
                                        {
                                          line = 29,
                                          name = "IDENT",
                                          value = "y_"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 29,
                                      step = 5}},
                                  call = {
                                    name = "binop =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 29,
                                  step = 5}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 29,
                              step = 5}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 29,
                          step = 5}},
                      call = {
                        name = "callablebody {throws=false,const=false}",
                        obj = {
                          const = false,
                          throws = false},
                        proc = <function>},
                      line = 29,
                      scope = {
                        5,
                        6}}},
                  call = {
                    name = "operator_procdef",
                    proc = <function>},
                  id = 2,
                  line = 29,
                  step = 6}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 29,
              step = 6},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=true}",
                        obj = {
                          explicit = true,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 29,
                      step = 6},
                    {
                      line = 32,
                      name = "IDENT",
                      value = "x"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 32,
                              name = "IDENT",
                              value = "int"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 32,
                          step = 6}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 32,
                      step = 6},
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 32,
                          step = 6},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 34,
                                      name = "IDENT",
                                      value = "m_x"}},
                                  call = {
                                    name = "variable",
                                    proc = <function>},
                                  line = 34,
                                  step = 6}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 34,
                              step = 7}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 34,
                          step = 7}},
                      call = {
                        name = "callablebody {throws=false,const=true}",
                        obj = {
                          const = true,
                          throws = false},
                        proc = <function>},
                      line = 34,
                      scope = {
                        6,
                        8}}},
                  call = {
                    name = "funcdef",
                    proc = <function>},
                  id = 3,
                  line = 34,
                  step = 8}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 34,
              step = 8},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=true}",
                        obj = {
                          explicit = true,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 34,
                      step = 8},
                    {
                      line = 37,
                      name = "IDENT",
                      value = "y"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 37,
                              name = "IDENT",
                              value = "int"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 37,
                          step = 8}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 37,
                      step = 8},
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 37,
                          step = 8},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 39,
                                          name = "IDENT",
                                          value = "self"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 39,
                                      step = 8},
                                    {
                                      line = 39,
                                      name = "IDENT",
                                      value = "m_y"}},
                                  call = {
                                    name = "member",
                                    proc = <function>},
                                  line = 39,
                                  step = 8}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 39,
                              step = 9}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 39,
                          step = 9}},
                      call = {
                        name = "callablebody {throws=false,const=true}",
                        obj = {
                          const = true,
                          throws = false},
                        proc = <function>},
                      line = 39,
                      scope = {
                        8,
                        10}}},
                  call = {
                    name = "funcdef",
                    proc = <function>},
                  id = 4,
                  line = 39,
                  step = 10}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 39,
              step = 10},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=false}",
                        obj = {
                          explicit = false,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 39,
                      step = 10},
                    {
                      line = 42,
                      name = "IDENT",
                      value = "ofs_x"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 42,
                              name = "IDENT",
                              value = "int"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 42,
                          step = 10}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 42,
                      step = 10},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 42,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 42,
                                      step = 10}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 42,
                                  step = 10},
                                {
                                  line = 42,
                                  name = "IDENT",
                                  value = "addx"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 42,
                              step = 10}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 42,
                          step = 10},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 44,
                                          name = "IDENT",
                                          value = "m_x"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 44,
                                      step = 10},
                                    {
                                      arg = {
                                        {
                                          line = 44,
                                          name = "IDENT",
                                          value = "addx"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 44,
                                      step = 10}},
                                  call = {
                                    name = "binop +",
                                    obj = "+",
                                    proc = <function>},
                                  line = 44,
                                  step = 10}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 44,
                              step = 11}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 44,
                          step = 11}},
                      call = {
                        name = "callablebody {throws=false,const=true}",
                        obj = {
                          const = true,
                          throws = false},
                        proc = <function>},
                      line = 44,
                      scope = {
                        10,
                        12}}},
                  call = {
                    name = "funcdef",
                    proc = <function>},
                  id = 5,
                  line = 44,
                  step = 12}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 44,
              step = 12},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=false}",
                        obj = {
                          explicit = false,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 44,
                      step = 12},
                    {
                      line = 47,
                      name = "IDENT",
                      value = "ofs_y"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 47,
                              name = "IDENT",
                              value = "int"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 47,
                          step = 12}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 47,
                      step = 12},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 47,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 47,
                                      step = 12}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 47,
                                  step = 12},
                                {
                                  line = 47,
                                  name = "IDENT",
                                  value = "addy"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 47,
                              step = 12}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 47,
                          step = 12},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 49,
                                          name = "IDENT",
                                          value = "m_y"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 49,
                                      step = 12},
                                    {
                                      arg = {
                                        {
                                          line = 49,
                                          name = "IDENT",
                                          value = "addy"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 49,
                                      step = 12}},
                                  call = {
                                    name = "binop +",
                                    obj = "+",
                                    proc = <function>},
                                  line = 49,
                                  step = 12}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 49,
                              step = 13}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 49,
                          step = 13}},
                      call = {
                        name = "callablebody {throws=false,const=true}",
                        obj = {
                          const = true,
                          throws = false},
                        proc = <function>},
                      line = 49,
                      scope = {
                        12,
                        14}}},
                  call = {
                    name = "funcdef",
                    proc = <function>},
                  id = 6,
                  line = 49,
                  step = 14}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 49,
              step = 14},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=true}",
                        obj = {
                          explicit = true,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 49,
                      step = 14},
                    {
                      line = 52,
                      name = "IDENT",
                      value = "object"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 52,
                              name = "IDENT",
                              value = "Object"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 52,
                          step = 14}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 52,
                      step = 14},
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 52,
                          step = 14},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 54,
                                          name = "IDENT",
                                          value = "self"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 54,
                                      step = 14},
                                    {
                                      line = 54,
                                      name = "IDENT",
                                      value = "Object"}},
                                  call = {
                                    name = "member",
                                    proc = <function>},
                                  line = 54,
                                  step = 14}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 54,
                              step = 15}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 54,
                          step = 15}},
                      call = {
                        name = "callablebody {throws=false,const=true}",
                        obj = {
                          const = true,
                          throws = false},
                        proc = <function>},
                      line = 54,
                      scope = {
                        14,
                        16}}},
                  call = {
                    name = "funcdef",
                    proc = <function>},
                  id = 7,
                  line = 54,
                  step = 16}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 54,
              step = 16},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=true}",
                        obj = {
                          explicit = true,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 54,
                      step = 16},
                    {
                      line = 56,
                      name = "IDENT",
                      value = "updater"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 56,
                              name = "IDENT",
                              value = "ObjectUpdater"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 56,
                          step = 16}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 56,
                      step = 16},
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 56,
                          step = 16},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 58,
                                          name = "IDENT",
                                          value = "self"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 58,
                                      step = 16},
                                    {
                                      line = 58,
                                      name = "IDENT",
                                      value = "ObjectUpdater"}},
                                  call = {
                                    name = "member",
                                    proc = <function>},
                                  line = 58,
                                  step = 16}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 58,
                              step = 17}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 58,
                          step = 17}},
                      call = {
                        name = "callablebody {throws=false,const=false}",
                        obj = {
                          const = false,
                          throws = false},
                        proc = <function>},
                      line = 58,
                      scope = {
                        16,
                        18}}},
                  call = {
                    name = "funcdef",
                    proc = <function>},
                  id = 8,
                  line = 58,
                  step = 18}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 58,
              step = 18},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 61,
                              name = "IDENT",
                              value = "int"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 61,
                          step = 18}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 61,
                      step = 18},
                    {
                      line = 61,
                      name = "IDENT",
                      value = "m_x"}},
                  call = {
                    name = "vardef",
                    proc = <function>},
                  line = 61,
                  step = 19}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 61,
              step = 19},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 62,
                              name = "IDENT",
                              value = "int"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 62,
                          step = 19}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 62,
                      step = 19},
                    {
                      line = 62,
                      name = "IDENT",
                      value = "m_y"}},
                  call = {
                    name = "vardef",
                    proc = <function>},
                  line = 62,
                  step = 20}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 62,
              step = 20}},
          call = {
            name = "classdef",
            proc = <function>},
          line = 62,
          step = 21}},
      call = {
        name = "definition 1",
        obj = 1,
        proc = <function>},
      line = 62,
      step = 21},
    {
      arg = {
        {
          arg = {
            {
              line = 65,
              name = "IDENT",
              value = "Line"},
            {
              arg = {
                {
                  arg = {
                    {
                      line = 65,
                      name = "IDENT",
                      value = "Point"}},
                  call = {
                    name = "typehdr {const=false}",
                    obj = {
                      const = false},
                    proc = <function>},
                  line = 65,
                  step = 21}},
              call = {
                name = "inheritdef 1",
                obj = 1,
                proc = <function>},
              line = 65,
              step = 22},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=true}",
                        obj = {
                          explicit = true,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 65,
                      step = 22},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 67,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 67,
                                      step = 22}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 67,
                                  step = 22},
                                {
                                  line = 67,
                                  name = "IDENT",
                                  value = "x_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 67,
                              step = 22},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 67,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 67,
                                      step = 22}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 67,
                                  step = 22},
                                {
                                  line = 67,
                                  name = "IDENT",
                                  value = "y_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 67,
                              step = 22}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 67,
                          step = 22},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 69,
                                              name = "IDENT",
                                              value = "self"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 69,
                                          step = 22},
                                        {
                                          line = 69,
                                          name = "IDENT",
                                          value = "Point"}},
                                      call = {
                                        name = "member",
                                        proc = <function>},
                                      line = 69,
                                      step = 22},
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 69,
                                              name = "IDENT",
                                              value = "x_"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 69,
                                          step = 22},
                                        {
                                          arg = {
                                            {
                                              line = 69,
                                              name = "IDENT",
                                              value = "y_"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 69,
                                          step = 22}},
                                      call = {
                                        name = "structure",
                                        proc = <function>},
                                      line = 69,
                                      step = 22}},
                                  call = {
                                    name = "binop =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 69,
                                  step = 22}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 69,
                              step = 22}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 69,
                          step = 22}},
                      call = {
                        name = "callablebody {throws=false,const=false}",
                        obj = {
                          const = false,
                          throws = false},
                        proc = <function>},
                      line = 69,
                      scope = {
                        22,
                        23}}},
                  call = {
                    name = "constructordef",
                    proc = <function>},
                  id = 9,
                  line = 69,
                  step = 23}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 69,
              step = 23},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external",explicit=true}",
                        obj = {
                          explicit = true,
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 69,
                      step = 23},
                    {
                      line = 72,
                      name = "IDENT",
                      value = "move"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 72,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 72,
                                      step = 23}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 72,
                                  step = 23},
                                {
                                  line = 72,
                                  name = "IDENT",
                                  value = "x_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 72,
                              step = 23},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 72,
                                          name = "IDENT",
                                          value = "int"}},
                                      call = {
                                        name = "typehdr {const=false}",
                                        obj = {
                                          const = false},
                                        proc = <function>},
                                      line = 72,
                                      step = 23}},
                                  call = {
                                    name = "typespec",
                                    proc = <function>},
                                  line = 72,
                                  step = 23},
                                {
                                  line = 72,
                                  name = "IDENT",
                                  value = "y_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 72,
                              step = 23}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 72,
                          step = 23},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 74,
                                              name = "IDENT",
                                              value = "self"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 74,
                                          step = 23},
                                        {
                                          line = 74,
                                          name = "IDENT",
                                          value = "Point"}},
                                      call = {
                                        name = "member",
                                        proc = <function>},
                                      line = 74,
                                      step = 23},
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 74,
                                              name = "IDENT",
                                              value = "x_"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 74,
                                          step = 23},
                                        {
                                          arg = {
                                            {
                                              line = 74,
                                              name = "IDENT",
                                              value = "y_"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 74,
                                          step = 23}},
                                      call = {
                                        name = "structure",
                                        proc = <function>},
                                      line = 74,
                                      step = 23}},
                                  call = {
                                    name = "binop =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 74,
                                  step = 23}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 74,
                              step = 23}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 74,
                          step = 23}},
                      call = {
                        name = "callablebody {throws=false,const=false}",
                        obj = {
                          const = false,
                          throws = false},
                        proc = <function>},
                      line = 74,
                      scope = {
                        23,
                        24}}},
                  call = {
                    name = "procdef",
                    proc = <function>},
                  id = 10,
                  line = 74,
                  step = 24}},
              call = {
                name = "definition_decl_impl_pass 4",
                obj = 4,
                proc = <function>},
              line = 74,
              step = 24}},
          call = {
            name = "classdef",
            proc = <function>},
          line = 74,
          step = 25}},
      call = {
        name = "definition 1",
        obj = 1,
        proc = <function>},
      line = 74,
      step = 25},
    {
      arg = {
        {
          arg = {
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 79,
                              name = "IDENT",
                              value = "float"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 79,
                          step = 25}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 79,
                      step = 25},
                    {
                      line = 79,
                      name = "IDENT",
                      value = "x"},
                    {
                      arg = {
                        {
                          line = 79,
                          name = "FLOAT",
                          value = "1.23"}},
                      call = {
                        name = "constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 79,
                      step = 25}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 79,
                  step = 26}},
              call = {
                name = "definition 1",
                obj = 1,
                proc = <function>},
              line = 79,
              step = 26},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 80,
                              name = "IDENT",
                              value = "Line"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 80,
                          step = 26}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 80,
                      step = 26},
                    {
                      line = 80,
                      name = "IDENT",
                      value = "ab"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 80,
                              name = "FLOAT",
                              value = "7.23"}},
                          call = {
                            name = "constant constexpr float",
                            obj = "constexpr float",
                            proc = <function>},
                          line = 80,
                          step = 26},
                        {
                          arg = {
                            {
                              line = 80,
                              name = "FLOAT",
                              value = "4.23"}},
                          call = {
                            name = "constant constexpr float",
                            obj = "constexpr float",
                            proc = <function>},
                          line = 80,
                          step = 26}},
                      call = {
                        name = "structure",
                        proc = <function>},
                      line = 80,
                      step = 26}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 80,
                  step = 27}},
              call = {
                name = "definition 1",
                obj = 1,
                proc = <function>},
              line = 80,
              step = 27},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 81,
                              name = "IDENT",
                              value = "Object"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 81,
                          step = 27}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 81,
                      step = 27},
                    {
                      line = 81,
                      name = "IDENT",
                      value = "obj"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 81,
                                  name = "IDENT",
                                  value = "ab"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 81,
                              step = 27},
                            {
                              line = 81,
                              name = "IDENT",
                              value = "object"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 81,
                          step = 27}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 81,
                      step = 27}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 81,
                  step = 28}},
              call = {
                name = "definition 1",
                obj = 1,
                proc = <function>},
              line = 81,
              step = 28},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 82,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 82,
                      step = 28},
                    {
                      arg = {
                        {
                          line = 82,
                          name = "DQSTRING",
                          value = "RESULT[1] x = %d\\n"}},
                      call = {
                        name = "string_constant",
                        proc = <function>},
                      line = 82,
                      step = 28},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 82,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 82,
                              step = 28},
                            {
                              line = 82,
                              name = "IDENT",
                              value = "x"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 82,
                          step = 28}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 82,
                      step = 28}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 82,
                  step = 28}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 82,
              step = 28},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 83,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 83,
                      step = 28},
                    {
                      arg = {
                        {
                          line = 83,
                          name = "DQSTRING",
                          value = "RESULT[1] y = %d\\n"}},
                      call = {
                        name = "string_constant",
                        proc = <function>},
                      line = 83,
                      step = 28},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 83,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 83,
                              step = 28},
                            {
                              line = 83,
                              name = "IDENT",
                              value = "y"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 83,
                          step = 28}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 83,
                      step = 28}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 83,
                  step = 28}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 83,
              step = 28},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 84,
                              name = "IDENT",
                              value = "ObjectUpdater"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 84,
                          step = 28}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 84,
                      step = 28},
                    {
                      line = 84,
                      name = "IDENT",
                      value = "updater"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 84,
                                  name = "IDENT",
                                  value = "ab"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 84,
                              step = 28},
                            {
                              line = 84,
                              name = "IDENT",
                              value = "updater"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 84,
                          step = 28}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 84,
                      step = 28}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 84,
                  step = 29}},
              call = {
                name = "definition 1",
                obj = 1,
                proc = <function>},
              line = 84,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 85,
                          name = "IDENT",
                          value = "updater"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 85,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 85,
                              name = "UINTEGER",
                              value = "31"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 85,
                          step = 29},
                        {
                          arg = {
                            {
                              line = 85,
                              name = "UINTEGER",
                              value = "411"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 85,
                          step = 29}},
                      call = {
                        name = "structure",
                        proc = <function>},
                      line = 85,
                      step = 29}},
                  call = {
                    name = "binop =",
                    obj = "=",
                    proc = <function>},
                  line = 85,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 85,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 86,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 86,
                      step = 29},
                    {
                      arg = {
                        {
                          line = 86,
                          name = "DQSTRING",
                          value = "RESULT[2] x = %d\\n"}},
                      call = {
                        name = "string_constant",
                        proc = <function>},
                      line = 86,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 86,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 86,
                              step = 29},
                            {
                              line = 86,
                              name = "IDENT",
                              value = "x"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 86,
                          step = 29}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 86,
                      step = 29}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 86,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 86,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 87,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 87,
                      step = 29},
                    {
                      arg = {
                        {
                          line = 87,
                          name = "DQSTRING",
                          value = "RESULT[2] y = %d\\n"}},
                      call = {
                        name = "string_constant",
                        proc = <function>},
                      line = 87,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 87,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 87,
                              step = 29},
                            {
                              line = 87,
                              name = "IDENT",
                              value = "y"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 87,
                          step = 29}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 87,
                      step = 29}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 87,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 87,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 88,
                          name = "IDENT",
                          value = "updater"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 88,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 88,
                              name = "UINTEGER",
                              value = "71"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 88,
                          step = 29},
                        {
                          arg = {
                            {
                              line = 88,
                              name = "UINTEGER",
                              value = "511"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 88,
                          step = 29}},
                      call = {
                        name = "structure",
                        proc = <function>},
                      line = 88,
                      step = 29}},
                  call = {
                    name = "binop =",
                    obj = "=",
                    proc = <function>},
                  line = 88,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 88,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 89,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 89,
                      step = 29},
                    {
                      arg = {
                        {
                          line = 89,
                          name = "DQSTRING",
                          value = "RESULT[3] x = %d\\n"}},
                      call = {
                        name = "string_constant",
                        proc = <function>},
                      line = 89,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 89,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 89,
                              step = 29},
                            {
                              line = 89,
                              name = "IDENT",
                              value = "ofs_x"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 89,
                          step = 29},
                        {
                          arg = {
                            {
                              line = 89,
                              name = "SINTEGER",
                              value = "-13"}},
                          call = {
                            name = "constant constexpr int",
                            obj = "constexpr int",
                            proc = <function>},
                          line = 89,
                          step = 29}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 89,
                      step = 29}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 89,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 89,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 90,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 90,
                      step = 29},
                    {
                      arg = {
                        {
                          line = 90,
                          name = "DQSTRING",
                          value = "RESULT[3] y = %d\\n"}},
                      call = {
                        name = "string_constant",
                        proc = <function>},
                      line = 90,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 90,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 90,
                              step = 29},
                            {
                              line = 90,
                              name = "IDENT",
                              value = "ofs_y"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 90,
                          step = 29},
                        {
                          arg = {
                            {
                              line = 90,
                              name = "UINTEGER",
                              value = "1"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 90,
                          step = 29}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 90,
                      step = 29}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 90,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 90,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 91,
                              name = "IDENT",
                              value = "ObjectUpdater"}},
                          call = {
                            name = "typehdr {const=false}",
                            obj = {
                              const = false},
                            proc = <function>},
                          line = 91,
                          step = 29}},
                      call = {
                        name = "typespec",
                        proc = <function>},
                      line = 91,
                      step = 29},
                    {
                      line = 91,
                      name = "IDENT",
                      value = "updater2"},
                    {
                      arg = {
                        {
                          line = 91,
                          name = "IDENT",
                          value = "updater"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 91,
                      step = 29}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 91,
                  step = 30}},
              call = {
                name = "definition 1",
                obj = 1,
                proc = <function>},
              line = 91,
              step = 30},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 92,
                          name = "IDENT",
                          value = "updater2"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 92,
                      step = 30},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 92,
                              name = "UINTEGER",
                              value = "32"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 92,
                          step = 30},
                        {
                          arg = {
                            {
                              line = 92,
                              name = "UINTEGER",
                              value = "412"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 92,
                          step = 30}},
                      call = {
                        name = "structure",
                        proc = <function>},
                      line = 92,
                      step = 30}},
                  call = {
                    name = "binop =",
                    obj = "=",
                    proc = <function>},
                  line = 92,
                  step = 30}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 92,
              step = 30},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 93,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 93,
                      step = 30},
                    {
                      arg = {
                        {
                          line = 93,
                          name = "DQSTRING",
                          value = "RESULT[4] x = %d\\n"}},
                      call = {
                        name = "string_constant",
                        proc = <function>},
                      line = 93,
                      step = 30},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 93,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 93,
                              step = 30},
                            {
                              line = 93,
                              name = "IDENT",
                              value = "ofs_x"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 93,
                          step = 30},
                        {
                          arg = {
                            {
                              line = 93,
                              name = "SINTEGER",
                              value = "-11"}},
                          call = {
                            name = "constant constexpr int",
                            obj = "constexpr int",
                            proc = <function>},
                          line = 93,
                          step = 30}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 93,
                      step = 30}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 93,
                  step = 30}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 93,
              step = 30},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 94,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 94,
                      step = 30},
                    {
                      arg = {
                        {
                          line = 94,
                          name = "DQSTRING",
                          value = "RESULT[4] y = %d\\n"}},
                      call = {
                        name = "string_constant",
                        proc = <function>},
                      line = 94,
                      step = 30},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 94,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 94,
                              step = 30},
                            {
                              line = 94,
                              name = "IDENT",
                              value = "y"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 94,
                          step = 30}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 94,
                      step = 30}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 94,
                  step = 30}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 94,
              step = 30},
            {
              arg = {
                {
                  arg = {
                    {
                      line = 95,
                      name = "UINTEGER",
                      value = "0"}},
                  call = {
                    name = "constant constexpr uint",
                    obj = "constexpr uint",
                    proc = <function>},
                  line = 95,
                  step = 30}},
              call = {
                name = "return_value",
                proc = <function>},
              line = 95,
              step = 31}},
          call = {
            name = "codeblock",
            proc = <function>},
          line = 95,
          step = 31}},
      call = {
        name = "main_procdef",
        proc = <function>},
      line = 95,
      scope = {
        25,
        32}}},
  call = {
    name = "program",
    proc = <function>},
  line = 95,
  step = 32}
