
@llvm.global_ctors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__ctors, i8* null }]
@llvm.global_dtors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__dtors, i8* null }]

declare external i32 @__gxx_personality_v0( ... ) nounwind
declare external void @putchar( i8 ) nounwind
declare external i8* @malloc( i64 ) nounwind
declare external void @free( i8* ) nounwind
declare external i8* @memcpy( i8*, i8*, i64 ) nounwind
declare external i64 @strlen( i8* ) nounwind
%std__String = type { i8*, i32 }
declare external i8* @strdup( i8* ) nounwind
%__L_Exception = type { i64, i8* }
@__L_ExceptionSize = constant i32 ptrtoint(%__L_Exception* getelementptr(%__L_Exception, %__L_Exception* null, i32 1) to i32)
declare external i8* @__cxa_allocate_exception( i32)
declare external void @__cxa_throw( i8*, i8*, i8*) noreturn
declare external i8* @__cxa_begin_catch( i8*)
declare external void @__cxa_end_catch()
define dso_local void @__L_init__Exception( %__L_Exception* %exception, i64 %code, i8* %msg) {
%ObjCodeRef = getelementptr inbounds %__L_Exception, %__L_Exception* %exception, i32 0, i32 0
store i64 %code, i64* %ObjCodeRef
%ObjMsgRef = getelementptr inbounds %__L_Exception, %__L_Exception* %exception, i32 0, i32 1
%IsNull = icmp ne i8* %msg, null
br i1 %IsNull, label %L_COPY, label %L_NULL
L_COPY:
%MsgCopy = call i8* @strdup( i8* %msg) nounwind
store i8* %MsgCopy, i8** %ObjMsgRef
br label %L_CONT
L_NULL:
store i8* null, i8** %ObjMsgRef
br label %L_CONT
L_CONT:
ret void
}
define dso_local void @__L_throw__Exception( %__L_Exception* %exception) {
%SizeObObj = load i32, i32* @__L_ExceptionSize
%Mem = call i8* @__cxa_allocate_exception( i32 %SizeObObj) nounwind
%Obj = bitcast i8* %Mem to %__L_Exception*
%exceptionVal = load %__L_Exception, %__L_Exception* %exception
store %__L_Exception %exceptionVal, %__L_Exception* %Obj
call void @__cxa_throw( i8* %Mem, i8* null, i8* null) noreturn
unreachable
}
define dso_local void @__L_free__ExceptionMsg( i8* %msg) {
%IsNull = icmp ne i8* %msg, null
br i1 %IsNull, label %L_FREE, label %L_DONE
L_FREE:
call void @free( i8* %msg) nounwind
br label %L_DONE
L_DONE:
ret void
}
define private dso_local void @__partial_dtor_std__String( %std__String* %ths, i32 %istate) {
enter:
br label %end
end:
ret void
}
define private dso_local void @__ctor_init_4__std__String( [4 x %std__String]* %ar, i32 %start)#0 nounwind {
enter:
%ths_base = getelementptr inbounds [4 x %std__String], [4 x %std__String]* %ar, i32 0, i32 %start
%ths_top = getelementptr inbounds [4 x %std__String], [4 x %std__String]* %ar, i32 0, i32 4
br label %loop
loop:
%ths = phi %std__String* [%ths_base, %enter], [%A2, %cond]
call void @__C_std__String__$ctor( %std__String* %ths)
br label %cond
cond:
%A2 = getelementptr inbounds %std__String, %std__String* %ths, i64 1
%A3 = icmp eq %std__String* %A2, %ths_top
br i1 %A3, label %end, label %loop
end:
ret void
}
define private dso_local void @__dtor_4__std__String( [4 x %std__String]* %ar, i32 %arsize) alwaysinline {
enter:
%X1 = icmp eq i32 %arsize, 0
br i1 %X1, label %end, label %start
start:
%artop = sub nsw i32 %arsize, 1
%base = getelementptr inbounds [4 x %std__String], [4 x %std__String]* %ar, i32 0, i32 0
%top = getelementptr inbounds [4 x %std__String], [4 x %std__String]* %ar, i32 0, i32 %artop
br label %loop
loop:
%ths = phi %std__String* [%top, %start], [%A2, %loop]
%A2 = getelementptr inbounds %std__String, %std__String* %ths, i64 -1
call void @__dtor_std__String( %std__String* %ths)
%A3 = icmp eq %std__String* %ths, %base
br i1 %A3, label %end, label %loop
end:
ret void
}


define internal void @_GLOBAL__ctors() nounwind uwtable readnone optsize ssp section ".text.startup" {
  ret void
}

define internal void @_GLOBAL__dtors() nounwind uwtable readnone optsize ssp section ".text.startup" {
  ret void
}

declare external void @printf( i8*, ... ) nounwind
@g_allocCnt = internal global i32 0, align 4
@g_maxAllocCnt = internal global i32 0, align 4
@string1 = private unnamed_addr constant [11 x i8] c"Throw: %s\0A\00"
@string2 = private unnamed_addr constant [32 x i8] c"Max allowed allocations reached\00"
@string3 = private unnamed_addr constant [14 x i8] c"Out of memory\00"
define internal i8* @allocmem__i64( i64 %r1 ) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
entry:
%exception = alloca %__L_Exception
%r2 = load i32, i32* @g_allocCnt
%r3 = add nsw i32 %r2, 1
store i32 %r3, i32* @g_allocCnt
%r4 = load i32, i32* @g_allocCnt
%r5 = load i32, i32* @g_maxAllocCnt
%r6 = icmp eq i32 %r4, %r5
br i1 %r6, label %L4, label %L3
L4:
%r7 = getelementptr inbounds [11 x i8], [11 x i8]* @string1, i64 0, i64 0
%r8 = getelementptr inbounds [32 x i8], [32 x i8]* @string2, i64 0, i64 0
call void(i8*,  ...) @printf( i8* %r7, i8* %r8)
%r9 = getelementptr inbounds [32 x i8], [32 x i8]* @string2, i64 0, i64 0
call void @__L_init__Exception( %__L_Exception* %exception, i64 201, i8* %r9)
br label %L2
L3:
%r11 = alloca i8*
%r10 = call i8* @malloc( i64 %r1)
store i8* %r10, i8** %r11
%r12 = load i8*, i8** %r11
%r13 = icmp eq i8* %r12, null
br i1 %r13, label %L7, label %L6
L7:
%r14 = getelementptr inbounds [11 x i8], [11 x i8]* @string1, i64 0, i64 0
%r15 = getelementptr inbounds [14 x i8], [14 x i8]* @string3, i64 0, i64 0
call void(i8*,  ...) @printf( i8* %r14, i8* %r15)
%r16 = getelementptr inbounds [14 x i8], [14 x i8]* @string3, i64 0, i64 0
call void @__L_init__Exception( %__L_Exception* %exception, i64 12, i8* %r16)
br label %L2
L6:
%r17 = load i8*, i8** %r11
br label %L8
L2:
call void @__L_throw__Exception( %__L_Exception* %exception)
unreachable
L8:
ret i8* %r17
}
@string4 = private unnamed_addr constant [16 x i8] c"Free mem: [%s]\0A\00"
define internal void @freemem__i8$( i8* %r1 ) #0 nounwind {
entry:
%r2 = getelementptr inbounds [16 x i8], [16 x i8]* @string4, i64 0, i64 0
call void(i8*,  ...) @printf( i8* %r2, i8* %r1)
call void @free( i8* %r1)
br label %L1
L1:
ret void
}
@string5 = private unnamed_addr constant [28 x i8] c"Default constructor string\0A\00"
define external void @__C_std__String__$ctor( %std__String* %ths ) #0 nounwind {
entry:
%r1 = getelementptr inbounds [28 x i8], [28 x i8]* @string5, i64 0, i64 0
call void(i8*,  ...) @printf( i8* %r1)
%r2 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
store i8* null, i8** %r2
%r3 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
store i32 0, i32* %r3
br label %L1
L1:
ret void
}
@string6 = private unnamed_addr constant [25 x i8] c"Constructor string [%s]\0A\00"
define external void @__C_std__String__$ctor__i8$( %std__String* %ths, i8* %r1 ) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
entry:
%excptr = alloca i8*
%excidx = alloca i32
%initstate = alloca i32
%r3 = alloca i32, align 4
%r2 = call i64 @strlen( i8* %r1)
%r4 = trunc i64 %r2 to i32
store i32 %r4, i32* %r3
%r5 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r6 = load i32, i32* %r3
%r7 = add nsw i32 %r6, 1
%r8 = sext i32 %r7 to i64
%r9 = invoke i8* @allocmem__i64( i64 %r8) to label %L3 unwind label %L1
L3:
store i8* %r9, i8** %r5
%r18 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r19 = load i32, i32* %r3
store i32 %r19, i32* %r18
%r20 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r21 = load i8*, i8** %r20
%r22 = load i32, i32* %r3
%r23 = sext i32 %r22 to i64
%r24 = call i8* @memcpy( i8* %r21, i8* %r1, i64 %r23)
%r25 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r26 = load i8*, i8** %r25
%r27 = load i32, i32* %r3
%r28 = getelementptr i8, i8* %r26, i32 %r27
store i8 0, i8* %r28
%r29 = getelementptr inbounds [25 x i8], [25 x i8]* @string6, i64 0, i64 0
%r30 = call i8* @__C_std__String__c_str__const( %std__String* %ths)
call void(i8*,  ...) @printf( i8* %r29, i8* %r30)
br label %L4
L1:
%r15 = landingpad { i8*, i32 } cleanup
%r16 = extractvalue { i8*, i32 } %r15, 0
store i8* %r16, i8** %excptr
%r17 = extractvalue { i8*, i32 } %r15, 1
store i32 %r17, i32* %excidx
store i32 0, i32* %initstate
br label %L2
L2:
%r10 = load i32, i32* %initstate
call void @__partial_dtor_std__String( %std__String* %ths, i32 %r10)
%r11 = load i8*, i8** %excptr
%r12 = load i32, i32* %excidx
%r13 = insertvalue { i8*, i32 } undef, i8* %r11, 0
%r14 = insertvalue { i8*, i32 } %r13, i32 %r12, 1
resume { i8*, i32 } %r14
L4:
ret void
}
@string7 = private unnamed_addr constant [24 x i8] c"Destructor string [%s]\0A\00"
define external void @__dtor_std__String( %std__String* %ths ) #0 nounwind {
entry:
%r1 = getelementptr inbounds [24 x i8], [24 x i8]* @string7, i64 0, i64 0
%r2 = call i8* @__C_std__String__c_str__const( %std__String* %ths)
call void(i8*,  ...) @printf( i8* %r1, i8* %r2)
%r3 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r4 = load i8*, i8** %r3
%r5 = icmp ne i8* %r4, null
br i1 %r5, label %L2, label %L1
L2:
%r6 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r7 = load i8*, i8** %r6
call void @freemem__i8$( i8* %r7)
br label %L1
L1:
br label %L3
L3:
ret void
}
define external void @__C_std__String__append__i8$__i32( %std__String* %ths, i8* %r1, i32 %r2 ) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
entry:
%excptr = alloca i8*
%excidx = alloca i32
%r16 = alloca i8*
%r3 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r4 = load i32, i32* %r3
%r5 = add nsw i32 %r4, %r2
%r6 = add nsw i32 %r5, 1
%r7 = sext i32 %r6 to i64
%r8 = invoke i8* @allocmem__i64( i64 %r7) to label %L3 unwind label %L1
L3:
store i8* %r8, i8** %r16
%r19 = load i8*, i8** %r16
%r17 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r20 = load i8*, i8** %r17
%r18 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r21 = load i32, i32* %r18
%r22 = sext i32 %r21 to i64
%r23 = call i8* @memcpy( i8* %r19, i8* %r20, i64 %r22)
%r25 = load i8*, i8** %r16
%r24 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r26 = load i32, i32* %r24
%r27 = getelementptr i8, i8* %r25, i32 %r26
%r28 = sext i32 %r2 to i64
%r29 = call i8* @memcpy( i8* %r27, i8* %r1, i64 %r28)
%r33 = load i8*, i8** %r16
%r30 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r31 = load i32, i32* %r30
%r32 = add nsw i32 %r31, %r2
%r34 = getelementptr i8, i8* %r33, i32 %r32
store i8 0, i8* %r34
%r35 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r36 = load i8*, i8** %r35
call void @freemem__i8$( i8* %r36)
%r37 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r38 = load i8*, i8** %r16
store i8* %r38, i8** %r37
%r39 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r40 = load i32, i32* %r39
%r41 = add nsw i32 %r40, %r2
store i32 %r41, i32* %r39
br label %L4
L1:
%r13 = landingpad { i8*, i32 } cleanup
%r14 = extractvalue { i8*, i32 } %r13, 0
store i8* %r14, i8** %excptr
%r15 = extractvalue { i8*, i32 } %r13, 1
store i32 %r15, i32* %excidx
br label %L2
L2:
%r9 = load i8*, i8** %excptr
%r10 = load i32, i32* %excidx
%r11 = insertvalue { i8*, i32 } undef, i8* %r9, 0
%r12 = insertvalue { i8*, i32 } %r11, i32 %r10, 1
resume { i8*, i32 } %r12
L4:
ret void
}
define external void @__C_std__String__$plus__std__String$__const( %std__String* sret %rt, %std__String* %ths, %std__String* %r1 ) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
entry:
%excptr = alloca i8*
%excidx = alloca i32
call void @__C_std__String__$ctor( %std__String* %rt)
%r17 = alloca i8*
%r2 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r4 = load i32, i32* %r2
%r3 = getelementptr inbounds %std__String, %std__String* %r1, i32 0, i32 1
%r5 = load i32, i32* %r3
%r6 = add nsw i32 %r4, %r5
%r7 = add nsw i32 %r6, 1
%r8 = sext i32 %r7 to i64
%r9 = invoke i8* @allocmem__i64( i64 %r8) to label %L3 unwind label %L1
L3:
store i8* %r9, i8** %r17
%r20 = load i8*, i8** %r17
%r18 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r21 = load i8*, i8** %r18
%r19 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r22 = load i32, i32* %r19
%r23 = sext i32 %r22 to i64
%r24 = call i8* @memcpy( i8* %r20, i8* %r21, i64 %r23)
%r26 = load i8*, i8** %r17
%r25 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r27 = load i32, i32* %r25
%r28 = getelementptr i8, i8* %r26, i32 %r27
%r29 = getelementptr inbounds %std__String, %std__String* %r1, i32 0, i32 0
%r31 = load i8*, i8** %r29
%r30 = getelementptr inbounds %std__String, %std__String* %r1, i32 0, i32 1
%r32 = load i32, i32* %r30
%r33 = sext i32 %r32 to i64
%r34 = call i8* @memcpy( i8* %r28, i8* %r31, i64 %r33)
%r40 = load i8*, i8** %r17
%r35 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r37 = load i32, i32* %r35
%r36 = getelementptr inbounds %std__String, %std__String* %r1, i32 0, i32 1
%r38 = load i32, i32* %r36
%r39 = add nsw i32 %r37, %r38
%r41 = getelementptr i8, i8* %r40, i32 %r39
store i8 0, i8* %r41
%r42 = getelementptr inbounds %std__String, %std__String* %rt, i32 0, i32 0
%r43 = load i8*, i8** %r17
store i8* %r43, i8** %r42
%r44 = getelementptr inbounds %std__String, %std__String* %rt, i32 0, i32 1
%r45 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 1
%r47 = load i32, i32* %r45
%r46 = getelementptr inbounds %std__String, %std__String* %r1, i32 0, i32 1
%r48 = load i32, i32* %r46
%r49 = add nsw i32 %r47, %r48
store i32 %r49, i32* %r44
br label %L4
L1:
%r14 = landingpad { i8*, i32 } cleanup
%r15 = extractvalue { i8*, i32 } %r14, 0
store i8* %r15, i8** %excptr
%r16 = extractvalue { i8*, i32 } %r14, 1
store i32 %r16, i32* %excidx
br label %L2
L2:
%r10 = load i8*, i8** %excptr
%r11 = load i32, i32* %excidx
%r12 = insertvalue { i8*, i32 } undef, i8* %r10, 0
%r13 = insertvalue { i8*, i32 } %r12, i32 %r11, 1
resume { i8*, i32 } %r13
L4:
ret void
}
@string8 = private unnamed_addr constant [12 x i8] c"Get string\0A\00"
@string9 = private unnamed_addr constant [1 x i8] c"\00"
define external i8* @__C_std__String__c_str__const( %std__String* %ths ) #0 nounwind {
entry:
%r1 = getelementptr inbounds [12 x i8], [12 x i8]* @string8, i64 0, i64 0
call void(i8*,  ...) @printf( i8* %r1)
%r2 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r3 = load i8*, i8** %r2
%r4 = icmp ne i8* %r3, null
br i1 %r4, label %L5, label %L4
L5:
%r5 = getelementptr inbounds %std__String, %std__String* %ths, i32 0, i32 0
%r6 = load i8*, i8** %r5
br label %L2
L4:
%r7 = getelementptr inbounds [1 x i8], [1 x i8]* @string9, i64 0, i64 0
br label %L3
L2:
ret i8* %r6
L3:
ret i8* %r7
}
@string10 = private unnamed_addr constant [15 x i8] c"Hello Universe\00"
@string11 = private unnamed_addr constant [2 x i8] c"!\00"
define internal void @getGreeting( %std__String* sret %rt ) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
entry:
%excptr = alloca i8*
%excidx = alloca i32
%r13 = alloca %std__String, align 8
%r1 = getelementptr inbounds [15 x i8], [15 x i8]* @string10, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r13, i8* %r1) to label %L3 unwind label %L1
L3:
%r14 = alloca %std__String, align 8
%r9 = getelementptr inbounds [2 x i8], [2 x i8]* @string11, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r14, i8* %r9) to label %L5 unwind label %L4
L5:
invoke void @__C_std__String__$plus__std__String$__const( %std__String* sret %rt, %std__String* %r13, %std__String* %r14) to label %L9 unwind label %L8
L9:
br label %L11
L1:
%r6 = landingpad { i8*, i32 } cleanup
%r7 = extractvalue { i8*, i32 } %r6, 0
store i8* %r7, i8** %excptr
%r8 = extractvalue { i8*, i32 } %r6, 1
store i32 %r8, i32* %excidx
br label %L2
L4:
%r10 = landingpad { i8*, i32 } cleanup
%r11 = extractvalue { i8*, i32 } %r10, 0
store i8* %r11, i8** %excptr
%r12 = extractvalue { i8*, i32 } %r10, 1
store i32 %r12, i32* %excidx
br label %L2
L8:
%r15 = landingpad { i8*, i32 } cleanup
%r16 = extractvalue { i8*, i32 } %r15, 0
store i8* %r16, i8** %excptr
%r17 = extractvalue { i8*, i32 } %r15, 1
store i32 %r17, i32* %excidx
br label %L7
L7:
call void @__dtor_std__String( %std__String* %r14)
br label %L6
L6:
call void @__dtor_std__String( %std__String* %r13)
br label %L2
L2:
%r2 = load i8*, i8** %excptr
%r3 = load i32, i32* %excidx
%r4 = insertvalue { i8*, i32 } undef, i8* %r2, 0
%r5 = insertvalue { i8*, i32 } %r4, i32 %r3, 1
resume { i8*, i32 } %r5
L11:
call void @__dtor_std__String( %std__String* %r14)
br label %L10
L10:
call void @__dtor_std__String( %std__String* %r13)
br label %L12
L12:
ret void
}
@string12 = private unnamed_addr constant [6 x i8] c"Hello\00"
@string13 = private unnamed_addr constant [2 x i8] c" \00"
@string14 = private unnamed_addr constant [9 x i8] c"Universe\00"
define internal void @getGreetingA1( %std__String* sret %rt ) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
entry:
%excptr = alloca i8*
%excidx = alloca i32
%r5 = alloca [4 x %std__String], align 8
%r6 = alloca i32, align 4
store i32 -1, i32* %r6
%r7 = getelementptr inbounds [4 x %std__String], [4 x %std__String]* %r5, i32 0, i32 0
%r9 = load i32, i32* %r6
%r10 = add nsw i32 %r9, 1
store i32 %r10, i32* %r6
%r8 = getelementptr inbounds %std__String, %std__String* %r7, i32 %r10
%r1 = getelementptr inbounds [6 x i8], [6 x i8]* @string12, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r8, i8* %r1) to label %L2 unwind label %L1
L2:
%r12 = load i32, i32* %r6
%r13 = add nsw i32 %r12, 1
store i32 %r13, i32* %r6
%r11 = getelementptr inbounds %std__String, %std__String* %r7, i32 %r13
%r2 = getelementptr inbounds [2 x i8], [2 x i8]* @string13, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r11, i8* %r2) to label %L3 unwind label %L1
L3:
%r15 = load i32, i32* %r6
%r16 = add nsw i32 %r15, 1
store i32 %r16, i32* %r6
%r14 = getelementptr inbounds %std__String, %std__String* %r7, i32 %r16
%r3 = getelementptr inbounds [9 x i8], [9 x i8]* @string14, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r14, i8* %r3) to label %L4 unwind label %L1
L4:
%r18 = load i32, i32* %r6
%r19 = add nsw i32 %r18, 1
store i32 %r19, i32* %r6
%r17 = getelementptr inbounds %std__String, %std__String* %r7, i32 %r19
%r4 = getelementptr inbounds [2 x i8], [2 x i8]* @string11, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r17, i8* %r4) to label %L5 unwind label %L1
L5:
br label %L7
L1:
%r21 = landingpad { i8*, i32 } cleanup
%r22 = extractvalue { i8*, i32 } %r21, 0
store i8* %r22, i8** %excptr
%r23 = extractvalue { i8*, i32 } %r21, 1
store i32 %r23, i32* %excidx
br label %L1_dtor
L1_dtor:
%r20 = load i32, i32* %r6
call void @__dtor_4__std__String( [4 x %std__String]* %r5, i32 %r20)
br label %L6
L6:
%r24 = load i8*, i8** %excptr
%r25 = load i32, i32* %excidx
%r26 = insertvalue { i8*, i32 } undef, i8* %r24, 0
%r27 = insertvalue { i8*, i32 } %r26, i32 %r25, 1
resume { i8*, i32 } %r27
L7:
%r43 = alloca %std__String, align 8
%r38 = alloca %std__String, align 8
%r28 = getelementptr inbounds [4 x %std__String], [4 x %std__String]* %r5, i32 0, i32 0
%r29 = getelementptr inbounds [4 x %std__String], [4 x %std__String]* %r5, i32 0, i32 1
invoke void @__C_std__String__$plus__std__String$__const( %std__String* sret %r38, %std__String* %r28, %std__String* %r29) to label %L11 unwind label %L8
L11:
%r37 = getelementptr inbounds [4 x %std__String], [4 x %std__String]* %r5, i32 0, i32 2
invoke void @__C_std__String__$plus__std__String$__const( %std__String* sret %r43, %std__String* %r38, %std__String* %r37) to label %L14 unwind label %L13
L14:
%r42 = getelementptr inbounds [4 x %std__String], [4 x %std__String]* %r5, i32 0, i32 3
invoke void @__C_std__String__$plus__std__String$__const( %std__String* sret %rt, %std__String* %r43, %std__String* %r42) to label %L17 unwind label %L16
L17:
br label %L20
L8:
%r34 = landingpad { i8*, i32 } cleanup
%r35 = extractvalue { i8*, i32 } %r34, 0
store i8* %r35, i8** %excptr
%r36 = extractvalue { i8*, i32 } %r34, 1
store i32 %r36, i32* %excidx
br label %L9
L13:
%r39 = landingpad { i8*, i32 } cleanup
%r40 = extractvalue { i8*, i32 } %r39, 0
store i8* %r40, i8** %excptr
%r41 = extractvalue { i8*, i32 } %r39, 1
store i32 %r41, i32* %excidx
br label %L12
L16:
%r44 = landingpad { i8*, i32 } cleanup
%r45 = extractvalue { i8*, i32 } %r44, 0
store i8* %r45, i8** %excptr
%r46 = extractvalue { i8*, i32 } %r44, 1
store i32 %r46, i32* %excidx
br label %L15
L15:
call void @__dtor_std__String( %std__String* %r43)
br label %L12
L12:
call void @__dtor_std__String( %std__String* %r38)
br label %L9
L9:
call void @__dtor_4__std__String( [4 x %std__String]* %r5, i32 4)
br label %L10
L10:
%r30 = load i8*, i8** %excptr
%r31 = load i32, i32* %excidx
%r32 = insertvalue { i8*, i32 } undef, i8* %r30, 0
%r33 = insertvalue { i8*, i32 } %r32, i32 %r31, 1
resume { i8*, i32 } %r33
L20:
call void @__dtor_std__String( %std__String* %r43)
br label %L19
L19:
call void @__dtor_std__String( %std__String* %r38)
br label %L18
L18:
call void @__dtor_4__std__String( [4 x %std__String]* %r5, i32 4)
br label %L21
L21:
ret void
}
@string15 = private unnamed_addr constant [13 x i8] c"Hello world!\00"
@string16 = private unnamed_addr constant [7 x i8] c"World!\00"
@string17 = private unnamed_addr constant [13 x i8] c"GREETING %s\0A\00"
@string18 = private unnamed_addr constant [31 x i8] c"GREET1 %s GREET2 %s GREET3 %s\0A\00"
@string19 = private unnamed_addr constant [12 x i8] c"ERR %ld %s\0A\00"
define internal void @test__i32( i32 %r1 ) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
entry:
%exception = alloca %__L_Exception
%excptr = alloca i8*
%excidx = alloca i32
store i32 %r1, i32* @g_maxAllocCnt
store i32 0, i32* @g_allocCnt
%r7 = alloca %std__String, align 8
invoke void @getGreeting( %std__String* sret %r7) to label %L4 unwind label %L3
L4:
%r13 = alloca %std__String, align 8
invoke void @getGreetingA1( %std__String* sret %r13) to label %L8 unwind label %L5
L8:
%r15 = alloca %std__String, align 8
%r14 = getelementptr inbounds [13 x i8], [13 x i8]* @string15, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r15, i8* %r14) to label %L11 unwind label %L10
L11:
%r53 = alloca %std__String, align 8
%r46 = alloca %std__String, align 8
%r33 = alloca %std__String, align 8
%r21 = getelementptr inbounds [6 x i8], [6 x i8]* @string12, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r33, i8* %r21) to label %L14 unwind label %L13
L14:
%r34 = alloca %std__String, align 8
%r27 = getelementptr inbounds [2 x i8], [2 x i8]* @string13, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r34, i8* %r27) to label %L16 unwind label %L15
L16:
invoke void @__C_std__String__$plus__std__String$__const( %std__String* sret %r46, %std__String* %r33, %std__String* %r34) to label %L21 unwind label %L17
L21:
%r47 = alloca %std__String, align 8
%r40 = getelementptr inbounds [7 x i8], [7 x i8]* @string16, i64 0, i64 0
invoke void @__C_std__String__$ctor__i8$( %std__String* %r47, i8* %r40) to label %L23 unwind label %L22
L23:
invoke void @__C_std__String__$plus__std__String$__const( %std__String* sret %r53, %std__String* %r46, %std__String* %r47) to label %L27 unwind label %L26
L27:
%r54 = getelementptr inbounds [13 x i8], [13 x i8]* @string17, i64 0, i64 0
%r55 = call i8* @__C_std__String__c_str__const( %std__String* %r53)
call void(i8*,  ...) @printf( i8* %r54, i8* %r55)
br label %L29
L29:
call void @__dtor_std__String( %std__String* %r53)
call void @__dtor_std__String( %std__String* %r47)
call void @__dtor_std__String( %std__String* %r46)
call void @__dtor_std__String( %std__String* %r34)
call void @__dtor_std__String( %std__String* %r33)
%r56 = getelementptr inbounds [31 x i8], [31 x i8]* @string18, i64 0, i64 0
%r57 = call i8* @__C_std__String__c_str__const( %std__String* %r7)
%r58 = call i8* @__C_std__String__c_str__const( %std__String* %r13)
%r59 = call i8* @__C_std__String__c_str__const( %std__String* %r15)
call void(i8*,  ...) @printf( i8* %r56, i8* %r57, i8* %r58, i8* %r59)
br label %L30
L30:
call void @__dtor_std__String( %std__String* %r15)
call void @__dtor_std__String( %std__String* %r13)
call void @__dtor_std__String( %std__String* %r7)
br label %L32
L1:
%r62 = getelementptr inbounds %__L_Exception, %__L_Exception* %exception, i32 0, i32 0
%r60 = load i64, i64* %r62
%r63 = getelementptr inbounds %__L_Exception, %__L_Exception* %exception, i32 0, i32 1
%r61 = load i8*, i8** %r63
%r64 = getelementptr inbounds [12 x i8], [12 x i8]* @string19, i64 0, i64 0
call void(i8*,  ...) @printf( i8* %r64, i64 %r60, i8* %r61)
br label %L31
L31:
call void @__L_free__ExceptionMsg( i8* %r61)
br label %L32
L32:
br label %L33
L2:
br label %L1
L3:
%r2 = landingpad { i8*, i32 } catch i8* null
%r3 = extractvalue { i8*, i32 } %r2, 0
%r4 = call i8* @__cxa_begin_catch( i8* %r3)
%r5 = bitcast i8* %r4 to %__L_Exception*
%r6 = load %__L_Exception, %__L_Exception* %r5
store %__L_Exception %r6, %__L_Exception* %exception
call void @__cxa_end_catch()
br label %L2
L5:
%r8 = landingpad { i8*, i32 } catch i8* null
%r9 = extractvalue { i8*, i32 } %r8, 0
%r10 = call i8* @__cxa_begin_catch( i8* %r9)
%r11 = bitcast i8* %r10 to %__L_Exception*
%r12 = load %__L_Exception, %__L_Exception* %r11
store %__L_Exception %r12, %__L_Exception* %exception
call void @__cxa_end_catch()
br label %L6
L10:
%r16 = landingpad { i8*, i32 } catch i8* null
%r17 = extractvalue { i8*, i32 } %r16, 0
%r18 = call i8* @__cxa_begin_catch( i8* %r17)
%r19 = bitcast i8* %r18 to %__L_Exception*
%r20 = load %__L_Exception, %__L_Exception* %r19
store %__L_Exception %r20, %__L_Exception* %exception
call void @__cxa_end_catch()
br label %L9
L12:
call void @__dtor_std__String( %std__String* %r15)
br label %L9
L9:
call void @__dtor_std__String( %std__String* %r13)
br label %L6
L6:
call void @__dtor_std__String( %std__String* %r7)
br label %L7
L7:
br label %L2
L13:
%r22 = landingpad { i8*, i32 } catch i8* null
%r23 = extractvalue { i8*, i32 } %r22, 0
%r24 = call i8* @__cxa_begin_catch( i8* %r23)
%r25 = bitcast i8* %r24 to %__L_Exception*
%r26 = load %__L_Exception, %__L_Exception* %r25
store %__L_Exception %r26, %__L_Exception* %exception
call void @__cxa_end_catch()
br label %L12
L15:
%r28 = landingpad { i8*, i32 } catch i8* null
%r29 = extractvalue { i8*, i32 } %r28, 0
%r30 = call i8* @__cxa_begin_catch( i8* %r29)
%r31 = bitcast i8* %r30 to %__L_Exception*
%r32 = load %__L_Exception, %__L_Exception* %r31
store %__L_Exception %r32, %__L_Exception* %exception
call void @__cxa_end_catch()
br label %L12
L17:
%r35 = landingpad { i8*, i32 } catch i8* null
%r36 = extractvalue { i8*, i32 } %r35, 0
%r37 = call i8* @__cxa_begin_catch( i8* %r36)
%r38 = bitcast i8* %r37 to %__L_Exception*
%r39 = load %__L_Exception, %__L_Exception* %r38
store %__L_Exception %r39, %__L_Exception* %exception
call void @__cxa_end_catch()
br label %L19
L22:
%r41 = landingpad { i8*, i32 } catch i8* null
%r42 = extractvalue { i8*, i32 } %r41, 0
%r43 = call i8* @__cxa_begin_catch( i8* %r42)
%r44 = bitcast i8* %r43 to %__L_Exception*
%r45 = load %__L_Exception, %__L_Exception* %r44
store %__L_Exception %r45, %__L_Exception* %exception
call void @__cxa_end_catch()
br label %L19
L26:
%r48 = landingpad { i8*, i32 } catch i8* null
%r49 = extractvalue { i8*, i32 } %r48, 0
%r50 = call i8* @__cxa_begin_catch( i8* %r49)
%r51 = bitcast i8* %r50 to %__L_Exception*
%r52 = load %__L_Exception, %__L_Exception* %r51
store %__L_Exception %r52, %__L_Exception* %exception
call void @__cxa_end_catch()
br label %L25
L25:
call void @__dtor_std__String( %std__String* %r47)
br label %L24
L24:
call void @__dtor_std__String( %std__String* %r46)
br label %L19
L19:
call void @__dtor_std__String( %std__String* %r34)
br label %L18
L18:
call void @__dtor_std__String( %std__String* %r33)
br label %L20
L20:
br label %L12
L33:
ret void
}
@string20 = private unnamed_addr constant [20 x i8] c"----- NO EXCEPTION\0A\00"
@string21 = private unnamed_addr constant [11 x i8] c"ALLOCS %d\0A\00"
@string22 = private unnamed_addr constant [15 x i8] c"----- TEST %d\0A\00"

define dso_local i32 @main(i32 %argc, i8** %argv) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*)
{
entry:
%r1 = alloca i32, align 4
%r2 = getelementptr inbounds [20 x i8], [20 x i8]* @string20, i64 0, i64 0
call void(i8*,  ...) @printf( i8* %r2)
call void @test__i32( i32 1000)
%r3 = getelementptr inbounds [11 x i8], [11 x i8]* @string21, i64 0, i64 0
%r4 = load i32, i32* @g_allocCnt
call void(i8*,  ...) @printf( i8* %r3, i32 %r4)
%r5 = alloca i32, align 4
store i32 1, i32* %r5
%r6 = alloca i32, align 4
%r7 = load i32, i32* @g_allocCnt
store i32 %r7, i32* %r6
br label %L4
L4:
%r8 = load i32, i32* %r5
%r9 = load i32, i32* %r6
%r10 = icmp slt i32 %r8, %r9
br i1 %r10, label %L3, label %L2
L3:
%r11 = getelementptr inbounds [15 x i8], [15 x i8]* @string22, i64 0, i64 0
%r12 = load i32, i32* %r5
call void(i8*,  ...) @printf( i8* %r11, i32 %r12)
%r13 = load i32, i32* %r5
call void @test__i32( i32 %r13)
%r14 = load i32, i32* %r5
%r15 = add nsw i32 %r14, 1
store i32 %r15, i32* %r5
br label %L4
L2:
store i32 0, i32* %r1
br label %L5
L5:
br label %L1
L1:
%r16 = load i32, i32* %r1
ret i32 %r16
}


