; ModuleID = 'examples/language1/sources/fibo.prg'
source_filename = "examples/language1/sources/fibo.prg"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"
@llvm.global_ctors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__ctors, i8* null }]
@llvm.global_dtors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__dtors, i8* null }]



define internal void @_GLOBAL__ctors() nounwind uwtable readnone optsize ssp section ".text.startup" {
  ret void
}

define internal void @_GLOBAL__dtors() nounwind uwtable readnone optsize ssp section ".text.startup" {
  ret void
}


declare external void @printf( i8*, i32 ) #1 nounwind


define internal void @swap_i32$( i32* %r1, i32* %r2 ) #0 nounwind {
entry:
%r3 = alloca i32, align 4
%r5 = load i32, i32* %r1
store i32 %r5, i32* %r3
%r6 = load i32, i32* %r2
store i32 %r6, i32* %r1
%r7 = load i32, i32* %r3
store i32 %r7, i32* %r2
ret void
}


define internal i32 @fibonacci__i32( i32 %r1 ) #0 nounwind {
entry:
%r2 = alloca i32, align 4
store i32 0, i32* %r2
%r3 = alloca i32, align 4
store i32 1, i32* %r3
%r4 = alloca i32, align 4
store i32 0, i32* %r4
br label %L3
L3:
%r5 = load i32, i32* %r4
%r6 = icmp slt i32 %r5, %r1
br i1 %r6, label %L2, label %L1
L2:
%r10 = load i32, i32* %r3
%r11 = load i32, i32* %r2
%r12 = add nsw i32 %r10, %r11
store i32 %r12, i32* %r2
call void @swap_i32$( i32* %r2, i32* %r3)
%r20 = load i32, i32* %r4
%r23 = add nsw i32 %r20, 1
store i32 %r23, i32* %r4
br label %L3
L1:
%r24 = load i32, i32* %r3
ret i32 %r24
}

@string1 = private unnamed_addr constant [12 x i8] c"Result: %d\0A\00"


define external i32 @main() #0 noinline nounwind {
entry:
%r2 = alloca i32, align 4
%r1 = call i32 @fibonacci__i32( i32 20)
store i32 %r1, i32* %r2
%r3 = getelementptr inbounds [12 x i8], [12 x i8]* @string1, i64 0, i64 0
%r4 = load i32, i32* %r2
call void @printf( i8* %r3, i32 %r4)
ret i32 0
}



attributes #0 = {
	"disable-tail-calls"="false" "frame-pointer"="all" "min-legal-vector-width"="0" 
	"correctly-rounded-divide-sqrt-fp-math"="false" "less-precise-fpmad"="false" "no-infs-fp-math"="false" 
	"no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "unsafe-fp-math"="false" 
	"no-jump-tables"="false" "stack-protector-buffer-size"="8" 
	"target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "use-soft-float"="false"
}
attributes #1 = {
	"no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "stack-protector-buffer-size"="8" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.0-4ubuntu1 "}
