----- NO EXCEPTION
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Get string
Constructor string [!]
Default constructor string
Default constructor string
Default constructor string
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Destructor string [Hello ]
Free mem: [Hello ]
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Constructor string [Hello world!]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Default constructor string
Get string
Constructor string [World!]
Default constructor string
Get string
GREETING Hello World!
Get string
Destructor string [Hello World!]
Free mem: [Hello World!]
Get string
Destructor string [World!]
Free mem: [World!]
Get string
Destructor string [Hello ]
Free mem: [Hello ]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Get string
Get string
GREET1 Hello Universe! GREET2 Hello Universe! GREET3 Hello world!
Get string
Destructor string [Hello world!]
Free mem: [Hello world!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ALLOCS 16
----- TEST 1
Throw: Max allowed allocations reached
ERR 201 Max allowed allocations reached
----- TEST 2
Get string
Constructor string [Hello Universe]
Throw: Max allowed allocations reached
ERR 201 Max allowed allocations reached
----- TEST 3
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Throw: Max allowed allocations reached
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
ERR 201 Max allowed allocations reached
----- TEST 4
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Throw: Max allowed allocations reached
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 5
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Throw: Max allowed allocations reached
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 6
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Throw: Max allowed allocations reached
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 7
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Throw: Max allowed allocations reached
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 8
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Get string
Constructor string [!]
Default constructor string
Throw: Max allowed allocations reached
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 9
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Get string
Constructor string [!]
Default constructor string
Default constructor string
Throw: Max allowed allocations reached
Get string
Destructor string [Hello ]
Free mem: [Hello ]
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 10
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Get string
Constructor string [!]
Default constructor string
Default constructor string
Default constructor string
Throw: Max allowed allocations reached
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Destructor string [Hello ]
Free mem: [Hello ]
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 11
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Get string
Constructor string [!]
Default constructor string
Default constructor string
Default constructor string
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Destructor string [Hello ]
Free mem: [Hello ]
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Throw: Max allowed allocations reached
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 12
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Get string
Constructor string [!]
Default constructor string
Default constructor string
Default constructor string
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Destructor string [Hello ]
Free mem: [Hello ]
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Constructor string [Hello world!]
Throw: Max allowed allocations reached
Get string
Destructor string [Hello world!]
Free mem: [Hello world!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 13
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Get string
Constructor string [!]
Default constructor string
Default constructor string
Default constructor string
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Destructor string [Hello ]
Free mem: [Hello ]
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Constructor string [Hello world!]
Get string
Constructor string [Hello]
Throw: Max allowed allocations reached
Get string
Destructor string [Hello world!]
Free mem: [Hello world!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 14
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Get string
Constructor string [!]
Default constructor string
Default constructor string
Default constructor string
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Destructor string [Hello ]
Free mem: [Hello ]
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Constructor string [Hello world!]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Default constructor string
Throw: Max allowed allocations reached
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Destructor string [Hello world!]
Free mem: [Hello world!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
----- TEST 15
Get string
Constructor string [Hello Universe]
Get string
Constructor string [!]
Default constructor string
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Get string
Constructor string [Universe]
Get string
Constructor string [!]
Default constructor string
Default constructor string
Default constructor string
Get string
Destructor string [Hello Universe]
Free mem: [Hello Universe]
Get string
Destructor string [Hello ]
Free mem: [Hello ]
Get string
Destructor string [!]
Free mem: [!]
Get string
Destructor string [Universe]
Free mem: [Universe]
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Constructor string [Hello world!]
Get string
Constructor string [Hello]
Get string
Constructor string [ ]
Default constructor string
Throw: Max allowed allocations reached
Get string
Destructor string [ ]
Free mem: [ ]
Get string
Destructor string [Hello]
Free mem: [Hello]
Get string
Destructor string [Hello world!]
Free mem: [Hello world!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
Get string
Destructor string [Hello Universe!]
Free mem: [Hello Universe!]
ERR 201 Max allowed allocations reached
