Shift token "extern" at line 1 in state 1, goto 4
Shift token DQSTRING = "C" at line 1 in state 4, goto 27
Shift token "procedure" at line 1 in state 27, goto 49
Shift token IDENT = "printf" at line 1 in state 49, goto 70
Shift token '(' at line 1 in state 70, goto 135
Shift token "const" at line 1 in state 135, goto 18
Shift token IDENT = "byte" at line 1 in state 18, goto 17
Reduce #1 to typename by token '^' at line 1 in state 17, goto 39
Shift token '^' at line 1 in state 39, goto 59
Reduce #3 to typespec by token IDENT = "fmt" at line 1 in state 59, call typespec "const^", goto 245
Shift token IDENT = "fmt" at line 1 in state 245, goto 313
Reduce #2 to extern_parameters by token "..." at line 1 in state 313, call extern_paramdef, goto 243
Reduce #1 to extern_paramlist by token "..." at line 1 in state 243, call extern_paramdeflist, goto 244
Shift token "..." at line 1 in state 244, goto 312
Shift token ')' at line 1 in state 312, goto 339
Shift token ';' at line 1 in state 339, goto 357
Reduce #9 to extern_definition by token "interface" at line 3 in state 357, call extern_procdef_vararg, goto 3
Reduce #0 to extern_definitionlist by token "interface" at line 3 in state 3, goto 26
Reduce #2 to extern_definitionlist by token "interface" at line 3 in state 26, goto 2
Shift token "interface" at line 3 in state 2, goto 23
Shift token IDENT = "Object" at line 3 in state 23, goto 47
Shift token '{' at line 4 in state 47, goto 68
Shift token "function" at line 5 in state 68, goto 131
Shift token IDENT = "x" at line 5 in state 131, goto 216
Shift token IDENT = "int" at line 5 in state 216, goto 17
Reduce #1 to typename by token '(' at line 5 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 5 in state 8, call typespec "", goto 304
Shift token '(' at line 5 in state 304, goto 332
Reduce #0 to extern_paramlist by token ')' at line 5 in state 332, call extern_paramdeflist, goto 351
Shift token ')' at line 5 in state 351, goto 364
Shift token "const" at line 5 in state 364, goto 375
Shift token ';' at line 5 in state 375, goto 381
Reduce #8 to interface_definition by token "function" at line 6 in state 381, call interface_funcdef {const=true}, goto 130
Shift token "function" at line 6 in state 130, goto 131
Shift token IDENT = "y" at line 6 in state 131, goto 216
Shift token IDENT = "int" at line 6 in state 216, goto 17
Reduce #1 to typename by token '(' at line 6 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 6 in state 8, call typespec "", goto 304
Shift token '(' at line 6 in state 304, goto 332
Reduce #0 to extern_paramlist by token ')' at line 6 in state 332, call extern_paramdeflist, goto 351
Shift token ')' at line 6 in state 351, goto 364
Shift token "const" at line 6 in state 364, goto 375
Shift token ';' at line 6 in state 375, goto 381
Reduce #8 to interface_definition by token "function" at line 7 in state 381, call interface_funcdef {const=true}, goto 130
Shift token "function" at line 7 in state 130, goto 131
Shift token IDENT = "ofs_x" at line 7 in state 131, goto 216
Shift token IDENT = "int" at line 7 in state 216, goto 17
Reduce #1 to typename by token '(' at line 7 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 7 in state 8, call typespec "", goto 304
Shift token '(' at line 7 in state 304, goto 332
Shift token IDENT = "int" at line 7 in state 332, goto 17
Reduce #1 to typename by token IDENT = "addx" at line 7 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "addx" at line 7 in state 8, call typespec "", goto 245
Shift token IDENT = "addx" at line 7 in state 245, goto 313
Reduce #2 to extern_parameters by token ')' at line 7 in state 313, call extern_paramdef, goto 243
Reduce #1 to extern_paramlist by token ')' at line 7 in state 243, call extern_paramdeflist, goto 351
Shift token ')' at line 7 in state 351, goto 364
Shift token "const" at line 7 in state 364, goto 375
Shift token ';' at line 7 in state 375, goto 381
Reduce #8 to interface_definition by token "function" at line 8 in state 381, call interface_funcdef {const=true}, goto 130
Shift token "function" at line 8 in state 130, goto 131
Shift token IDENT = "ofs_y" at line 8 in state 131, goto 216
Shift token IDENT = "int" at line 8 in state 216, goto 17
Reduce #1 to typename by token '(' at line 8 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 8 in state 8, call typespec "", goto 304
Shift token '(' at line 8 in state 304, goto 332
Shift token IDENT = "int" at line 8 in state 332, goto 17
Reduce #1 to typename by token IDENT = "addy" at line 8 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "addy" at line 8 in state 8, call typespec "", goto 245
Shift token IDENT = "addy" at line 8 in state 245, goto 313
Reduce #2 to extern_parameters by token ')' at line 8 in state 313, call extern_paramdef, goto 243
Reduce #1 to extern_paramlist by token ')' at line 8 in state 243, call extern_paramdeflist, goto 351
Shift token ')' at line 8 in state 351, goto 364
Shift token "const" at line 8 in state 364, goto 375
Shift token ';' at line 8 in state 375, goto 381
Reduce #8 to interface_definition by token '}' at line 9 in state 381, call interface_funcdef {const=true}, goto 130
Reduce #0 to interface_definitionlist by token '}' at line 9 in state 130, goto 215
Reduce #2 to interface_definitionlist by token '}' at line 9 in state 215, goto 215
Reduce #2 to interface_definitionlist by token '}' at line 9 in state 215, goto 215
Reduce #2 to interface_definitionlist by token '}' at line 9 in state 215, goto 215
Reduce #2 to interface_definitionlist by token '}' at line 9 in state 215, goto 129
Shift token '}' at line 9 in state 129, goto 214
Reduce #5 to interfacedefinition by token "interface" at line 11 in state 214, call interfacedef, goto 12
Reduce #1 to free_definition by token "interface" at line 11 in state 12, call definition 1, goto 7
Shift token "interface" at line 11 in state 7, goto 23
Shift token IDENT = "ObjectUpdater" at line 11 in state 23, goto 47
Shift token '{' at line 12 in state 47, goto 68
Shift token "operator" at line 13 in state 68, goto 133
Shift token '=' at line 13 in state 133, goto 222
Reduce #1 to operatordecl by token '(' at line 13 in state 222, call operatordecl {name="=",symbol="assign"}, goto 218
Shift token '(' at line 13 in state 218, goto 307
Shift token IDENT = "int" at line 13 in state 307, goto 17
Reduce #1 to typename by token IDENT = "x_" at line 13 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "x_" at line 13 in state 8, call typespec "", goto 245
Shift token IDENT = "x_" at line 13 in state 245, goto 313
Shift token ',' at line 13 in state 313, goto 340
Shift token IDENT = "int" at line 13 in state 340, goto 17
Reduce #1 to typename by token IDENT = "y_" at line 13 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "y_" at line 13 in state 8, call typespec "", goto 245
Shift token IDENT = "y_" at line 13 in state 245, goto 313
Reduce #2 to extern_parameters by token ')' at line 13 in state 313, call extern_paramdef, goto 358
Reduce #4 to extern_parameters by token ')' at line 13 in state 358, call extern_paramdef, goto 243
Reduce #1 to extern_paramlist by token ')' at line 13 in state 243, call extern_paramdeflist, goto 335
Shift token ')' at line 13 in state 335, goto 354
Shift token ';' at line 13 in state 354, goto 368
Reduce #6 to interface_definition by token '}' at line 14 in state 368, call interface_operator_procdef {const=false}, goto 130
Reduce #0 to interface_definitionlist by token '}' at line 14 in state 130, goto 215
Reduce #2 to interface_definitionlist by token '}' at line 14 in state 215, goto 129
Shift token '}' at line 14 in state 129, goto 214
Reduce #5 to interfacedefinition by token "class" at line 16 in state 214, call interfacedef, goto 12
Reduce #1 to free_definition by token "class" at line 16 in state 12, call definition 1, goto 7
Shift token "class" at line 16 in state 7, goto 20
Shift token IDENT = "Point" at line 16 in state 20, goto 43
Shift token ':' at line 16 in state 43, goto 65
Shift token IDENT = "Object" at line 16 in state 65, goto 17
Reduce #1 to typename by token ',' at line 16 in state 17, goto 45
Reduce #1 to typepath by token ',' at line 16 in state 45, call typespec "", goto 125
Shift token ',' at line 16 in state 125, goto 210
Shift token IDENT = "ObjectUpdater" at line 16 in state 210, goto 17
Reduce #1 to typename by token '{' at line 17 in state 17, goto 45
Reduce #1 to typepath by token '{' at line 17 in state 45, call typespec "", goto 125
Reduce #1 to inheritlist by token '{' at line 17 in state 125, call inheritdef 1, goto 302
Reduce #3 to inheritlist by token '{' at line 17 in state 302, call inheritdef 1, goto 126
Shift token '{' at line 17 in state 126, goto 211
Shift token "public" at line 18 in state 211, goto 25
Reduce #1 to linkage by token "constructor" at line 18 in state 25, call linkage {private=false,linkage="external"}, goto 119
Shift token "constructor" at line 18 in state 119, goto 207
Shift token '(' at line 18 in state 207, goto 300
Shift token IDENT = "int" at line 18 in state 300, goto 17
Reduce #1 to typename by token IDENT = "x_" at line 18 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "x_" at line 18 in state 8, call typespec "", goto 198
Shift token IDENT = "x_" at line 18 in state 198, goto 295
Reduce #2 to paramdecl by token ',' at line 18 in state 295, call paramdef, goto 201
Shift token ',' at line 18 in state 201, goto 297
Shift token IDENT = "int" at line 18 in state 297, goto 17
Reduce #1 to typename by token IDENT = "y_" at line 18 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "y_" at line 18 in state 8, call typespec "", goto 198
Shift token IDENT = "y_" at line 18 in state 198, goto 295
Reduce #2 to paramdecl by token ')' at line 18 in state 295, call paramdef, goto 201
Reduce #1 to parameters by token ')' at line 18 in state 201, goto 325
Reduce #3 to parameters by token ')' at line 18 in state 325, goto 200
Reduce #1 to parameterlist by token ')' at line 18 in state 200, call paramdeflist, goto 329
Shift token ')' at line 18 in state 329, goto 350
Shift token '{' at line 19 in state 350, goto 324
Shift token IDENT = "m_x" at line 20 in state 324, goto 79
Reduce #1 to expression by token '=' at line 20 in state 79, call variable, goto 76
Shift token '=' at line 20 in state 76, goto 145
Shift token IDENT = "x_" at line 20 in state 145, goto 79
Reduce #1 to expression by token ';' at line 20 in state 79, call variable, goto 252
Reduce #3 to expression by token ';' at line 20 in state 252, call operator "=", goto 76
Shift token ';' at line 20 in state 76, goto 141
Reduce #2 to statement by token IDENT = "this" at line 21 in state 141, call free_expression, goto 75
Shift token IDENT = "this" at line 21 in state 75, goto 79
Reduce #1 to expression by token "->" at line 21 in state 79, call variable, goto 76
Shift token "->" at line 21 in state 76, goto 144
Reduce #1 to indirection by token IDENT = "m_y" at line 21 in state 144, call count, goto 139
Shift token IDENT = "m_y" at line 21 in state 139, goto 246
Reduce #3 to iexpression by token '=' at line 21 in state 246, call rep_operator "->", goto 77
Reduce #1 to expression by token '=' at line 21 in state 77, goto 76
Shift token '=' at line 21 in state 76, goto 145
Shift token IDENT = "y_" at line 21 in state 145, goto 79
Reduce #1 to expression by token ';' at line 21 in state 79, call variable, goto 252
Reduce #3 to expression by token ';' at line 21 in state 252, call operator "=", goto 76
Shift token ';' at line 21 in state 76, goto 141
Reduce #2 to statement by token '}' at line 22 in state 141, call free_expression, goto 75
Reduce #0 to statementlist by token '}' at line 22 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 22 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 22 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 22 in state 74, call codeblock, goto 347
Shift token '}' at line 22 in state 347, goto 363
Reduce #6 to callablebody by token "public" at line 24 in state 363, call callablebody, goto 299
Reduce #3 to constructordefinition by token "public" at line 24 in state 299, call constructordef, goto 121
Reduce #1 to class_definition by token "public" at line 24 in state 121, call definition 2, goto 114
Shift token "public" at line 24 in state 114, goto 25
Reduce #1 to linkage by token "operator" at line 24 in state 25, call linkage {private=false,linkage="external"}, goto 119
Shift token "operator" at line 24 in state 119, goto 206
Shift token '=' at line 24 in state 206, goto 222
Reduce #1 to operatordecl by token '(' at line 24 in state 222, call operatordecl {name="=",symbol="assign"}, goto 298
Shift token '(' at line 24 in state 298, goto 108
Shift token IDENT = "int" at line 24 in state 108, goto 17
Reduce #1 to typename by token IDENT = "x_" at line 24 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "x_" at line 24 in state 8, call typespec "", goto 198
Shift token IDENT = "x_" at line 24 in state 198, goto 295
Reduce #2 to paramdecl by token ',' at line 24 in state 295, call paramdef, goto 201
Shift token ',' at line 24 in state 201, goto 297
Shift token IDENT = "int" at line 24 in state 297, goto 17
Reduce #1 to typename by token IDENT = "y_" at line 24 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "y_" at line 24 in state 8, call typespec "", goto 198
Shift token IDENT = "y_" at line 24 in state 198, goto 295
Reduce #2 to paramdecl by token ')' at line 24 in state 295, call paramdef, goto 201
Reduce #1 to parameters by token ')' at line 24 in state 201, goto 325
Reduce #3 to parameters by token ')' at line 24 in state 325, goto 200
Reduce #1 to parameterlist by token ')' at line 24 in state 200, call paramdeflist, goto 199
Shift token ')' at line 24 in state 199, goto 296
Shift token '{' at line 25 in state 296, goto 324
Shift token IDENT = "this" at line 26 in state 324, goto 79
Reduce #1 to expression by token "->" at line 26 in state 79, call variable, goto 76
Shift token "->" at line 26 in state 76, goto 144
Reduce #1 to indirection by token IDENT = "m_x" at line 26 in state 144, call count, goto 139
Shift token IDENT = "m_x" at line 26 in state 139, goto 246
Reduce #3 to iexpression by token '=' at line 26 in state 246, call rep_operator "->", goto 77
Reduce #1 to expression by token '=' at line 26 in state 77, goto 76
Shift token '=' at line 26 in state 76, goto 145
Shift token IDENT = "x_" at line 26 in state 145, goto 79
Reduce #1 to expression by token ';' at line 26 in state 79, call variable, goto 252
Reduce #3 to expression by token ';' at line 26 in state 252, call operator "=", goto 76
Shift token ';' at line 26 in state 76, goto 141
Reduce #2 to statement by token IDENT = "m_y" at line 27 in state 141, call free_expression, goto 75
Shift token IDENT = "m_y" at line 27 in state 75, goto 79
Reduce #1 to expression by token '=' at line 27 in state 79, call variable, goto 76
Shift token '=' at line 27 in state 76, goto 145
Shift token IDENT = "y_" at line 27 in state 145, goto 79
Reduce #1 to expression by token ';' at line 27 in state 79, call variable, goto 252
Reduce #3 to expression by token ';' at line 27 in state 252, call operator "=", goto 76
Shift token ';' at line 27 in state 76, goto 141
Reduce #2 to statement by token '}' at line 28 in state 141, call free_expression, goto 75
Reduce #0 to statementlist by token '}' at line 28 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 28 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 28 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 28 in state 74, call codeblock, goto 347
Shift token '}' at line 28 in state 347, goto 363
Reduce #6 to callablebody by token "public" at line 30 in state 363, call callablebody, goto 327
Reduce #4 to operatordefinition by token "public" at line 30 in state 327, call operator_procdef {const=false}, goto 122
Reduce #1 to class_definition by token "public" at line 30 in state 122, call definition 2, goto 114
Shift token "public" at line 30 in state 114, goto 25
Reduce #1 to linkage by token "function" at line 30 in state 25, call linkage {private=false,linkage="external"}, goto 119
Shift token "function" at line 30 in state 119, goto 35
Shift token IDENT = "x" at line 30 in state 35, goto 55
Shift token IDENT = "int" at line 30 in state 55, goto 17
Reduce #1 to typename by token '(' at line 30 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 30 in state 8, call typespec "", goto 105
Shift token '(' at line 30 in state 105, goto 108
Reduce #0 to parameterlist by token ')' at line 30 in state 108, call paramdeflist, goto 199
Shift token ')' at line 30 in state 199, goto 296
Shift token "const" at line 30 in state 296, goto 323
Shift token '{' at line 31 in state 323, goto 346
Shift token "return" at line 32 in state 346, goto 94
Shift token IDENT = "m_x" at line 32 in state 94, goto 79
Reduce #1 to expression by token ';' at line 32 in state 79, call variable, goto 188
Shift token ';' at line 32 in state 188, goto 288
Reduce #3 to statement by token '}' at line 33 in state 288, call return_value, goto 75
Reduce #0 to statementlist by token '}' at line 33 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 33 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 33 in state 74, call codeblock, goto 362
Shift token '}' at line 33 in state 362, goto 373
Reduce #7 to callablebody_const by token "public" at line 35 in state 373, call callablebody, goto 197
Reduce #5 to functiondefinition by token "public" at line 35 in state 197, call funcdef {const=true}, goto 120
Reduce #1 to class_definition by token "public" at line 35 in state 120, call definition 2, goto 114
Shift token "public" at line 35 in state 114, goto 25
Reduce #1 to linkage by token "function" at line 35 in state 25, call linkage {private=false,linkage="external"}, goto 119
Shift token "function" at line 35 in state 119, goto 35
Shift token IDENT = "y" at line 35 in state 35, goto 55
Shift token IDENT = "int" at line 35 in state 55, goto 17
Reduce #1 to typename by token '(' at line 35 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 35 in state 8, call typespec "", goto 105
Shift token '(' at line 35 in state 105, goto 108
Reduce #0 to parameterlist by token ')' at line 35 in state 108, call paramdeflist, goto 199
Shift token ')' at line 35 in state 199, goto 296
Shift token "const" at line 35 in state 296, goto 323
Shift token '{' at line 36 in state 323, goto 346
Shift token "return" at line 37 in state 346, goto 94
Shift token IDENT = "this" at line 37 in state 94, goto 79
Reduce #1 to expression by token "->" at line 37 in state 79, call variable, goto 188
Shift token "->" at line 37 in state 188, goto 144
Reduce #1 to indirection by token IDENT = "m_y" at line 37 in state 144, call count, goto 139
Shift token IDENT = "m_y" at line 37 in state 139, goto 246
Reduce #3 to iexpression by token ';' at line 37 in state 246, call rep_operator "->", goto 77
Reduce #1 to expression by token ';' at line 37 in state 77, goto 188
Shift token ';' at line 37 in state 188, goto 288
Reduce #3 to statement by token '}' at line 38 in state 288, call return_value, goto 75
Reduce #0 to statementlist by token '}' at line 38 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 38 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 38 in state 74, call codeblock, goto 362
Shift token '}' at line 38 in state 362, goto 373
Reduce #7 to callablebody_const by token "function" at line 40 in state 373, call callablebody, goto 197
Reduce #5 to functiondefinition by token "function" at line 40 in state 197, call funcdef {const=true}, goto 120
Reduce #1 to class_definition by token "function" at line 40 in state 120, call definition 2, goto 114
Reduce #0 to linkage by token "function" at line 40 in state 114, call linkage {private=false,linkage="external"}, goto 119
Shift token "function" at line 40 in state 119, goto 35
Shift token IDENT = "ofs_x" at line 40 in state 35, goto 55
Shift token IDENT = "int" at line 40 in state 55, goto 17
Reduce #1 to typename by token '(' at line 40 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 40 in state 8, call typespec "", goto 105
Shift token '(' at line 40 in state 105, goto 108
Shift token IDENT = "int" at line 40 in state 108, goto 17
Reduce #1 to typename by token IDENT = "addx" at line 40 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "addx" at line 40 in state 8, call typespec "", goto 198
Shift token IDENT = "addx" at line 40 in state 198, goto 295
Reduce #2 to paramdecl by token ')' at line 40 in state 295, call paramdef, goto 201
Reduce #1 to parameters by token ')' at line 40 in state 201, goto 200
Reduce #1 to parameterlist by token ')' at line 40 in state 200, call paramdeflist, goto 199
Shift token ')' at line 40 in state 199, goto 296
Shift token "const" at line 40 in state 296, goto 323
Shift token '{' at line 41 in state 323, goto 346
Shift token "return" at line 42 in state 346, goto 94
Shift token IDENT = "m_x" at line 42 in state 94, goto 79
Reduce #1 to expression by token '+' at line 42 in state 79, call variable, goto 188
Shift token '+' at line 42 in state 188, goto 146
Shift token IDENT = "addx" at line 42 in state 146, goto 79
Reduce #1 to expression by token ';' at line 42 in state 79, call variable, goto 253
Reduce #3 to expression by token ';' at line 42 in state 253, call operator "+", goto 188
Shift token ';' at line 42 in state 188, goto 288
Reduce #3 to statement by token '}' at line 43 in state 288, call return_value, goto 75
Reduce #0 to statementlist by token '}' at line 43 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 43 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 43 in state 74, call codeblock, goto 362
Shift token '}' at line 43 in state 362, goto 373
Reduce #7 to callablebody_const by token "function" at line 45 in state 373, call callablebody, goto 197
Reduce #5 to functiondefinition by token "function" at line 45 in state 197, call funcdef {const=true}, goto 120
Reduce #1 to class_definition by token "function" at line 45 in state 120, call definition 2, goto 114
Reduce #0 to linkage by token "function" at line 45 in state 114, call linkage {private=false,linkage="external"}, goto 119
Shift token "function" at line 45 in state 119, goto 35
Shift token IDENT = "ofs_y" at line 45 in state 35, goto 55
Shift token IDENT = "int" at line 45 in state 55, goto 17
Reduce #1 to typename by token '(' at line 45 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 45 in state 8, call typespec "", goto 105
Shift token '(' at line 45 in state 105, goto 108
Shift token IDENT = "int" at line 45 in state 108, goto 17
Reduce #1 to typename by token IDENT = "addy" at line 45 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "addy" at line 45 in state 8, call typespec "", goto 198
Shift token IDENT = "addy" at line 45 in state 198, goto 295
Reduce #2 to paramdecl by token ')' at line 45 in state 295, call paramdef, goto 201
Reduce #1 to parameters by token ')' at line 45 in state 201, goto 200
Reduce #1 to parameterlist by token ')' at line 45 in state 200, call paramdeflist, goto 199
Shift token ')' at line 45 in state 199, goto 296
Shift token "const" at line 45 in state 296, goto 323
Shift token '{' at line 46 in state 323, goto 346
Shift token "return" at line 47 in state 346, goto 94
Shift token IDENT = "m_y" at line 47 in state 94, goto 79
Reduce #1 to expression by token '+' at line 47 in state 79, call variable, goto 188
Shift token '+' at line 47 in state 188, goto 146
Shift token IDENT = "addy" at line 47 in state 146, goto 79
Reduce #1 to expression by token ';' at line 47 in state 79, call variable, goto 253
Reduce #3 to expression by token ';' at line 47 in state 253, call operator "+", goto 188
Shift token ';' at line 47 in state 188, goto 288
Reduce #3 to statement by token '}' at line 48 in state 288, call return_value, goto 75
Reduce #0 to statementlist by token '}' at line 48 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 48 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 48 in state 74, call codeblock, goto 362
Shift token '}' at line 48 in state 362, goto 373
Reduce #7 to callablebody_const by token "public" at line 50 in state 373, call callablebody, goto 197
Reduce #5 to functiondefinition by token "public" at line 50 in state 197, call funcdef {const=true}, goto 120
Reduce #1 to class_definition by token "public" at line 50 in state 120, call definition 2, goto 114
Shift token "public" at line 50 in state 114, goto 25
Reduce #1 to linkage by token "function" at line 50 in state 25, call linkage {private=false,linkage="external"}, goto 119
Shift token "function" at line 50 in state 119, goto 35
Shift token IDENT = "object" at line 50 in state 35, goto 55
Shift token IDENT = "Object" at line 50 in state 55, goto 17
Reduce #1 to typename by token '(' at line 50 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 50 in state 8, call typespec "", goto 105
Shift token '(' at line 50 in state 105, goto 108
Reduce #0 to parameterlist by token ')' at line 50 in state 108, call paramdeflist, goto 199
Shift token ')' at line 50 in state 199, goto 296
Shift token "const" at line 50 in state 296, goto 323
Shift token '{' at line 51 in state 323, goto 346
Shift token "return" at line 52 in state 346, goto 94
Shift token IDENT = "this" at line 52 in state 94, goto 79
Reduce #1 to expression by token "->" at line 52 in state 79, call variable, goto 188
Shift token "->" at line 52 in state 188, goto 144
Reduce #1 to indirection by token IDENT = "Object" at line 52 in state 144, call count, goto 139
Shift token IDENT = "Object" at line 52 in state 139, goto 246
Reduce #3 to iexpression by token ';' at line 52 in state 246, call rep_operator "->", goto 77
Reduce #1 to expression by token ';' at line 52 in state 77, goto 188
Shift token ';' at line 52 in state 188, goto 288
Reduce #3 to statement by token '}' at line 53 in state 288, call return_value, goto 75
Reduce #0 to statementlist by token '}' at line 53 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 53 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 53 in state 74, call codeblock, goto 362
Shift token '}' at line 53 in state 362, goto 373
Reduce #7 to callablebody_const by token "public" at line 54 in state 373, call callablebody, goto 197
Reduce #5 to functiondefinition by token "public" at line 54 in state 197, call funcdef {const=true}, goto 120
Reduce #1 to class_definition by token "public" at line 54 in state 120, call definition 2, goto 114
Shift token "public" at line 54 in state 114, goto 25
Reduce #1 to linkage by token "function" at line 54 in state 25, call linkage {private=false,linkage="external"}, goto 119
Shift token "function" at line 54 in state 119, goto 35
Shift token IDENT = "updater" at line 54 in state 35, goto 55
Shift token IDENT = "ObjectUpdater" at line 54 in state 55, goto 17
Reduce #1 to typename by token '(' at line 54 in state 17, goto 8
Reduce #1 to typespec by token '(' at line 54 in state 8, call typespec "", goto 105
Shift token '(' at line 54 in state 105, goto 108
Reduce #0 to parameterlist by token ')' at line 54 in state 108, call paramdeflist, goto 199
Shift token ')' at line 54 in state 199, goto 296
Shift token '{' at line 55 in state 296, goto 324
Shift token "return" at line 56 in state 324, goto 94
Shift token IDENT = "this" at line 56 in state 94, goto 79
Reduce #1 to expression by token "->" at line 56 in state 79, call variable, goto 188
Shift token "->" at line 56 in state 188, goto 144
Reduce #1 to indirection by token IDENT = "ObjectUpdater" at line 56 in state 144, call count, goto 139
Shift token IDENT = "ObjectUpdater" at line 56 in state 139, goto 246
Reduce #3 to iexpression by token ';' at line 56 in state 246, call rep_operator "->", goto 77
Reduce #1 to expression by token ';' at line 56 in state 77, goto 188
Shift token ';' at line 56 in state 188, goto 288
Reduce #3 to statement by token '}' at line 57 in state 288, call return_value, goto 75
Reduce #0 to statementlist by token '}' at line 57 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 57 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 57 in state 74, call codeblock, goto 347
Shift token '}' at line 57 in state 347, goto 363
Reduce #6 to callablebody by token IDENT = "int" at line 59 in state 363, call callablebody, goto 196
Reduce #5 to functiondefinition by token IDENT = "int" at line 59 in state 196, call funcdef {const=false}, goto 120
Reduce #1 to class_definition by token IDENT = "int" at line 59 in state 120, call definition 2, goto 114
Shift token IDENT = "int" at line 59 in state 114, goto 17
Reduce #1 to typename by token IDENT = "m_x" at line 59 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "m_x" at line 59 in state 8, call typespec "", goto 9
Shift token IDENT = "m_x" at line 59 in state 9, goto 33
Reduce #2 to variabledefinition by token ';' at line 59 in state 33, call vardef, goto 123
Shift token ';' at line 59 in state 123, goto 208
Reduce #2 to class_definition by token IDENT = "int" at line 60 in state 208, call definition 1, goto 114
Shift token IDENT = "int" at line 60 in state 114, goto 17
Reduce #1 to typename by token IDENT = "m_y" at line 60 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "m_y" at line 60 in state 8, call typespec "", goto 9
Shift token IDENT = "m_y" at line 60 in state 9, goto 33
Reduce #2 to variabledefinition by token ';' at line 60 in state 33, call vardef, goto 123
Shift token ';' at line 60 in state 123, goto 208
Reduce #2 to class_definition by token '}' at line 61 in state 208, call definition 1, goto 114
Reduce #0 to class_definitionlist by token '}' at line 61 in state 114, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 61 in state 204, goto 303
Shift token '}' at line 61 in state 303, goto 331
Reduce #7 to classdefinition by token "class" at line 63 in state 331, call classdef, goto 13
Reduce #1 to free_definition by token "class" at line 63 in state 13, call definition 1, goto 7
Shift token "class" at line 63 in state 7, goto 20
Shift token IDENT = "Line" at line 63 in state 20, goto 43
Shift token ':' at line 63 in state 43, goto 65
Shift token IDENT = "Point" at line 63 in state 65, goto 17
Reduce #1 to typename by token '{' at line 64 in state 17, goto 45
Reduce #1 to typepath by token '{' at line 64 in state 45, call typespec "", goto 125
Reduce #1 to inheritlist by token '{' at line 64 in state 125, call inheritdef 1, goto 126
Shift token '{' at line 64 in state 126, goto 211
Shift token "public" at line 65 in state 211, goto 25
Reduce #1 to linkage by token "constructor" at line 65 in state 25, call linkage {private=false,linkage="external"}, goto 119
Shift token "constructor" at line 65 in state 119, goto 207
Shift token '(' at line 65 in state 207, goto 300
Shift token IDENT = "int" at line 65 in state 300, goto 17
Reduce #1 to typename by token IDENT = "x_" at line 65 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "x_" at line 65 in state 8, call typespec "", goto 198
Shift token IDENT = "x_" at line 65 in state 198, goto 295
Reduce #2 to paramdecl by token ',' at line 65 in state 295, call paramdef, goto 201
Shift token ',' at line 65 in state 201, goto 297
Shift token IDENT = "int" at line 65 in state 297, goto 17
Reduce #1 to typename by token IDENT = "y_" at line 65 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "y_" at line 65 in state 8, call typespec "", goto 198
Shift token IDENT = "y_" at line 65 in state 198, goto 295
Reduce #2 to paramdecl by token ')' at line 65 in state 295, call paramdef, goto 201
Reduce #1 to parameters by token ')' at line 65 in state 201, goto 325
Reduce #3 to parameters by token ')' at line 65 in state 325, goto 200
Reduce #1 to parameterlist by token ')' at line 65 in state 200, call paramdeflist, goto 329
Shift token ')' at line 65 in state 329, goto 350
Shift token '{' at line 66 in state 350, goto 324
Shift token IDENT = "this" at line 67 in state 324, goto 79
Reduce #1 to expression by token "->" at line 67 in state 79, call variable, goto 76
Shift token "->" at line 67 in state 76, goto 144
Reduce #1 to indirection by token IDENT = "Point" at line 67 in state 144, call count, goto 139
Shift token IDENT = "Point" at line 67 in state 139, goto 246
Reduce #3 to iexpression by token '=' at line 67 in state 246, call rep_operator "->", goto 77
Reduce #1 to expression by token '=' at line 67 in state 77, goto 76
Shift token '=' at line 67 in state 76, goto 145
Shift token '{' at line 67 in state 145, goto 103
Shift token IDENT = "x_" at line 67 in state 103, goto 79
Reduce #1 to expression by token ',' at line 67 in state 79, call variable, goto 194
Shift token ',' at line 67 in state 194, goto 285
Shift token IDENT = "y_" at line 67 in state 285, goto 79
Reduce #1 to expression by token '}' at line 67 in state 79, call variable, goto 194
Reduce #1 to expressionlist by token '}' at line 67 in state 194, goto 317
Reduce #3 to expressionlist by token '}' at line 67 in state 317, goto 180
Shift token '}' at line 67 in state 180, goto 286
Reduce #3 to expression by token ';' at line 67 in state 286, call structure, goto 252
Reduce #3 to expression by token ';' at line 67 in state 252, call operator "=", goto 76
Shift token ';' at line 67 in state 76, goto 141
Reduce #2 to statement by token '}' at line 68 in state 141, call free_expression, goto 75
Reduce #0 to statementlist by token '}' at line 68 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 68 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 68 in state 74, call codeblock, goto 347
Shift token '}' at line 68 in state 347, goto 363
Reduce #6 to callablebody by token "public" at line 70 in state 363, call callablebody, goto 299
Reduce #3 to constructordefinition by token "public" at line 70 in state 299, call constructordef, goto 121
Reduce #1 to class_definition by token "public" at line 70 in state 121, call definition 2, goto 114
Shift token "public" at line 70 in state 114, goto 25
Reduce #1 to linkage by token "procedure" at line 70 in state 25, call linkage {private=false,linkage="external"}, goto 119
Shift token "procedure" at line 70 in state 119, goto 36
Shift token IDENT = "move" at line 70 in state 36, goto 56
Shift token '(' at line 70 in state 56, goto 108
Shift token IDENT = "int" at line 70 in state 108, goto 17
Reduce #1 to typename by token IDENT = "x_" at line 70 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "x_" at line 70 in state 8, call typespec "", goto 198
Shift token IDENT = "x_" at line 70 in state 198, goto 295
Reduce #2 to paramdecl by token ',' at line 70 in state 295, call paramdef, goto 201
Shift token ',' at line 70 in state 201, goto 297
Shift token IDENT = "int" at line 70 in state 297, goto 17
Reduce #1 to typename by token IDENT = "y_" at line 70 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "y_" at line 70 in state 8, call typespec "", goto 198
Shift token IDENT = "y_" at line 70 in state 198, goto 295
Reduce #2 to paramdecl by token ')' at line 70 in state 295, call paramdef, goto 201
Reduce #1 to parameters by token ')' at line 70 in state 201, goto 325
Reduce #3 to parameters by token ')' at line 70 in state 325, goto 200
Reduce #1 to parameterlist by token ')' at line 70 in state 200, call paramdeflist, goto 199
Shift token ')' at line 70 in state 199, goto 296
Shift token '{' at line 71 in state 296, goto 324
Shift token IDENT = "this" at line 72 in state 324, goto 79
Reduce #1 to expression by token "->" at line 72 in state 79, call variable, goto 76
Shift token "->" at line 72 in state 76, goto 144
Reduce #1 to indirection by token IDENT = "Point" at line 72 in state 144, call count, goto 139
Shift token IDENT = "Point" at line 72 in state 139, goto 246
Reduce #3 to iexpression by token '=' at line 72 in state 246, call rep_operator "->", goto 77
Reduce #1 to expression by token '=' at line 72 in state 77, goto 76
Shift token '=' at line 72 in state 76, goto 145
Shift token '{' at line 72 in state 145, goto 103
Shift token IDENT = "x_" at line 72 in state 103, goto 79
Reduce #1 to expression by token ',' at line 72 in state 79, call variable, goto 194
Shift token ',' at line 72 in state 194, goto 285
Shift token IDENT = "y_" at line 72 in state 285, goto 79
Reduce #1 to expression by token '}' at line 72 in state 79, call variable, goto 194
Reduce #1 to expressionlist by token '}' at line 72 in state 194, goto 317
Reduce #3 to expressionlist by token '}' at line 72 in state 317, goto 180
Shift token '}' at line 72 in state 180, goto 286
Reduce #3 to expression by token ';' at line 72 in state 286, call structure, goto 252
Reduce #3 to expression by token ';' at line 72 in state 252, call operator "=", goto 76
Shift token ';' at line 72 in state 76, goto 141
Reduce #2 to statement by token '}' at line 73 in state 141, call free_expression, goto 75
Reduce #0 to statementlist by token '}' at line 73 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 73 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 73 in state 74, call codeblock, goto 347
Shift token '}' at line 73 in state 347, goto 363
Reduce #6 to callablebody by token '}' at line 74 in state 363, call callablebody, goto 106
Reduce #4 to functiondefinition by token '}' at line 74 in state 106, call procdef {const=false}, goto 120
Reduce #1 to class_definition by token '}' at line 74 in state 120, call definition 2, goto 114
Reduce #0 to class_definitionlist by token '}' at line 74 in state 114, goto 204
Reduce #2 to class_definitionlist by token '}' at line 74 in state 204, goto 204
Reduce #2 to class_definitionlist by token '}' at line 74 in state 204, goto 303
Shift token '}' at line 74 in state 303, goto 331
Reduce #7 to classdefinition by token "main" at line 76 in state 331, call classdef, goto 13
Reduce #1 to free_definition by token "main" at line 76 in state 13, call definition 1, goto 7
Reduce #0 to free_definitionlist by token "main" at line 76 in state 7, goto 30
Reduce #2 to free_definitionlist by token "main" at line 76 in state 30, goto 30
Reduce #2 to free_definitionlist by token "main" at line 76 in state 30, goto 30
Reduce #2 to free_definitionlist by token "main" at line 76 in state 30, goto 30
Reduce #2 to free_definitionlist by token "main" at line 76 in state 30, goto 5
Shift token "main" at line 76 in state 5, goto 29
Shift token '{' at line 76 in state 29, goto 50
Shift token "var" at line 77 in state 50, goto 93
Shift token IDENT = "float" at line 77 in state 93, goto 17
Reduce #1 to typename by token IDENT = "x" at line 77 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "x" at line 77 in state 8, call typespec "", goto 9
Shift token IDENT = "x" at line 77 in state 9, goto 33
Shift token '=' at line 77 in state 33, goto 53
Shift token FLOAT = "1.23" at line 77 in state 53, goto 84
Reduce #1 to expression by token ';' at line 77 in state 84, call constant "constexpr float", goto 102
Reduce #4 to variabledefinition by token ';' at line 77 in state 102, call vardef_assign, goto 187
Shift token ';' at line 77 in state 187, goto 287
Reduce #3 to statement by token "var" at line 78 in state 287, call definition, goto 75
Shift token "var" at line 78 in state 75, goto 93
Shift token IDENT = "Line" at line 78 in state 93, goto 17
Reduce #1 to typename by token IDENT = "ab" at line 78 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "ab" at line 78 in state 8, call typespec "", goto 9
Shift token IDENT = "ab" at line 78 in state 9, goto 33
Shift token '=' at line 78 in state 33, goto 53
Shift token '{' at line 78 in state 53, goto 103
Shift token FLOAT = "1.23" at line 78 in state 103, goto 84
Reduce #1 to expression by token ',' at line 78 in state 84, call constant "constexpr float", goto 194
Shift token ',' at line 78 in state 194, goto 285
Shift token FLOAT = "4.23" at line 78 in state 285, goto 84
Reduce #1 to expression by token '}' at line 78 in state 84, call constant "constexpr float", goto 194
Reduce #1 to expressionlist by token '}' at line 78 in state 194, goto 317
Reduce #3 to expressionlist by token '}' at line 78 in state 317, goto 180
Shift token '}' at line 78 in state 180, goto 286
Reduce #3 to expression by token ';' at line 78 in state 286, call structure, goto 102
Reduce #4 to variabledefinition by token ';' at line 78 in state 102, call vardef_assign, goto 187
Shift token ';' at line 78 in state 187, goto 287
Reduce #3 to statement by token "var" at line 79 in state 287, call definition, goto 75
Shift token "var" at line 79 in state 75, goto 93
Shift token IDENT = "Object" at line 79 in state 93, goto 17
Reduce #1 to typename by token IDENT = "obj" at line 79 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "obj" at line 79 in state 8, call typespec "", goto 9
Shift token IDENT = "obj" at line 79 in state 9, goto 33
Shift token '=' at line 79 in state 33, goto 53
Shift token IDENT = "ab" at line 79 in state 53, goto 79
Reduce #1 to expression by token '.' at line 79 in state 79, call variable, goto 102
Shift token '.' at line 79 in state 102, goto 175
Shift token IDENT = "object" at line 79 in state 175, goto 282
Reduce #3 to expression by token '(' at line 79 in state 282, call member, goto 102
Shift token '(' at line 79 in state 102, goto 140
Shift token ')' at line 79 in state 140, goto 248
Reduce #3 to expression by token ';' at line 79 in state 248, call operator "()", goto 102
Reduce #4 to variabledefinition by token ';' at line 79 in state 102, call vardef_assign, goto 187
Shift token ';' at line 79 in state 187, goto 287
Reduce #3 to statement by token IDENT = "printf" at line 80 in state 287, call definition, goto 75
Shift token IDENT = "printf" at line 80 in state 75, goto 79
Reduce #1 to expression by token '(' at line 80 in state 79, call variable, goto 76
Shift token '(' at line 80 in state 76, goto 140
Shift token DQSTRING = "RESULT[1] x = %d\n" at line 80 in state 140, goto 80
Reduce #1 to expression by token ',' at line 80 in state 80, call string_constant "constexpr float", goto 194
Shift token ',' at line 80 in state 194, goto 285
Shift token IDENT = "obj" at line 80 in state 285, goto 79
Reduce #1 to expression by token '.' at line 80 in state 79, call variable, goto 194
Shift token '.' at line 80 in state 194, goto 175
Shift token IDENT = "x" at line 80 in state 175, goto 282
Reduce #3 to expression by token '(' at line 80 in state 282, call member, goto 194
Shift token '(' at line 80 in state 194, goto 140
Shift token ')' at line 80 in state 140, goto 248
Reduce #3 to expression by token ')' at line 80 in state 248, call operator "()", goto 194
Reduce #1 to expressionlist by token ')' at line 80 in state 194, goto 317
Reduce #3 to expressionlist by token ')' at line 80 in state 317, goto 247
Shift token ')' at line 80 in state 247, goto 315
Reduce #4 to expression by token ';' at line 80 in state 315, call operator "()", goto 76
Shift token ';' at line 80 in state 76, goto 141
Reduce #2 to statement by token IDENT = "printf" at line 81 in state 141, call free_expression, goto 75
Shift token IDENT = "printf" at line 81 in state 75, goto 79
Reduce #1 to expression by token '(' at line 81 in state 79, call variable, goto 76
Shift token '(' at line 81 in state 76, goto 140
Shift token DQSTRING = "RESULT[1] y = %d\n" at line 81 in state 140, goto 80
Reduce #1 to expression by token ',' at line 81 in state 80, call string_constant "constexpr float", goto 194
Shift token ',' at line 81 in state 194, goto 285
Shift token IDENT = "obj" at line 81 in state 285, goto 79
Reduce #1 to expression by token '.' at line 81 in state 79, call variable, goto 194
Shift token '.' at line 81 in state 194, goto 175
Shift token IDENT = "y" at line 81 in state 175, goto 282
Reduce #3 to expression by token '(' at line 81 in state 282, call member, goto 194
Shift token '(' at line 81 in state 194, goto 140
Shift token ')' at line 81 in state 140, goto 248
Reduce #3 to expression by token ')' at line 81 in state 248, call operator "()", goto 194
Reduce #1 to expressionlist by token ')' at line 81 in state 194, goto 317
Reduce #3 to expressionlist by token ')' at line 81 in state 317, goto 247
Shift token ')' at line 81 in state 247, goto 315
Reduce #4 to expression by token ';' at line 81 in state 315, call operator "()", goto 76
Shift token ';' at line 81 in state 76, goto 141
Reduce #2 to statement by token "var" at line 82 in state 141, call free_expression, goto 75
Shift token "var" at line 82 in state 75, goto 93
Shift token IDENT = "ObjectUpdater" at line 82 in state 93, goto 17
Reduce #1 to typename by token IDENT = "updater" at line 82 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "updater" at line 82 in state 8, call typespec "", goto 9
Shift token IDENT = "updater" at line 82 in state 9, goto 33
Shift token '=' at line 82 in state 33, goto 53
Shift token IDENT = "ab" at line 82 in state 53, goto 79
Reduce #1 to expression by token '.' at line 82 in state 79, call variable, goto 102
Shift token '.' at line 82 in state 102, goto 175
Shift token IDENT = "updater" at line 82 in state 175, goto 282
Reduce #3 to expression by token '(' at line 82 in state 282, call member, goto 102
Shift token '(' at line 82 in state 102, goto 140
Shift token ')' at line 82 in state 140, goto 248
Reduce #3 to expression by token ';' at line 82 in state 248, call operator "()", goto 102
Reduce #4 to variabledefinition by token ';' at line 82 in state 102, call vardef_assign, goto 187
Shift token ';' at line 82 in state 187, goto 287
Reduce #3 to statement by token IDENT = "updater" at line 83 in state 287, call definition, goto 75
Shift token IDENT = "updater" at line 83 in state 75, goto 79
Reduce #1 to expression by token '=' at line 83 in state 79, call variable, goto 76
Shift token '=' at line 83 in state 76, goto 145
Shift token '{' at line 83 in state 145, goto 103
Shift token CARDINAL = "31" at line 83 in state 103, goto 82
Reduce #1 to expression by token ',' at line 83 in state 82, call constant "constexpr uint", goto 194
Shift token ',' at line 83 in state 194, goto 285
Shift token CARDINAL = "411" at line 83 in state 285, goto 82
Reduce #1 to expression by token '}' at line 83 in state 82, call constant "constexpr uint", goto 194
Reduce #1 to expressionlist by token '}' at line 83 in state 194, goto 317
Reduce #3 to expressionlist by token '}' at line 83 in state 317, goto 180
Shift token '}' at line 83 in state 180, goto 286
Reduce #3 to expression by token ';' at line 83 in state 286, call structure, goto 252
Reduce #3 to expression by token ';' at line 83 in state 252, call operator "=", goto 76
Shift token ';' at line 83 in state 76, goto 141
Reduce #2 to statement by token IDENT = "printf" at line 84 in state 141, call free_expression, goto 75
Shift token IDENT = "printf" at line 84 in state 75, goto 79
Reduce #1 to expression by token '(' at line 84 in state 79, call variable, goto 76
Shift token '(' at line 84 in state 76, goto 140
Shift token DQSTRING = "RESULT[2] x = %d\n" at line 84 in state 140, goto 80
Reduce #1 to expression by token ',' at line 84 in state 80, call string_constant "constexpr float", goto 194
Shift token ',' at line 84 in state 194, goto 285
Shift token IDENT = "obj" at line 84 in state 285, goto 79
Reduce #1 to expression by token '.' at line 84 in state 79, call variable, goto 194
Shift token '.' at line 84 in state 194, goto 175
Shift token IDENT = "x" at line 84 in state 175, goto 282
Reduce #3 to expression by token '(' at line 84 in state 282, call member, goto 194
Shift token '(' at line 84 in state 194, goto 140
Shift token ')' at line 84 in state 140, goto 248
Reduce #3 to expression by token ')' at line 84 in state 248, call operator "()", goto 194
Reduce #1 to expressionlist by token ')' at line 84 in state 194, goto 317
Reduce #3 to expressionlist by token ')' at line 84 in state 317, goto 247
Shift token ')' at line 84 in state 247, goto 315
Reduce #4 to expression by token ';' at line 84 in state 315, call operator "()", goto 76
Shift token ';' at line 84 in state 76, goto 141
Reduce #2 to statement by token IDENT = "printf" at line 85 in state 141, call free_expression, goto 75
Shift token IDENT = "printf" at line 85 in state 75, goto 79
Reduce #1 to expression by token '(' at line 85 in state 79, call variable, goto 76
Shift token '(' at line 85 in state 76, goto 140
Shift token DQSTRING = "RESULT[2] y = %d\n" at line 85 in state 140, goto 80
Reduce #1 to expression by token ',' at line 85 in state 80, call string_constant "constexpr float", goto 194
Shift token ',' at line 85 in state 194, goto 285
Shift token IDENT = "obj" at line 85 in state 285, goto 79
Reduce #1 to expression by token '.' at line 85 in state 79, call variable, goto 194
Shift token '.' at line 85 in state 194, goto 175
Shift token IDENT = "y" at line 85 in state 175, goto 282
Reduce #3 to expression by token '(' at line 85 in state 282, call member, goto 194
Shift token '(' at line 85 in state 194, goto 140
Shift token ')' at line 85 in state 140, goto 248
Reduce #3 to expression by token ')' at line 85 in state 248, call operator "()", goto 194
Reduce #1 to expressionlist by token ')' at line 85 in state 194, goto 317
Reduce #3 to expressionlist by token ')' at line 85 in state 317, goto 247
Shift token ')' at line 85 in state 247, goto 315
Reduce #4 to expression by token ';' at line 85 in state 315, call operator "()", goto 76
Shift token ';' at line 85 in state 76, goto 141
Reduce #2 to statement by token IDENT = "updater" at line 86 in state 141, call free_expression, goto 75
Shift token IDENT = "updater" at line 86 in state 75, goto 79
Reduce #1 to expression by token '=' at line 86 in state 79, call variable, goto 76
Shift token '=' at line 86 in state 76, goto 145
Shift token '{' at line 86 in state 145, goto 103
Shift token CARDINAL = "71" at line 86 in state 103, goto 82
Reduce #1 to expression by token ',' at line 86 in state 82, call constant "constexpr uint", goto 194
Shift token ',' at line 86 in state 194, goto 285
Shift token CARDINAL = "511" at line 86 in state 285, goto 82
Reduce #1 to expression by token '}' at line 86 in state 82, call constant "constexpr uint", goto 194
Reduce #1 to expressionlist by token '}' at line 86 in state 194, goto 317
Reduce #3 to expressionlist by token '}' at line 86 in state 317, goto 180
Shift token '}' at line 86 in state 180, goto 286
Reduce #3 to expression by token ';' at line 86 in state 286, call structure, goto 252
Reduce #3 to expression by token ';' at line 86 in state 252, call operator "=", goto 76
Shift token ';' at line 86 in state 76, goto 141
Reduce #2 to statement by token IDENT = "printf" at line 87 in state 141, call free_expression, goto 75
Shift token IDENT = "printf" at line 87 in state 75, goto 79
Reduce #1 to expression by token '(' at line 87 in state 79, call variable, goto 76
Shift token '(' at line 87 in state 76, goto 140
Shift token DQSTRING = "RESULT[3] x = %d\n" at line 87 in state 140, goto 80
Reduce #1 to expression by token ',' at line 87 in state 80, call string_constant "constexpr float", goto 194
Shift token ',' at line 87 in state 194, goto 285
Shift token IDENT = "obj" at line 87 in state 285, goto 79
Reduce #1 to expression by token '.' at line 87 in state 79, call variable, goto 194
Shift token '.' at line 87 in state 194, goto 175
Shift token IDENT = "ofs_x" at line 87 in state 175, goto 282
Reduce #3 to expression by token '(' at line 87 in state 282, call member, goto 194
Shift token '(' at line 87 in state 194, goto 140
Shift token INTEGER = "-13" at line 87 in state 140, goto 83
Reduce #1 to expression by token ')' at line 87 in state 83, call constant "constexpr int", goto 194
Reduce #1 to expressionlist by token ')' at line 87 in state 194, goto 247
Shift token ')' at line 87 in state 247, goto 315
Reduce #4 to expression by token ')' at line 87 in state 315, call operator "()", goto 194
Reduce #1 to expressionlist by token ')' at line 87 in state 194, goto 317
Reduce #3 to expressionlist by token ')' at line 87 in state 317, goto 247
Shift token ')' at line 87 in state 247, goto 315
Reduce #4 to expression by token ';' at line 87 in state 315, call operator "()", goto 76
Shift token ';' at line 87 in state 76, goto 141
Reduce #2 to statement by token IDENT = "printf" at line 88 in state 141, call free_expression, goto 75
Shift token IDENT = "printf" at line 88 in state 75, goto 79
Reduce #1 to expression by token '(' at line 88 in state 79, call variable, goto 76
Shift token '(' at line 88 in state 76, goto 140
Shift token DQSTRING = "RESULT[3] y = %d\n" at line 88 in state 140, goto 80
Reduce #1 to expression by token ',' at line 88 in state 80, call string_constant "constexpr float", goto 194
Shift token ',' at line 88 in state 194, goto 285
Shift token IDENT = "obj" at line 88 in state 285, goto 79
Reduce #1 to expression by token '.' at line 88 in state 79, call variable, goto 194
Shift token '.' at line 88 in state 194, goto 175
Shift token IDENT = "ofs_y" at line 88 in state 175, goto 282
Reduce #3 to expression by token '(' at line 88 in state 282, call member, goto 194
Shift token '(' at line 88 in state 194, goto 140
Shift token CARDINAL = "1" at line 88 in state 140, goto 82
Reduce #1 to expression by token ')' at line 88 in state 82, call constant "constexpr uint", goto 194
Reduce #1 to expressionlist by token ')' at line 88 in state 194, goto 247
Shift token ')' at line 88 in state 247, goto 315
Reduce #4 to expression by token ')' at line 88 in state 315, call operator "()", goto 194
Reduce #1 to expressionlist by token ')' at line 88 in state 194, goto 317
Reduce #3 to expressionlist by token ')' at line 88 in state 317, goto 247
Shift token ')' at line 88 in state 247, goto 315
Reduce #4 to expression by token ';' at line 88 in state 315, call operator "()", goto 76
Shift token ';' at line 88 in state 76, goto 141
Reduce #2 to statement by token "var" at line 89 in state 141, call free_expression, goto 75
Shift token "var" at line 89 in state 75, goto 93
Shift token IDENT = "ObjectUpdater" at line 89 in state 93, goto 17
Reduce #1 to typename by token IDENT = "updater2" at line 89 in state 17, goto 8
Reduce #1 to typespec by token IDENT = "updater2" at line 89 in state 8, call typespec "", goto 9
Shift token IDENT = "updater2" at line 89 in state 9, goto 33
Shift token '=' at line 89 in state 33, goto 53
Shift token IDENT = "updater" at line 89 in state 53, goto 79
Reduce #1 to expression by token ';' at line 89 in state 79, call variable, goto 102
Reduce #4 to variabledefinition by token ';' at line 89 in state 102, call vardef_assign, goto 187
Shift token ';' at line 89 in state 187, goto 287
Reduce #3 to statement by token IDENT = "updater2" at line 90 in state 287, call definition, goto 75
Shift token IDENT = "updater2" at line 90 in state 75, goto 79
Reduce #1 to expression by token '=' at line 90 in state 79, call variable, goto 76
Shift token '=' at line 90 in state 76, goto 145
Shift token '{' at line 90 in state 145, goto 103
Shift token CARDINAL = "32" at line 90 in state 103, goto 82
Reduce #1 to expression by token ',' at line 90 in state 82, call constant "constexpr uint", goto 194
Shift token ',' at line 90 in state 194, goto 285
Shift token CARDINAL = "412" at line 90 in state 285, goto 82
Reduce #1 to expression by token '}' at line 90 in state 82, call constant "constexpr uint", goto 194
Reduce #1 to expressionlist by token '}' at line 90 in state 194, goto 317
Reduce #3 to expressionlist by token '}' at line 90 in state 317, goto 180
Shift token '}' at line 90 in state 180, goto 286
Reduce #3 to expression by token ';' at line 90 in state 286, call structure, goto 252
Reduce #3 to expression by token ';' at line 90 in state 252, call operator "=", goto 76
Shift token ';' at line 90 in state 76, goto 141
Reduce #2 to statement by token IDENT = "printf" at line 91 in state 141, call free_expression, goto 75
Shift token IDENT = "printf" at line 91 in state 75, goto 79
Reduce #1 to expression by token '(' at line 91 in state 79, call variable, goto 76
Shift token '(' at line 91 in state 76, goto 140
Shift token DQSTRING = "RESULT[4] x = %d\n" at line 91 in state 140, goto 80
Reduce #1 to expression by token ',' at line 91 in state 80, call string_constant "constexpr float", goto 194
Shift token ',' at line 91 in state 194, goto 285
Shift token IDENT = "obj" at line 91 in state 285, goto 79
Reduce #1 to expression by token '.' at line 91 in state 79, call variable, goto 194
Shift token '.' at line 91 in state 194, goto 175
Shift token IDENT = "ofs_x" at line 91 in state 175, goto 282
Reduce #3 to expression by token '(' at line 91 in state 282, call member, goto 194
Shift token '(' at line 91 in state 194, goto 140
Shift token INTEGER = "-11" at line 91 in state 140, goto 83
Reduce #1 to expression by token ')' at line 91 in state 83, call constant "constexpr int", goto 194
Reduce #1 to expressionlist by token ')' at line 91 in state 194, goto 247
Shift token ')' at line 91 in state 247, goto 315
Reduce #4 to expression by token ')' at line 91 in state 315, call operator "()", goto 194
Reduce #1 to expressionlist by token ')' at line 91 in state 194, goto 317
Reduce #3 to expressionlist by token ')' at line 91 in state 317, goto 247
Shift token ')' at line 91 in state 247, goto 315
Reduce #4 to expression by token ';' at line 91 in state 315, call operator "()", goto 76
Shift token ';' at line 91 in state 76, goto 141
Reduce #2 to statement by token IDENT = "printf" at line 92 in state 141, call free_expression, goto 75
Shift token IDENT = "printf" at line 92 in state 75, goto 79
Reduce #1 to expression by token '(' at line 92 in state 79, call variable, goto 76
Shift token '(' at line 92 in state 76, goto 140
Shift token DQSTRING = "RESULT[4] y = %d\n" at line 92 in state 140, goto 80
Reduce #1 to expression by token ',' at line 92 in state 80, call string_constant "constexpr float", goto 194
Shift token ',' at line 92 in state 194, goto 285
Shift token IDENT = "obj" at line 92 in state 285, goto 79
Reduce #1 to expression by token '.' at line 92 in state 79, call variable, goto 194
Shift token '.' at line 92 in state 194, goto 175
Shift token IDENT = "y" at line 92 in state 175, goto 282
Reduce #3 to expression by token '(' at line 92 in state 282, call member, goto 194
Shift token '(' at line 92 in state 194, goto 140
Shift token ')' at line 92 in state 140, goto 248
Reduce #3 to expression by token ')' at line 92 in state 248, call operator "()", goto 194
Reduce #1 to expressionlist by token ')' at line 92 in state 194, goto 317
Reduce #3 to expressionlist by token ')' at line 92 in state 317, goto 247
Shift token ')' at line 92 in state 247, goto 315
Reduce #4 to expression by token ';' at line 92 in state 315, call operator "()", goto 76
Shift token ';' at line 92 in state 76, goto 141
Reduce #2 to statement by token "return" at line 93 in state 141, call free_expression, goto 75
Shift token "return" at line 93 in state 75, goto 94
Shift token CARDINAL = "0" at line 93 in state 94, goto 82
Reduce #1 to expression by token ';' at line 93 in state 82, call constant "constexpr uint", goto 188
Shift token ';' at line 93 in state 188, goto 288
Reduce #3 to statement by token '}' at line 94 in state 288, call return_value, goto 75
Reduce #0 to statementlist by token '}' at line 94 in state 75, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 138
Reduce #2 to statementlist by token '}' at line 94 in state 138, goto 74
Reduce #1 to codeblock by token '}' at line 94 in state 74, call codeblock, goto 73
Shift token '}' at line 94 in state 73, goto 137
Accept
Calling Lua function: program
Lua call result [1]
{
  arg = {
    {
      arg = {
        {
          line = 1,
          name = "DQSTRING",
          value = "C"},
        {
          line = 1,
          name = "IDENT",
          value = "printf"},
        {
          arg = {
            {
              arg = {
                {
                  arg = {
                    {
                      line = 1,
                      name = "IDENT",
                      value = "byte"}},
                  call = {
                    name = "typespec const^",
                    obj = "const^",
                    proc = <function>},
                  line = 1,
                  step = 0},
                {
                  line = 1,
                  name = "IDENT",
                  value = "fmt"}},
              call = {
                name = "extern_paramdef",
                proc = <function>},
              line = 1,
              step = 0}},
          call = {
            name = "extern_paramdeflist",
            proc = <function>},
          line = 1,
          step = 0}},
      call = {
        name = "extern_procdef_vararg",
        proc = <function>},
      line = 1,
      step = 0},
    {
      arg = {
        {
          arg = {
            {
              line = 3,
              name = "IDENT",
              value = "Object"},
            {
              arg = {
                {
                  line = 5,
                  name = "IDENT",
                  value = "x"},
                {
                  arg = {
                    {
                      line = 5,
                      name = "IDENT",
                      value = "int"}},
                  call = {
                    name = "typespec ",
                    obj = "",
                    proc = <function>},
                  line = 5,
                  step = 0},
                {
                  arg = {},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 5,
                  step = 0}},
              call = {
                name = "interface_funcdef {const=true}",
                obj = {
                  const = true},
                proc = <function>},
              line = 5,
              step = 0},
            {
              arg = {
                {
                  line = 6,
                  name = "IDENT",
                  value = "y"},
                {
                  arg = {
                    {
                      line = 6,
                      name = "IDENT",
                      value = "int"}},
                  call = {
                    name = "typespec ",
                    obj = "",
                    proc = <function>},
                  line = 6,
                  step = 0},
                {
                  arg = {},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 6,
                  step = 0}},
              call = {
                name = "interface_funcdef {const=true}",
                obj = {
                  const = true},
                proc = <function>},
              line = 6,
              step = 0},
            {
              arg = {
                {
                  line = 7,
                  name = "IDENT",
                  value = "ofs_x"},
                {
                  arg = {
                    {
                      line = 7,
                      name = "IDENT",
                      value = "int"}},
                  call = {
                    name = "typespec ",
                    obj = "",
                    proc = <function>},
                  line = 7,
                  step = 0},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 7,
                              name = "IDENT",
                              value = "int"}},
                          call = {
                            name = "typespec ",
                            obj = "",
                            proc = <function>},
                          line = 7,
                          step = 0},
                        {
                          line = 7,
                          name = "IDENT",
                          value = "addx"}},
                      call = {
                        name = "extern_paramdef",
                        proc = <function>},
                      line = 7,
                      step = 0}},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 7,
                  step = 0}},
              call = {
                name = "interface_funcdef {const=true}",
                obj = {
                  const = true},
                proc = <function>},
              line = 7,
              step = 0},
            {
              arg = {
                {
                  line = 8,
                  name = "IDENT",
                  value = "ofs_y"},
                {
                  arg = {
                    {
                      line = 8,
                      name = "IDENT",
                      value = "int"}},
                  call = {
                    name = "typespec ",
                    obj = "",
                    proc = <function>},
                  line = 8,
                  step = 0},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 8,
                              name = "IDENT",
                              value = "int"}},
                          call = {
                            name = "typespec ",
                            obj = "",
                            proc = <function>},
                          line = 8,
                          step = 0},
                        {
                          line = 8,
                          name = "IDENT",
                          value = "addy"}},
                      call = {
                        name = "extern_paramdef",
                        proc = <function>},
                      line = 8,
                      step = 0}},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 8,
                  step = 0}},
              call = {
                name = "interface_funcdef {const=true}",
                obj = {
                  const = true},
                proc = <function>},
              line = 8,
              step = 0}},
          call = {
            name = "interfacedef",
            proc = <function>},
          line = 8,
          step = 1}},
      call = {
        name = "definition 1",
        obj = 1,
        proc = <function>},
      line = 8,
      step = 1},
    {
      arg = {
        {
          arg = {
            {
              line = 11,
              name = "IDENT",
              value = "ObjectUpdater"},
            {
              arg = {
                {
                  arg = {},
                  call = {
                    name = "operatordecl {name="=",symbol="assign"}",
                    obj = {
                      name = "=",
                      symbol = "assign"},
                    proc = <function>},
                  line = 11,
                  step = 1},
                {
                  arg = {
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 13,
                              name = "IDENT",
                              value = "int"}},
                          call = {
                            name = "typespec ",
                            obj = "",
                            proc = <function>},
                          line = 13,
                          step = 1},
                        {
                          line = 13,
                          name = "IDENT",
                          value = "x_"},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 13,
                                  name = "IDENT",
                                  value = "int"}},
                              call = {
                                name = "typespec ",
                                obj = "",
                                proc = <function>},
                              line = 13,
                              step = 1},
                            {
                              line = 13,
                              name = "IDENT",
                              value = "y_"}},
                          call = {
                            name = "extern_paramdef",
                            proc = <function>},
                          line = 13,
                          step = 1}},
                      call = {
                        name = "extern_paramdef",
                        proc = <function>},
                      line = 13,
                      step = 1}},
                  call = {
                    name = "extern_paramdeflist",
                    proc = <function>},
                  line = 13,
                  step = 1}},
              call = {
                name = "interface_operator_procdef {const=false}",
                obj = {
                  const = false},
                proc = <function>},
              line = 13,
              step = 1}},
          call = {
            name = "interfacedef",
            proc = <function>},
          line = 13,
          step = 2}},
      call = {
        name = "definition 1",
        obj = 1,
        proc = <function>},
      line = 13,
      step = 2},
    {
      arg = {
        {
          arg = {
            {
              line = 16,
              name = "IDENT",
              value = "Point"},
            {
              arg = {
                {
                  arg = {
                    {
                      line = 16,
                      name = "IDENT",
                      value = "Object"}},
                  call = {
                    name = "typespec ",
                    obj = "",
                    proc = <function>},
                  line = 16,
                  step = 2},
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 16,
                          name = "IDENT",
                          value = "ObjectUpdater"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 16,
                      step = 2}},
                  call = {
                    name = "inheritdef 1",
                    obj = 1,
                    proc = <function>},
                  line = 16,
                  step = 3}},
              call = {
                name = "inheritdef 1",
                obj = 1,
                proc = <function>},
              line = 16,
              step = 4},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 16,
                      step = 4},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 18,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 18,
                                  step = 4},
                                {
                                  line = 18,
                                  name = "IDENT",
                                  value = "x_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 18,
                              step = 4},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 18,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 18,
                                  step = 4},
                                {
                                  line = 18,
                                  name = "IDENT",
                                  value = "y_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 18,
                              step = 4}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 18,
                          step = 4},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 20,
                                          name = "IDENT",
                                          value = "m_x"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 20,
                                      step = 4},
                                    {
                                      arg = {
                                        {
                                          line = 20,
                                          name = "IDENT",
                                          value = "x_"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 20,
                                      step = 4}},
                                  call = {
                                    name = "operator =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 20,
                                  step = 4}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 20,
                              step = 4},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 21,
                                              name = "IDENT",
                                              value = "this"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 21,
                                          step = 4},
                                        {
                                          arg = {},
                                          call = {
                                            name = "count",
                                            proc = <function>},
                                          line = 21,
                                          step = 4},
                                        {
                                          line = 21,
                                          name = "IDENT",
                                          value = "m_y"}},
                                      call = {
                                        name = "rep_operator ->",
                                        obj = "->",
                                        proc = <function>},
                                      line = 21,
                                      step = 4},
                                    {
                                      arg = {
                                        {
                                          line = 21,
                                          name = "IDENT",
                                          value = "y_"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 21,
                                      step = 4}},
                                  call = {
                                    name = "operator =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 21,
                                  step = 4}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 21,
                              step = 4}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 21,
                          step = 4}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 21,
                      scope = {
                        4,
                        5}}},
                  call = {
                    name = "constructordef",
                    proc = <function>},
                  line = 21,
                  step = 5}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 21,
              step = 5},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 21,
                      step = 5},
                    {
                      arg = {},
                      call = {
                        name = "operatordecl {name="=",symbol="assign"}",
                        obj = {
                          name = "=",
                          symbol = "assign"},
                        proc = <function>},
                      line = 21,
                      step = 5},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 24,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 24,
                                  step = 5},
                                {
                                  line = 24,
                                  name = "IDENT",
                                  value = "x_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 24,
                              step = 5},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 24,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 24,
                                  step = 5},
                                {
                                  line = 24,
                                  name = "IDENT",
                                  value = "y_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 24,
                              step = 5}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 24,
                          step = 5},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 26,
                                              name = "IDENT",
                                              value = "this"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 26,
                                          step = 5},
                                        {
                                          arg = {},
                                          call = {
                                            name = "count",
                                            proc = <function>},
                                          line = 26,
                                          step = 5},
                                        {
                                          line = 26,
                                          name = "IDENT",
                                          value = "m_x"}},
                                      call = {
                                        name = "rep_operator ->",
                                        obj = "->",
                                        proc = <function>},
                                      line = 26,
                                      step = 5},
                                    {
                                      arg = {
                                        {
                                          line = 26,
                                          name = "IDENT",
                                          value = "x_"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 26,
                                      step = 5}},
                                  call = {
                                    name = "operator =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 26,
                                  step = 5}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 26,
                              step = 5},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 27,
                                          name = "IDENT",
                                          value = "m_y"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 27,
                                      step = 5},
                                    {
                                      arg = {
                                        {
                                          line = 27,
                                          name = "IDENT",
                                          value = "y_"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 27,
                                      step = 5}},
                                  call = {
                                    name = "operator =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 27,
                                  step = 5}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 27,
                              step = 5}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 27,
                          step = 5}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 27,
                      scope = {
                        5,
                        6}}},
                  call = {
                    name = "operator_procdef {const=false}",
                    obj = {
                      const = false},
                    proc = <function>},
                  line = 27,
                  step = 6}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 27,
              step = 6},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 27,
                      step = 6},
                    {
                      line = 30,
                      name = "IDENT",
                      value = "x"},
                    {
                      arg = {
                        {
                          line = 30,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 30,
                      step = 6},
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 30,
                          step = 6},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 32,
                                      name = "IDENT",
                                      value = "m_x"}},
                                  call = {
                                    name = "variable",
                                    proc = <function>},
                                  line = 32,
                                  step = 6}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 32,
                              step = 7}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 32,
                          step = 7}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 32,
                      scope = {
                        6,
                        8}}},
                  call = {
                    name = "funcdef {const=true}",
                    obj = {
                      const = true},
                    proc = <function>},
                  line = 32,
                  step = 8}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 32,
              step = 8},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 32,
                      step = 8},
                    {
                      line = 35,
                      name = "IDENT",
                      value = "y"},
                    {
                      arg = {
                        {
                          line = 35,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 35,
                      step = 8},
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 35,
                          step = 8},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 37,
                                          name = "IDENT",
                                          value = "this"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 37,
                                      step = 8},
                                    {
                                      arg = {},
                                      call = {
                                        name = "count",
                                        proc = <function>},
                                      line = 37,
                                      step = 8},
                                    {
                                      line = 37,
                                      name = "IDENT",
                                      value = "m_y"}},
                                  call = {
                                    name = "rep_operator ->",
                                    obj = "->",
                                    proc = <function>},
                                  line = 37,
                                  step = 8}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 37,
                              step = 9}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 37,
                          step = 9}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 37,
                      scope = {
                        8,
                        10}}},
                  call = {
                    name = "funcdef {const=true}",
                    obj = {
                      const = true},
                    proc = <function>},
                  line = 37,
                  step = 10}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 37,
              step = 10},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 37,
                      step = 10},
                    {
                      line = 40,
                      name = "IDENT",
                      value = "ofs_x"},
                    {
                      arg = {
                        {
                          line = 40,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 40,
                      step = 10},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 40,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 40,
                                  step = 10},
                                {
                                  line = 40,
                                  name = "IDENT",
                                  value = "addx"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 40,
                              step = 10}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 40,
                          step = 10},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 42,
                                          name = "IDENT",
                                          value = "m_x"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 42,
                                      step = 10},
                                    {
                                      arg = {
                                        {
                                          line = 42,
                                          name = "IDENT",
                                          value = "addx"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 42,
                                      step = 10}},
                                  call = {
                                    name = "operator +",
                                    obj = "+",
                                    proc = <function>},
                                  line = 42,
                                  step = 10}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 42,
                              step = 11}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 42,
                          step = 11}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 42,
                      scope = {
                        10,
                        12}}},
                  call = {
                    name = "funcdef {const=true}",
                    obj = {
                      const = true},
                    proc = <function>},
                  line = 42,
                  step = 12}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 42,
              step = 12},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 42,
                      step = 12},
                    {
                      line = 45,
                      name = "IDENT",
                      value = "ofs_y"},
                    {
                      arg = {
                        {
                          line = 45,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 45,
                      step = 12},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 45,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 45,
                                  step = 12},
                                {
                                  line = 45,
                                  name = "IDENT",
                                  value = "addy"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 45,
                              step = 12}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 45,
                          step = 12},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 47,
                                          name = "IDENT",
                                          value = "m_y"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 47,
                                      step = 12},
                                    {
                                      arg = {
                                        {
                                          line = 47,
                                          name = "IDENT",
                                          value = "addy"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 47,
                                      step = 12}},
                                  call = {
                                    name = "operator +",
                                    obj = "+",
                                    proc = <function>},
                                  line = 47,
                                  step = 12}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 47,
                              step = 13}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 47,
                          step = 13}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 47,
                      scope = {
                        12,
                        14}}},
                  call = {
                    name = "funcdef {const=true}",
                    obj = {
                      const = true},
                    proc = <function>},
                  line = 47,
                  step = 14}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 47,
              step = 14},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 47,
                      step = 14},
                    {
                      line = 50,
                      name = "IDENT",
                      value = "object"},
                    {
                      arg = {
                        {
                          line = 50,
                          name = "IDENT",
                          value = "Object"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 50,
                      step = 14},
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 50,
                          step = 14},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 52,
                                          name = "IDENT",
                                          value = "this"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 52,
                                      step = 14},
                                    {
                                      arg = {},
                                      call = {
                                        name = "count",
                                        proc = <function>},
                                      line = 52,
                                      step = 14},
                                    {
                                      line = 52,
                                      name = "IDENT",
                                      value = "Object"}},
                                  call = {
                                    name = "rep_operator ->",
                                    obj = "->",
                                    proc = <function>},
                                  line = 52,
                                  step = 14}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 52,
                              step = 15}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 52,
                          step = 15}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 52,
                      scope = {
                        14,
                        16}}},
                  call = {
                    name = "funcdef {const=true}",
                    obj = {
                      const = true},
                    proc = <function>},
                  line = 52,
                  step = 16}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 52,
              step = 16},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 52,
                      step = 16},
                    {
                      line = 54,
                      name = "IDENT",
                      value = "updater"},
                    {
                      arg = {
                        {
                          line = 54,
                          name = "IDENT",
                          value = "ObjectUpdater"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 54,
                      step = 16},
                    {
                      arg = {
                        {
                          arg = {},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 54,
                          step = 16},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          line = 56,
                                          name = "IDENT",
                                          value = "this"}},
                                      call = {
                                        name = "variable",
                                        proc = <function>},
                                      line = 56,
                                      step = 16},
                                    {
                                      arg = {},
                                      call = {
                                        name = "count",
                                        proc = <function>},
                                      line = 56,
                                      step = 16},
                                    {
                                      line = 56,
                                      name = "IDENT",
                                      value = "ObjectUpdater"}},
                                  call = {
                                    name = "rep_operator ->",
                                    obj = "->",
                                    proc = <function>},
                                  line = 56,
                                  step = 16}},
                              call = {
                                name = "return_value",
                                proc = <function>},
                              line = 56,
                              step = 17}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 56,
                          step = 17}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 56,
                      scope = {
                        16,
                        18}}},
                  call = {
                    name = "funcdef {const=false}",
                    obj = {
                      const = false},
                    proc = <function>},
                  line = 56,
                  step = 18}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 56,
              step = 18},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 59,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 59,
                      step = 18},
                    {
                      line = 59,
                      name = "IDENT",
                      value = "m_x"}},
                  call = {
                    name = "vardef",
                    proc = <function>},
                  line = 59,
                  step = 19}},
              call = {
                name = "definition 1",
                obj = 1,
                proc = <function>},
              line = 59,
              step = 19},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 60,
                          name = "IDENT",
                          value = "int"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 60,
                      step = 19},
                    {
                      line = 60,
                      name = "IDENT",
                      value = "m_y"}},
                  call = {
                    name = "vardef",
                    proc = <function>},
                  line = 60,
                  step = 20}},
              call = {
                name = "definition 1",
                obj = 1,
                proc = <function>},
              line = 60,
              step = 20}},
          call = {
            name = "classdef",
            proc = <function>},
          line = 60,
          step = 21}},
      call = {
        name = "definition 1",
        obj = 1,
        proc = <function>},
      line = 60,
      step = 21},
    {
      arg = {
        {
          arg = {
            {
              line = 63,
              name = "IDENT",
              value = "Line"},
            {
              arg = {
                {
                  arg = {
                    {
                      line = 63,
                      name = "IDENT",
                      value = "Point"}},
                  call = {
                    name = "typespec ",
                    obj = "",
                    proc = <function>},
                  line = 63,
                  step = 21}},
              call = {
                name = "inheritdef 1",
                obj = 1,
                proc = <function>},
              line = 63,
              step = 22},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 63,
                      step = 22},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 65,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 65,
                                  step = 22},
                                {
                                  line = 65,
                                  name = "IDENT",
                                  value = "x_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 65,
                              step = 22},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 65,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 65,
                                  step = 22},
                                {
                                  line = 65,
                                  name = "IDENT",
                                  value = "y_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 65,
                              step = 22}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 65,
                          step = 22},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 67,
                                              name = "IDENT",
                                              value = "this"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 67,
                                          step = 22},
                                        {
                                          arg = {},
                                          call = {
                                            name = "count",
                                            proc = <function>},
                                          line = 67,
                                          step = 22},
                                        {
                                          line = 67,
                                          name = "IDENT",
                                          value = "Point"}},
                                      call = {
                                        name = "rep_operator ->",
                                        obj = "->",
                                        proc = <function>},
                                      line = 67,
                                      step = 22},
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 67,
                                              name = "IDENT",
                                              value = "x_"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 67,
                                          step = 22},
                                        {
                                          arg = {
                                            {
                                              line = 67,
                                              name = "IDENT",
                                              value = "y_"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 67,
                                          step = 22}},
                                      call = {
                                        name = "structure",
                                        proc = <function>},
                                      line = 67,
                                      step = 22}},
                                  call = {
                                    name = "operator =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 67,
                                  step = 22}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 67,
                              step = 22}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 67,
                          step = 22}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 67,
                      scope = {
                        22,
                        23}}},
                  call = {
                    name = "constructordef",
                    proc = <function>},
                  line = 67,
                  step = 23}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 67,
              step = 23},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {},
                      call = {
                        name = "linkage {private=false,linkage="external"}",
                        obj = {
                          linkage = "external",
                          private = false},
                        proc = <function>},
                      line = 67,
                      step = 23},
                    {
                      line = 70,
                      name = "IDENT",
                      value = "move"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 70,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 70,
                                  step = 23},
                                {
                                  line = 70,
                                  name = "IDENT",
                                  value = "x_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 70,
                              step = 23},
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      line = 70,
                                      name = "IDENT",
                                      value = "int"}},
                                  call = {
                                    name = "typespec ",
                                    obj = "",
                                    proc = <function>},
                                  line = 70,
                                  step = 23},
                                {
                                  line = 70,
                                  name = "IDENT",
                                  value = "y_"}},
                              call = {
                                name = "paramdef",
                                proc = <function>},
                              line = 70,
                              step = 23}},
                          call = {
                            name = "paramdeflist",
                            proc = <function>},
                          line = 70,
                          step = 23},
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  arg = {
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 72,
                                              name = "IDENT",
                                              value = "this"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 72,
                                          step = 23},
                                        {
                                          arg = {},
                                          call = {
                                            name = "count",
                                            proc = <function>},
                                          line = 72,
                                          step = 23},
                                        {
                                          line = 72,
                                          name = "IDENT",
                                          value = "Point"}},
                                      call = {
                                        name = "rep_operator ->",
                                        obj = "->",
                                        proc = <function>},
                                      line = 72,
                                      step = 23},
                                    {
                                      arg = {
                                        {
                                          arg = {
                                            {
                                              line = 72,
                                              name = "IDENT",
                                              value = "x_"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 72,
                                          step = 23},
                                        {
                                          arg = {
                                            {
                                              line = 72,
                                              name = "IDENT",
                                              value = "y_"}},
                                          call = {
                                            name = "variable",
                                            proc = <function>},
                                          line = 72,
                                          step = 23}},
                                      call = {
                                        name = "structure",
                                        proc = <function>},
                                      line = 72,
                                      step = 23}},
                                  call = {
                                    name = "operator =",
                                    obj = "=",
                                    proc = <function>},
                                  line = 72,
                                  step = 23}},
                              call = {
                                name = "free_expression",
                                proc = <function>},
                              line = 72,
                              step = 23}},
                          call = {
                            name = "codeblock",
                            proc = <function>},
                          line = 72,
                          step = 23}},
                      call = {
                        name = "callablebody",
                        proc = <function>},
                      line = 72,
                      scope = {
                        23,
                        24}}},
                  call = {
                    name = "procdef {const=false}",
                    obj = {
                      const = false},
                    proc = <function>},
                  line = 72,
                  step = 24}},
              call = {
                name = "definition 2",
                obj = 2,
                proc = <function>},
              line = 72,
              step = 24}},
          call = {
            name = "classdef",
            proc = <function>},
          line = 72,
          step = 25}},
      call = {
        name = "definition 1",
        obj = 1,
        proc = <function>},
      line = 72,
      step = 25},
    {
      arg = {
        {
          arg = {
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 77,
                          name = "IDENT",
                          value = "float"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 77,
                      step = 25},
                    {
                      line = 77,
                      name = "IDENT",
                      value = "x"},
                    {
                      arg = {
                        {
                          line = 77,
                          name = "FLOAT",
                          value = "1.23"}},
                      call = {
                        name = "constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 77,
                      step = 25}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 77,
                  step = 26}},
              call = {
                name = "definition",
                proc = <function>},
              line = 77,
              step = 26},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 78,
                          name = "IDENT",
                          value = "Line"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 78,
                      step = 26},
                    {
                      line = 78,
                      name = "IDENT",
                      value = "ab"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 78,
                              name = "FLOAT",
                              value = "1.23"}},
                          call = {
                            name = "constant constexpr float",
                            obj = "constexpr float",
                            proc = <function>},
                          line = 78,
                          step = 26},
                        {
                          arg = {
                            {
                              line = 78,
                              name = "FLOAT",
                              value = "4.23"}},
                          call = {
                            name = "constant constexpr float",
                            obj = "constexpr float",
                            proc = <function>},
                          line = 78,
                          step = 26}},
                      call = {
                        name = "structure",
                        proc = <function>},
                      line = 78,
                      step = 26}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 78,
                  step = 27}},
              call = {
                name = "definition",
                proc = <function>},
              line = 78,
              step = 27},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 79,
                          name = "IDENT",
                          value = "Object"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 79,
                      step = 27},
                    {
                      line = 79,
                      name = "IDENT",
                      value = "obj"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 79,
                                  name = "IDENT",
                                  value = "ab"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 79,
                              step = 27},
                            {
                              line = 79,
                              name = "IDENT",
                              value = "object"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 79,
                          step = 27}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 79,
                      step = 27}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 79,
                  step = 28}},
              call = {
                name = "definition",
                proc = <function>},
              line = 79,
              step = 28},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 80,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 80,
                      step = 28},
                    {
                      arg = {
                        {
                          line = 80,
                          name = "DQSTRING",
                          value = "RESULT[1] x = %d\\n"}},
                      call = {
                        name = "string_constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 80,
                      step = 28},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 80,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 80,
                              step = 28},
                            {
                              line = 80,
                              name = "IDENT",
                              value = "x"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 80,
                          step = 28}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 80,
                      step = 28}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 80,
                  step = 28}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 80,
              step = 28},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 81,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 81,
                      step = 28},
                    {
                      arg = {
                        {
                          line = 81,
                          name = "DQSTRING",
                          value = "RESULT[1] y = %d\\n"}},
                      call = {
                        name = "string_constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 81,
                      step = 28},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 81,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 81,
                              step = 28},
                            {
                              line = 81,
                              name = "IDENT",
                              value = "y"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 81,
                          step = 28}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 81,
                      step = 28}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 81,
                  step = 28}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 81,
              step = 28},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 82,
                          name = "IDENT",
                          value = "ObjectUpdater"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 82,
                      step = 28},
                    {
                      line = 82,
                      name = "IDENT",
                      value = "updater"},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 82,
                                  name = "IDENT",
                                  value = "ab"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 82,
                              step = 28},
                            {
                              line = 82,
                              name = "IDENT",
                              value = "updater"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 82,
                          step = 28}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 82,
                      step = 28}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 82,
                  step = 29}},
              call = {
                name = "definition",
                proc = <function>},
              line = 82,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 83,
                          name = "IDENT",
                          value = "updater"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 83,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 83,
                              name = "CARDINAL",
                              value = "31"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 83,
                          step = 29},
                        {
                          arg = {
                            {
                              line = 83,
                              name = "CARDINAL",
                              value = "411"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 83,
                          step = 29}},
                      call = {
                        name = "structure",
                        proc = <function>},
                      line = 83,
                      step = 29}},
                  call = {
                    name = "operator =",
                    obj = "=",
                    proc = <function>},
                  line = 83,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 83,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 84,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 84,
                      step = 29},
                    {
                      arg = {
                        {
                          line = 84,
                          name = "DQSTRING",
                          value = "RESULT[2] x = %d\\n"}},
                      call = {
                        name = "string_constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 84,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 84,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 84,
                              step = 29},
                            {
                              line = 84,
                              name = "IDENT",
                              value = "x"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 84,
                          step = 29}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 84,
                      step = 29}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 84,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 84,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 85,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 85,
                      step = 29},
                    {
                      arg = {
                        {
                          line = 85,
                          name = "DQSTRING",
                          value = "RESULT[2] y = %d\\n"}},
                      call = {
                        name = "string_constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 85,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 85,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 85,
                              step = 29},
                            {
                              line = 85,
                              name = "IDENT",
                              value = "y"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 85,
                          step = 29}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 85,
                      step = 29}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 85,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 85,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 86,
                          name = "IDENT",
                          value = "updater"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 86,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 86,
                              name = "CARDINAL",
                              value = "71"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 86,
                          step = 29},
                        {
                          arg = {
                            {
                              line = 86,
                              name = "CARDINAL",
                              value = "511"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 86,
                          step = 29}},
                      call = {
                        name = "structure",
                        proc = <function>},
                      line = 86,
                      step = 29}},
                  call = {
                    name = "operator =",
                    obj = "=",
                    proc = <function>},
                  line = 86,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 86,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 87,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 87,
                      step = 29},
                    {
                      arg = {
                        {
                          line = 87,
                          name = "DQSTRING",
                          value = "RESULT[3] x = %d\\n"}},
                      call = {
                        name = "string_constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 87,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 87,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 87,
                              step = 29},
                            {
                              line = 87,
                              name = "IDENT",
                              value = "ofs_x"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 87,
                          step = 29},
                        {
                          arg = {
                            {
                              line = 87,
                              name = "INTEGER",
                              value = "-13"}},
                          call = {
                            name = "constant constexpr int",
                            obj = "constexpr int",
                            proc = <function>},
                          line = 87,
                          step = 29}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 87,
                      step = 29}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 87,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 87,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 88,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 88,
                      step = 29},
                    {
                      arg = {
                        {
                          line = 88,
                          name = "DQSTRING",
                          value = "RESULT[3] y = %d\\n"}},
                      call = {
                        name = "string_constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 88,
                      step = 29},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 88,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 88,
                              step = 29},
                            {
                              line = 88,
                              name = "IDENT",
                              value = "ofs_y"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 88,
                          step = 29},
                        {
                          arg = {
                            {
                              line = 88,
                              name = "CARDINAL",
                              value = "1"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 88,
                          step = 29}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 88,
                      step = 29}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 88,
                  step = 29}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 88,
              step = 29},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 89,
                          name = "IDENT",
                          value = "ObjectUpdater"}},
                      call = {
                        name = "typespec ",
                        obj = "",
                        proc = <function>},
                      line = 89,
                      step = 29},
                    {
                      line = 89,
                      name = "IDENT",
                      value = "updater2"},
                    {
                      arg = {
                        {
                          line = 89,
                          name = "IDENT",
                          value = "updater"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 89,
                      step = 29}},
                  call = {
                    name = "vardef_assign",
                    proc = <function>},
                  line = 89,
                  step = 30}},
              call = {
                name = "definition",
                proc = <function>},
              line = 89,
              step = 30},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 90,
                          name = "IDENT",
                          value = "updater2"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 90,
                      step = 30},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              line = 90,
                              name = "CARDINAL",
                              value = "32"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 90,
                          step = 30},
                        {
                          arg = {
                            {
                              line = 90,
                              name = "CARDINAL",
                              value = "412"}},
                          call = {
                            name = "constant constexpr uint",
                            obj = "constexpr uint",
                            proc = <function>},
                          line = 90,
                          step = 30}},
                      call = {
                        name = "structure",
                        proc = <function>},
                      line = 90,
                      step = 30}},
                  call = {
                    name = "operator =",
                    obj = "=",
                    proc = <function>},
                  line = 90,
                  step = 30}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 90,
              step = 30},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 91,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 91,
                      step = 30},
                    {
                      arg = {
                        {
                          line = 91,
                          name = "DQSTRING",
                          value = "RESULT[4] x = %d\\n"}},
                      call = {
                        name = "string_constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 91,
                      step = 30},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 91,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 91,
                              step = 30},
                            {
                              line = 91,
                              name = "IDENT",
                              value = "ofs_x"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 91,
                          step = 30},
                        {
                          arg = {
                            {
                              line = 91,
                              name = "INTEGER",
                              value = "-11"}},
                          call = {
                            name = "constant constexpr int",
                            obj = "constexpr int",
                            proc = <function>},
                          line = 91,
                          step = 30}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 91,
                      step = 30}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 91,
                  step = 30}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 91,
              step = 30},
            {
              arg = {
                {
                  arg = {
                    {
                      arg = {
                        {
                          line = 92,
                          name = "IDENT",
                          value = "printf"}},
                      call = {
                        name = "variable",
                        proc = <function>},
                      line = 92,
                      step = 30},
                    {
                      arg = {
                        {
                          line = 92,
                          name = "DQSTRING",
                          value = "RESULT[4] y = %d\\n"}},
                      call = {
                        name = "string_constant constexpr float",
                        obj = "constexpr float",
                        proc = <function>},
                      line = 92,
                      step = 30},
                    {
                      arg = {
                        {
                          arg = {
                            {
                              arg = {
                                {
                                  line = 92,
                                  name = "IDENT",
                                  value = "obj"}},
                              call = {
                                name = "variable",
                                proc = <function>},
                              line = 92,
                              step = 30},
                            {
                              line = 92,
                              name = "IDENT",
                              value = "y"}},
                          call = {
                            name = "member",
                            proc = <function>},
                          line = 92,
                          step = 30}},
                      call = {
                        name = "operator ()",
                        obj = "()",
                        proc = <function>},
                      line = 92,
                      step = 30}},
                  call = {
                    name = "operator ()",
                    obj = "()",
                    proc = <function>},
                  line = 92,
                  step = 30}},
              call = {
                name = "free_expression",
                proc = <function>},
              line = 92,
              step = 30},
            {
              arg = {
                {
                  arg = {
                    {
                      line = 93,
                      name = "CARDINAL",
                      value = "0"}},
                  call = {
                    name = "constant constexpr uint",
                    obj = "constexpr uint",
                    proc = <function>},
                  line = 93,
                  step = 30}},
              call = {
                name = "return_value",
                proc = <function>},
              line = 93,
              step = 31}},
          call = {
            name = "codeblock",
            proc = <function>},
          line = 93,
          step = 31}},
      call = {
        name = "main_procdef",
        proc = <function>},
      line = 93,
      scope = {
        25,
        32}}},
  call = {
    name = "program",
    proc = <function>},
  line = 93,
  step = 32}
