
@llvm.global_ctors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__ctors, i8* null }]
@llvm.global_dtors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__dtors, i8* null }]

declare external i32 @__gxx_personality_v0( ... ) nounwind
declare external i8* @malloc( i64 ) nounwind


define internal void @_GLOBAL__ctors() nounwind uwtable readnone optsize ssp section ".text.startup" {
  ret void
}

define internal void @_GLOBAL__dtors() nounwind uwtable readnone optsize ssp section ".text.startup" {
  ret void
}

declare external void @printf( i8*, ... ) nounwind
@string1 = private unnamed_addr constant [26 x i8] c"CALL printNumber [%d] %f\0A\00"
define external void @printNumber__double__i32$( double %r1, i32* %r2 ) #0 nounwind {
entry:
%r3 = getelementptr inbounds [26 x i8], [26 x i8]* @string1, i64 0, i64 0
%r4 = load i32, i32* %r2
call void(i8*,  ...) @printf( i8* %r3, i32 %r4, double %r1)
%r5 = load i32, i32* %r2
%r6 = add nsw i32 %r5, 1
store i32 %r6, i32* %r2
br label %L1
L1:
ret void
}
define external i32 @printNumber__double__i32( double %r1, i32 %r2 ) #0 nounwind {
entry:
%r3 = getelementptr inbounds [26 x i8], [26 x i8]* @string1, i64 0, i64 0
call void(i8*,  ...) @printf( i8* %r3, i32 %r2, double %r1)
%r4 = add nsw i32 %r2, 1
br label %L1
L1:
ret i32 %r4
}
@g_pnp = internal global void(double, i32*)* null
@string2 = private unnamed_addr constant [14 x i8] c"RES cnt = %d\0A\00"

define dso_local i32 @main(i32 %argc, i8** %argv) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*)
{
entry:
store void(double, i32*)* @printNumber__double__i32$, void(double, i32*)** @g_pnp
%r1 = alloca i32, align 4
%r2 = alloca void(double, i32*)*
store void(double, i32*)* @printNumber__double__i32$, void(double, i32*)** %r2
%r3 = alloca i32(double, i32)*
store i32(double, i32)* @printNumber__double__i32, i32(double, i32)** %r3
%r4 = alloca i32, align 4
store i32 31, i32* %r4
%r5 = load void(double, i32*)*, void(double, i32*)** %r2
call void %r5( double 0x4008E147AE147AE1, i32* %r4)
%r9 = load i32, i32* %r4
%r6 = load i32(double, i32)*, i32(double, i32)** %r3
%r7 = call i32 %r6( double 0x4010E147AE147AE1, i32 4)
%r8 = mul nsw i32 %r7, 2
%r10 = add nsw i32 %r9, %r8
store i32 %r10, i32* %r4
%r11 = load i32(double, i32)*, i32(double, i32)** %r3
%r12 = load i32, i32* %r4
%r13 = call i32 %r11( double 0x401CE147AE147AE1, i32 %r12)
%r14 = load void(double, i32*)*, void(double, i32*)** @g_pnp
call void %r14( double 0x403319999999999A, i32* %r4)
%r15 = getelementptr inbounds [14 x i8], [14 x i8]* @string2, i64 0, i64 0
%r16 = load i32, i32* %r4
call void(i8*,  ...) @printf( i8* %r15, i32 %r16)
store i32 0, i32* %r1
br label %L1
L1:
%r17 = load i32, i32* %r1
ret i32 %r17
}


