@llvm.global_ctors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__ctors, i8* null }]
@llvm.global_dtors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__dtors, i8* null }]

declare external i32 @__gxx_personality_v0( ... ) nounwind
declare external void @printf( i8*, i32 ) nounwind


define internal void @_GLOBAL__ctors() nounwind uwtable readnone optsize ssp section ".text.startup" {
  ret void
}

define internal void @_GLOBAL__dtors() nounwind uwtable readnone optsize ssp section ".text.startup" {
  ret void
}

define internal void @swap__1( i32* %r1, i32* %r2 ) #0 nounwind {
entry:
%r3 = alloca i32, align 4
%r4 = load i32, i32* %r1
store i32 %r4, i32* %r3
%r5 = load i32, i32* %r2
store i32 %r5, i32* %r1
%r6 = load i32, i32* %r3
store i32 %r6, i32* %r2
br label %L1
L1:
ret void
}
define internal i32 @fibonacci__i32( i32 %r1 ) #0 nounwind {
entry:
%r2 = alloca i32, align 4
store i32 0, i32* %r2
%r3 = alloca i32, align 4
store i32 1, i32* %r3
%r4 = alloca i32, align 4
store i32 0, i32* %r4
br label %L3
L3:
%r5 = load i32, i32* %r4
%r6 = icmp slt i32 %r5, %r1
br i1 %r6, label %L2, label %L1
L2:
%r7 = load i32, i32* %r3
%r8 = load i32, i32* %r2
%r9 = add nsw i32 %r7, %r8
store i32 %r9, i32* %r2
call void @swap__1( i32* %r2, i32* %r3)
%r10 = load i32, i32* %r4
%r11 = add nsw i32 %r10, 1
store i32 %r11, i32* %r4
br label %L3
L1:
%r12 = load i32, i32* %r3
br label %L4
L4:
ret i32 %r12
}
@string1 = private unnamed_addr constant [12 x i8] c"Result: %d\0A\00"

define dso_local i32 @main(i32 %argc, i8** %argv) #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*)
{
entry:
%r1 = alloca i32, align 4
%r2 = alloca i32, align 4
%r3 = call i32 @fibonacci__i32( i32 20)
store i32 %r3, i32* %r2
%r4 = getelementptr inbounds [12 x i8], [12 x i8]* @string1, i64 0, i64 0
%r5 = load i32, i32* %r2
call void @printf( i8* %r4, i32 %r5)
store i32 0, i32* %r1
br label %L2
L2:
br label %L1
L1:
%r6 = load i32, i32* %r1
ret i32 %r6
}


