
return {
	assign = {},
	assign_add = {},
	assign_sub = {},
	assign_mul = {},
	assign_div = {},
	assign_mod = {},
	logical_or = {},
	logical_and = {},
	bitwise_or = {},
	bitwise_xor = {},
	bitwise_and = {},
	add = {},
	sub = {},
	minus = {},
	plus = {},
	mul = {},
	div = {},
	mod = {},

	arrow = {},
	member = {},
	ptrderef = {},
	call = {},
	arrayaccess = {},

	cmpeq = {},
	cmpne = {},
	cmple = {},
	cmplt = {},
	cmpge = {},
	cmpgt = {},

	puretype = {},
	consttype = {},
	reftype = {},
	constreftype = {},
	ptrtype = {},
	constptrtype = {},
	ptrreftype = {},
	constptrreftype = {},
	movereftype = {},

	vardef = function( arg) end,
	vardef_assign = function( arg) end,
	vardef_array = function( arg) end,
	vardef_array_assign = function( arg) end,
	operator = function( arg) end,
	stm_expression = function( arg) end,
	stm_return = function( arg) end,
	conditional_if = function( arg) end,
	conditional_while = function( arg) end,

	namespaceref = function( arg) end,
	typedef = function( arg) end,
	typespec = function( arg) end,
	funcdef = function( arg) end,
	procdef = function( arg) end,
	paramdef = function( arg) end,
	program = function( arg) return arg end
}

